/-
Copyright (c) 2026 QICLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: QICLean contributors
-/
import QICLean.Channel.ChoiTypeMap.HaTwoSimpleWitness
import QICLean.Channel.PartialTranspose

/-!
# Ha's block-transpose decomposition

This module proves the second two-simple decomposition in Ha's witness
construction. It identifies the block transpose displayed on pp. 594--595 with
the repository's right-factor partial transpose and decomposes it into the
projectors generated by Ha's vectors `u_i`, `v_i`, `α_i`, and `β_{i,j}`.

No factor shuffle, negative pairing, positivity theorem for the Choi-type map,
or atomicity conclusion is asserted here.

## Reference

* [K.-C. Ha, *Atomic Positive Linear Maps in Matrix Algebras*,
  pp. 594--595][Ha1998AtomicPositiveMaps]
-/

open scoped Matrix ComplexOrder
open Finset

namespace Matrix

variable {d : ℕ} [NeZero d]

/-! ## Ha's block-transpose decomposition -/

/-- Ha's cyclic successor `i + 1`, with suffixes understood modulo `d`. -/
def haCyclicSucc (i : Fin d) : Fin d :=
  i + 1

/-- The squared exceptional cyclic weight, written in the source's two
oriented neighbouring cases. -/
theorem haCyclicWeight_mul_star (hd : 3 ≤ d) (γ : ℝ) (a b : Fin d) :
    haCyclicWeight d γ b a * star (haCyclicWeight d γ b a) =
      if a = haCyclicSucc b then (γ : ℂ) ^ 2
      else if b = haCyclicSucc a then ((γ : ℂ)⁻¹) ^ 2 else 1 := by
  have hneg : (-1 : ZMod d) ≠ 1 := by
    intro h
    have h' : ((-1 : ℤ) : ZMod d) = ((1 : ℤ) : ZMod d) := by simpa using h
    have hdvdz : (d : ℤ) ∣ (2 : ℤ) := by
      simpa using
        (ZMod.intCast_eq_intCast_iff_dvd_sub (-1 : ℤ) (1 : ℤ) d).mp h'
    have hdvd : d ∣ 2 := Int.natCast_dvd_natCast.mp hdvdz
    exact (by omega : ¬d ≤ 2) (Nat.le_of_dvd (by norm_num) hdvd)
  have hoff_one {p q : Fin d}
      (h : ZMod.finEquiv d p - ZMod.finEquiv d q = 1) :
      p = haCyclicSucc q := by
    apply (ZMod.finEquiv d).injective
    calc
      ZMod.finEquiv d p =
          (ZMod.finEquiv d p - ZMod.finEquiv d q) + ZMod.finEquiv d q := by ring
      _ = 1 + ZMod.finEquiv d q := by rw [h]
      _ = ZMod.finEquiv d (haCyclicSucc q) := by
        simp [haCyclicSucc, add_comm]
  by_cases hab : a = haCyclicSucc b
  · rw [ite_eq_left hab]
    subst a
    simp [haCyclicWeight, haCyclicSucc, haBaseWeight]
    ring
  · by_cases hba : b = haCyclicSucc a
    · rw [ite_eq_right hab, ite_eq_left hba]
      subst b
      have hw : haCyclicWeight d γ (haCyclicSucc a) a = (γ : ℂ)⁻¹ := by
        simp [haCyclicWeight, haCyclicSucc, haBaseWeight, hneg]
      rw [hw]
      simp
      ring
    · have hone : ZMod.finEquiv d a - ZMod.finEquiv d b ≠ 1 :=
        fun h ↦ hab (hoff_one h)
      have hminus : ZMod.finEquiv d a - ZMod.finEquiv d b ≠ -1 := by
        intro h
        apply hba
        apply hoff_one
        rw [show ZMod.finEquiv d b - ZMod.finEquiv d a =
          -(ZMod.finEquiv d a - ZMod.finEquiv d b) by ring, h]
        simp
      simp [haCyclicWeight, haBaseWeight, hab, hba, hone, hminus]

/-- A diagonal coordinate of `z_{r,i}` has no exceptional weight. -/
private theorem haTwoSimpleWeight_diag (hd : 3 ≤ d) (γ : ℝ)
    (r a : Fin d) : haTwoSimpleWeight d γ r (a, a) = 1 := by
  let _ : Fact (1 < d) := ⟨by omega⟩
  by_cases har : a = r
  · subst a
    simp [haTwoSimpleWeight, haCyclicWeight, haBaseWeight]
  · simp [haTwoSimpleWeight, har]

/-- Averaging the exceptional column leaves `d-1` unit weights and one cyclic
weight. -/
private theorem sum_haTwoSimpleWeight_self (γ : ℝ)
    (a b : Fin d) :
    (∑ r : Fin d,
        haTwoSimpleWeight d γ r (a, b) * star (haTwoSimpleWeight d γ r (a, b))) =
      haCyclicWeight d γ b a * star (haCyclicWeight d γ b a) + (d - 1 : ℕ) := by
  classical
  let f : Fin d → ℂ := fun r ↦
    haTwoSimpleWeight d γ r (a, b) * star (haTwoSimpleWeight d γ r (a, b))
  have hsplit := Finset.sum_erase_add (Finset.univ : Finset (Fin d)) f
    (Finset.mem_univ b)
  rw [← hsplit]
  have herase :
      (∑ r ∈ (Finset.univ : Finset (Fin d)).erase b, f r) =
        ((Finset.univ : Finset (Fin d)).erase b).card := by
    calc
      _ = ∑ _r ∈ (Finset.univ : Finset (Fin d)).erase b, (1 : ℂ) := by
        apply Finset.sum_congr rfl
        intro r hr
        have hrb : b ≠ r := (Finset.mem_erase.mp hr).1.symm
        simp [f, haTwoSimpleWeight, hrb]
      _ = _ := by simp
  rw [herase]
  simp [f, haTwoSimpleWeight, Finset.card_erase_of_mem, Fintype.card_fin, add_comm]

/-- Ha's vector
`u_i = γ / √d (e_{i+1} ⊗ e_i) + 1 / (√d γ) (e_i ⊗ e_{i+1})`
from p. 594, with zero-based cyclic indices. -/
noncomputable def haUVector (d : ℕ) [NeZero d] (γ : ℝ) (i : Fin d) :
    Fin d × Fin d → ℂ :=
  fun p ↦ (γ / Real.sqrt d : ℝ) * haTensorBasis (haCyclicSucc i) i p +
    ((Real.sqrt d * γ)⁻¹ : ℝ) * haTensorBasis i (haCyclicSucc i) p

/-- Ha's vector
`v_i = √((d-1)/d) (e_{i+1} ⊗ e_i + e_i ⊗ e_{i+1})`
from p. 594. -/
noncomputable def haVVector (d : ℕ) [NeZero d] (i : Fin d) :
    Fin d × Fin d → ℂ :=
  fun p ↦ Real.sqrt (((d : ℝ) - 1) / d) *
    (haTensorBasis (haCyclicSucc i) i p + haTensorBasis i (haCyclicSucc i) p)

theorem haCyclicSucc_ne (hd : 3 ≤ d) (i : Fin d) : haCyclicSucc i ≠ i := by
  intro h
  have hv := congrArg Fin.val h
  by_cases hi : i.val + 1 < d
  · rw [haCyclicSucc, Fin.val_add, Fin.val_one',
      Nat.mod_eq_of_lt (by omega : 1 < d), Nat.mod_eq_of_lt hi] at hv
    omega
  · have hieq : i.val + 1 = d := by omega
    rw [haCyclicSucc, Fin.val_add, Fin.val_one',
      Nat.mod_eq_of_lt (by omega : 1 < d), hieq, Nat.mod_self] at hv
    omega

private theorem haCyclicSucc_injective : Function.Injective (haCyclicSucc : Fin d → Fin d) := by
  intro i j h
  apply (ZMod.finEquiv d).injective
  have hz := congrArg (ZMod.finEquiv d) h
  simpa [haCyclicSucc] using hz

private theorem haCyclicSucc_twice_ne (hd : 3 ≤ d) (i : Fin d) :
    haCyclicSucc (haCyclicSucc i) ≠ i := by
  intro h
  have hz := congrArg (ZMod.finEquiv d) h
  have hz' : (1 : ZMod d) + 1 = 0 := by
    simpa [haCyclicSucc, add_assoc] using
      congrArg (fun z : ZMod d ↦ z - ZMod.finEquiv d i) hz
  have hzcast : ((2 : ℤ) : ZMod d) = 0 := by
    rw [show (2 : ℤ) = 1 + 1 by norm_num, Int.cast_add, Int.cast_one]
    exact hz'
  have hdvdz : (d : ℤ) ∣ (2 : ℤ) :=
    (ZMod.intCast_zmod_eq_zero_iff_dvd (2 : ℤ) d).mp hzcast
  have hdvd : d ∣ 2 := Int.natCast_dvd_natCast.mp hdvdz
  exact (by omega : ¬d ≤ 2) (Nat.le_of_dvd (by norm_num) hdvd)

omit [NeZero d] in
private theorem haTensorBasis_eq_zero_of_ne (i j : Fin d) (p : Fin d × Fin d)
    (h : p ≠ (i, j)) : haTensorBasis i j p = 0 := by
  rcases p with ⟨a, b⟩
  simp only [haTensorBasis]
  by_cases hai : a = i
  · rw [ite_eq_left hai]
    by_cases hbj : b = j
    · exact (h (Prod.ext hai hbj)).elim
    · simp [hbj]
  · simp [hai]

private theorem haUVector_eq_zero_of_not_support (γ : ℝ) (i : Fin d)
    (p : Fin d × Fin d)
    (h : p ≠ (haCyclicSucc i, i) ∧ p ≠ (i, haCyclicSucc i)) :
    haUVector d γ i p = 0 := by
  rw [haUVector, haTensorBasis_eq_zero_of_ne _ _ _ h.1,
    haTensorBasis_eq_zero_of_ne _ _ _ h.2]
  ring

private theorem haVVector_eq_zero_of_not_support (i : Fin d)
    (p : Fin d × Fin d)
    (h : p ≠ (haCyclicSucc i, i) ∧ p ≠ (i, haCyclicSucc i)) :
    haVVector d i p = 0 := by
  rw [haVVector, haTensorBasis_eq_zero_of_ne _ _ _ h.1,
    haTensorBasis_eq_zero_of_ne _ _ _ h.2]
  ring

/-- Ha's diagonal vector `α_i = e_i ⊗ e_i` from p. 595. -/
def haAlphaVector (i : Fin d) : Fin d × Fin d → ℂ :=
  haTensorBasis i i

/-- Ha's symmetric vector `β_{i,j} = e_j ⊗ e_i + e_i ⊗ e_j` from p. 595. -/
def haBetaVector (i j : Fin d) : Fin d × Fin d → ℂ :=
  fun p ↦ haTensorBasis j i p + haTensorBasis i j p

private theorem haUVector_hasSchmidtRankLE_two (γ : ℝ) (i : Fin d) :
    HasSchmidtRankLE 2 (haUVector d γ i) := by
  change HasSchmidtRankLE 2 (fun p : Fin d × Fin d ↦
    (γ / Real.sqrt d : ℝ) * haTensorBasis (haCyclicSucc i) i p +
      ((Real.sqrt d * γ)⁻¹ : ℝ) * haTensorBasis i (haCyclicSucc i) p)
  exact hasSchmidtRankLE_two_tensorBasis_add (d := d)
    ((γ / Real.sqrt d : ℝ) : ℂ) ((((Real.sqrt d * γ)⁻¹ : ℝ) : ℂ))
    (haCyclicSucc i) i i (haCyclicSucc i)

private theorem haVVector_hasSchmidtRankLE_two (i : Fin d) :
    HasSchmidtRankLE 2 (haVVector d i) := by
  change HasSchmidtRankLE 2 (fun p : Fin d × Fin d ↦
    Real.sqrt (((d : ℝ) - 1) / d) *
      (haTensorBasis (haCyclicSucc i) i p + haTensorBasis i (haCyclicSucc i) p))
  simpa only [mul_add] using
    (hasSchmidtRankLE_two_tensorBasis_add (d := d)
      ((Real.sqrt (((d : ℝ) - 1) / d) : ℝ) : ℂ)
      ((Real.sqrt (((d : ℝ) - 1) / d) : ℝ) : ℂ)
      (haCyclicSucc i) i i (haCyclicSucc i))

omit [NeZero d] in
private theorem haAlphaVector_hasSchmidtRankLE_two (i : Fin d) :
    HasSchmidtRankLE 2 (haAlphaVector i) := by
  simpa only [haAlphaVector, one_mul, zero_mul, add_zero] using
    (hasSchmidtRankLE_two_tensorBasis_add (d := d) 1 0 i i i i)

omit [NeZero d] in
private theorem haBetaVector_hasSchmidtRankLE_two (i j : Fin d) :
    HasSchmidtRankLE 2 (haBetaVector i j) := by
  change HasSchmidtRankLE 2 (fun p : Fin d × Fin d ↦
    haTensorBasis j i p + haTensorBasis i j p)
  simpa only [one_mul] using
    (hasSchmidtRankLE_two_tensorBasis_add (d := d) 1 1 j i i j)

omit [NeZero d] in
private theorem haBetaVector_ne_zero_iff (i j a b : Fin d) :
    haBetaVector i j (a, b) ≠ 0 ↔ (a = j ∧ b = i) ∨ (a = i ∧ b = j) := by
  simp only [haBetaVector, haTensorBasis]
  split_ifs <;> simp_all

omit [NeZero d] in
private theorem haBetaVector_eq_zero_of_not_support (i j a b : Fin d)
    (h : ¬((a = j ∧ b = i) ∨ (a = i ∧ b = j))) :
    haBetaVector i j (a, b) = 0 := by
  by_contra hn
  exact h ((haBetaVector_ne_zero_iff i j a b).mp hn)

omit [NeZero d] in
private theorem haBetaVector_apply_swap (i j a b : Fin d) :
    haBetaVector i j (b, a) = haBetaVector i j (a, b) := by
  simp only [haBetaVector, haTensorBasis]
  split_ifs <;> simp_all

/-- The zero-based translation of Ha's two displayed beta ranges:
`3 ≤ j ≤ d-1` when the first source index is `1`, and
`2 ≤ i ≤ d-2`, `i+2 ≤ j ≤ d` otherwise.

Equivalently, these are the naturally ordered non-neighbouring pairs, excluding
the cyclic neighbouring pair `(0, d-1)`. -/
def haBetaPairs (d : ℕ) : Finset (Fin d × Fin d) :=
  Finset.univ.filter fun p ↦
    p.1.1 + 1 < p.2.1 ∧ ¬ (p.1.1 = 0 ∧ p.2.1 + 1 = d)

/-- The beta ranges are exactly the unordered distinct pairs which are not
cyclic neighbours. -/
private theorem mem_haBetaPairs_or_swap_iff (hd : 3 ≤ d) (a b : Fin d)
    (hab : a ≠ b) :
    ((a, b) ∈ haBetaPairs d ∨ (b, a) ∈ haBetaPairs d) ↔
      a ≠ haCyclicSucc b ∧ b ≠ haCyclicSucc a := by
  have hsucc_lt (y : Fin d) (hy : y.val + 1 < d) :
      (haCyclicSucc y).val = y.val + 1 := by
    rw [haCyclicSucc, Fin.val_add, Fin.val_one',
      Nat.mod_eq_of_lt (by omega : 1 < d)]
    exact Nat.mod_eq_of_lt hy
  have hsucc_eq (y : Fin d) (hy : y.val + 1 = d) :
      (haCyclicSucc y).val = 0 := by
    rw [haCyclicSucc, Fin.val_add, Fin.val_one',
      Nat.mod_eq_of_lt (by omega : 1 < d), hy, Nat.mod_self]
  simp only [haBetaPairs, Finset.mem_filter, Finset.mem_univ, true_and]
  have ha := a.isLt
  have hb := b.isLt
  have hne : a.val ≠ b.val := fun h ↦ hab (Fin.ext h)
  constructor
  · rintro (h | h)
    · constructor
      · intro heq
        have hv := congrArg Fin.val heq
        rcases Nat.lt_or_eq_of_le (by omega : b.val + 1 ≤ d) with hblt | hbeq
        · rw [hsucc_lt b hblt] at hv
          omega
        · rw [hsucc_eq b hbeq] at hv
          omega
      · intro heq
        have hv := congrArg Fin.val heq
        have halt : a.val + 1 < d := by omega
        rw [hsucc_lt a halt] at hv
        omega
    · constructor
      · intro heq
        have hv := congrArg Fin.val heq
        have hblt : b.val + 1 < d := by omega
        rw [hsucc_lt b hblt] at hv
        omega
      · intro heq
        have hv := congrArg Fin.val heq
        rcases Nat.lt_or_eq_of_le (by omega : a.val + 1 ≤ d) with halt | haeq
        · rw [hsucc_lt a halt] at hv
          omega
        · rw [hsucc_eq a haeq] at hv
          omega
  · rintro ⟨habn, hban⟩
    by_cases hlt : a.val < b.val
    · left
      constructor
      · have hale : a.val + 1 ≤ b.val := by omega
        exact lt_of_le_of_ne hale fun heq ↦ hban <| by
          apply Fin.ext
          rw [hsucc_lt a (by omega)]
          omega
      · rintro ⟨ha0, hbtop⟩
        apply habn
        apply Fin.ext
        rw [hsucc_eq b hbtop]
        omega
    · right
      have hlt' : b.val < a.val := by omega
      constructor
      · have hble : b.val + 1 ≤ a.val := by omega
        exact lt_of_le_of_ne hble fun heq ↦ habn <| by
          apply Fin.ext
          rw [hsucc_lt b (by omega)]
          omega
      · rintro ⟨hb0, hatop⟩
        apply hban
        apply Fin.ext
        rw [hsucc_eq a hatop]
        omega

/-- A rank-one projector in Ha's displayed decomposition. -/
noncomputable def haVectorProjector (z : Fin d × Fin d → ℂ) :
    Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ :=
  vecMulVec z (star z)

private noncomputable def haCyclicProjectorSum (d : ℕ) [NeZero d] (γ : ℝ) :
    Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ :=
  ∑ i : Fin d,
    (haVectorProjector (haUVector d γ i) + haVectorProjector (haVVector d i))

private theorem haCyclicProjectorSum_apply_eq_single_forward (hd : 3 ≤ d)
    (γ : ℝ) (i : Fin d) (q : Fin d × Fin d) :
    haCyclicProjectorSum d γ (haCyclicSucc i, i) q =
      (haVectorProjector (haUVector d γ i) +
        haVectorProjector (haVVector d i)) (haCyclicSucc i, i) q := by
  classical
  rw [haCyclicProjectorSum, sum_apply, Finset.sum_eq_single i]
  · intro j _ hji
    have hforward : (haCyclicSucc i, i) ≠ (haCyclicSucc j, j) := by
      intro h
      exact hji (congrArg Prod.snd h).symm
    have hreverse : (haCyclicSucc i, i) ≠ (j, haCyclicSucc j) := by
      intro h
      have hj : j = haCyclicSucc i := (congrArg Prod.fst h).symm
      have hi : i = haCyclicSucc j := congrArg Prod.snd h
      apply haCyclicSucc_twice_ne hd i
      rw [← hj, ← hi]
    have hu := haUVector_eq_zero_of_not_support γ j (haCyclicSucc i, i)
      ⟨hforward, hreverse⟩
    have hv := haVVector_eq_zero_of_not_support j (haCyclicSucc i, i)
      ⟨hforward, hreverse⟩
    simp [add_apply, haVectorProjector, vecMulVec_apply, hu, hv]
  · simp

private theorem haCyclicProjectorSum_apply_eq_single_reverse (hd : 3 ≤ d)
    (γ : ℝ) (i : Fin d) (q : Fin d × Fin d) :
    haCyclicProjectorSum d γ (i, haCyclicSucc i) q =
      (haVectorProjector (haUVector d γ i) +
        haVectorProjector (haVVector d i)) (i, haCyclicSucc i) q := by
  classical
  rw [haCyclicProjectorSum, sum_apply, Finset.sum_eq_single i]
  · intro j _ hji
    have hforward : (i, haCyclicSucc i) ≠ (haCyclicSucc j, j) := by
      intro h
      have hi : i = haCyclicSucc j := congrArg Prod.fst h
      have hj : j = haCyclicSucc i := (congrArg Prod.snd h).symm
      apply haCyclicSucc_twice_ne hd i
      rw [← hj, ← hi]
    have hreverse : (i, haCyclicSucc i) ≠ (j, haCyclicSucc j) := by
      intro h
      exact hji (congrArg Prod.fst h).symm
    have hu := haUVector_eq_zero_of_not_support γ j (i, haCyclicSucc i)
      ⟨hforward, hreverse⟩
    have hv := haVVector_eq_zero_of_not_support j (i, haCyclicSucc i)
      ⟨hforward, hreverse⟩
    simp [add_apply, haVectorProjector, vecMulVec_apply, hu, hv]
  · simp

private theorem haCyclicProjectorSum_apply_forward_diag (hd : 3 ≤ d)
    (γ : ℝ) (i : Fin d) :
    haCyclicProjectorSum d γ (haCyclicSucc i, i) (haCyclicSucc i, i) =
      ((d : ℝ)⁻¹ : ℝ) * ((γ : ℂ) ^ 2 + (d - 1 : ℕ)) := by
  rw [haCyclicProjectorSum_apply_eq_single_forward hd]
  have hdr : (3 : ℝ) ≤ d := by exact_mod_cast hd
  have hdpos : 0 < (d : ℝ) := by nlinarith
  have hdm1 : 0 ≤ (d : ℝ) - 1 := by nlinarith
  have hspos : 0 < Real.sqrt d := Real.sqrt_pos.2 hdpos
  have hdsq : (Real.sqrt d) ^ 2 = (d : ℝ) := Real.sq_sqrt hdpos.le
  have hm1sq : (Real.sqrt ((d : ℝ) - 1)) ^ 2 = (d : ℝ) - 1 :=
    Real.sq_sqrt hdm1
  have hne := haCyclicSucc_ne hd i
  have hscalar :
      γ / Real.sqrt d * (γ / Real.sqrt d) +
          Real.sqrt ((d : ℝ) - 1) / Real.sqrt d *
            (Real.sqrt ((d : ℝ) - 1) / Real.sqrt d) =
        (d : ℝ)⁻¹ * (γ ^ 2 + (d - 1 : ℕ)) := by
    rw [Nat.cast_sub (by omega : 1 ≤ d), Nat.cast_one]
    field_simp
    ring_nf at hdsq hm1sq ⊢
    nlinarith
  simpa [add_apply, haVectorProjector, vecMulVec_apply, Pi.star_apply,
    haUVector, haVVector, haTensorBasis, hne, pow_two] using
      congrArg (fun x : ℝ ↦ (x : ℂ)) hscalar

private theorem haCyclicProjectorSum_apply_reverse_diag (hd : 3 ≤ d)
    {γ : ℝ} (hγ : 0 < γ) (i : Fin d) :
    haCyclicProjectorSum d γ (i, haCyclicSucc i) (i, haCyclicSucc i) =
      ((d : ℝ)⁻¹ : ℝ) * (((γ : ℂ)⁻¹) ^ 2 + (d - 1 : ℕ)) := by
  rw [haCyclicProjectorSum_apply_eq_single_reverse hd]
  have hdr : (3 : ℝ) ≤ d := by exact_mod_cast hd
  have hdpos : 0 < (d : ℝ) := by nlinarith
  have hspos : 0 < Real.sqrt d := Real.sqrt_pos.2 hdpos
  have hdsq : (Real.sqrt d) ^ 2 = (d : ℝ) := Real.sq_sqrt hdpos.le
  have hm1sq : (Real.sqrt (-1 + (d : ℝ))) ^ 2 = -1 + (d : ℝ) := by
    convert Real.sq_sqrt (show 0 ≤ -1 + (d : ℝ) by nlinarith)
  have hne := haCyclicSucc_ne hd i
  have hscalar :
      γ⁻¹ * (Real.sqrt d)⁻¹ * (γ⁻¹ * (Real.sqrt d)⁻¹) +
          Real.sqrt ((d : ℝ) - 1) / Real.sqrt d *
            (Real.sqrt ((d : ℝ) - 1) / Real.sqrt d) =
        (d : ℝ)⁻¹ * ((γ ^ 2)⁻¹ + (d - 1 : ℕ)) := by
    rw [Nat.cast_sub (by omega : 1 ≤ d), Nat.cast_one]
    field_simp
    ring_nf
    rw [hm1sq, hdsq]
    ring
  simpa [add_apply, haVectorProjector, vecMulVec_apply, Pi.star_apply,
    haUVector, haVVector, haTensorBasis, hne, pow_two] using
      congrArg (fun x : ℝ ↦ (x : ℂ)) hscalar

private theorem haCyclicProjectorSum_apply_forward_reverse (hd : 3 ≤ d)
    {γ : ℝ} (hγ : 0 < γ) (i : Fin d) :
    haCyclicProjectorSum d γ (haCyclicSucc i, i) (i, haCyclicSucc i) = 1 := by
  rw [haCyclicProjectorSum_apply_eq_single_forward hd]
  have hdr : (3 : ℝ) ≤ d := by exact_mod_cast hd
  have hdpos : 0 < (d : ℝ) := by nlinarith
  have hdm1 : 0 ≤ (d : ℝ) - 1 := by nlinarith
  have hspos : 0 < Real.sqrt d := Real.sqrt_pos.2 hdpos
  have hdsq : (Real.sqrt d) ^ 2 = (d : ℝ) := Real.sq_sqrt hdpos.le
  have hm1sq : (Real.sqrt ((d : ℝ) - 1)) ^ 2 = (d : ℝ) - 1 :=
    Real.sq_sqrt hdm1
  have hne := haCyclicSucc_ne hd i
  have hscalar :
      γ / Real.sqrt d * (γ⁻¹ * (Real.sqrt d)⁻¹) +
          Real.sqrt ((d : ℝ) - 1) / Real.sqrt d *
            (Real.sqrt ((d : ℝ) - 1) / Real.sqrt d) = 1 := by
    field_simp
    ring_nf at hdsq hm1sq ⊢
    nlinarith
  simpa [add_apply, haVectorProjector, vecMulVec_apply, Pi.star_apply,
    haUVector, haVVector, haTensorBasis, hne] using
      congrArg (fun x : ℝ ↦ (x : ℂ)) hscalar

private theorem haCyclicProjectorSum_apply_reverse_forward (hd : 3 ≤ d)
    {γ : ℝ} (hγ : 0 < γ) (i : Fin d) :
    haCyclicProjectorSum d γ (i, haCyclicSucc i) (haCyclicSucc i, i) = 1 := by
  rw [haCyclicProjectorSum_apply_eq_single_reverse hd]
  have hdr : (3 : ℝ) ≤ d := by exact_mod_cast hd
  have hdpos : 0 < (d : ℝ) := by nlinarith
  have hdm1 : 0 ≤ (d : ℝ) - 1 := by nlinarith
  have hspos : 0 < Real.sqrt d := Real.sqrt_pos.2 hdpos
  have hdsq : (Real.sqrt d) ^ 2 = (d : ℝ) := Real.sq_sqrt hdpos.le
  have hm1sq : (Real.sqrt ((d : ℝ) - 1)) ^ 2 = (d : ℝ) - 1 :=
    Real.sq_sqrt hdm1
  have hne := haCyclicSucc_ne hd i
  have hscalar :
      (γ⁻¹ * (Real.sqrt d)⁻¹) * (γ / Real.sqrt d) +
          Real.sqrt ((d : ℝ) - 1) / Real.sqrt d *
            (Real.sqrt ((d : ℝ) - 1) / Real.sqrt d) = 1 := by
    field_simp
    ring_nf at hdsq hm1sq ⊢
    nlinarith
  simpa [add_apply, haVectorProjector, vecMulVec_apply, Pi.star_apply,
    haUVector, haVVector, haTensorBasis, hne] using
      congrArg (fun x : ℝ ↦ (x : ℂ)) hscalar

private theorem haCyclicProjectorSum_apply_eq_zero (γ : ℝ)
    (p q : Fin d × Fin d)
    (h : ∀ i : Fin d, p ≠ (haCyclicSucc i, i) ∧ p ≠ (i, haCyclicSucc i)) :
    haCyclicProjectorSum d γ p q = 0 := by
  classical
  rw [haCyclicProjectorSum, sum_apply]
  apply Finset.sum_eq_zero
  intro i _
  have hu := haUVector_eq_zero_of_not_support γ i p (h i)
  have hv := haVVector_eq_zero_of_not_support i p (h i)
  simp [add_apply, haVectorProjector, vecMulVec_apply, hu, hv]

private theorem haCyclicProjectorSum_apply_forward_eq_zero (hd : 3 ≤ d)
    (γ : ℝ) (i : Fin d) (q : Fin d × Fin d)
    (hq : q ≠ (haCyclicSucc i, i) ∧ q ≠ (i, haCyclicSucc i)) :
    haCyclicProjectorSum d γ (haCyclicSucc i, i) q = 0 := by
  rw [haCyclicProjectorSum_apply_eq_single_forward hd]
  have hu := haUVector_eq_zero_of_not_support γ i q hq
  have hv := haVVector_eq_zero_of_not_support i q hq
  simp [add_apply, haVectorProjector, vecMulVec_apply, hu, hv]

private theorem haCyclicProjectorSum_apply_reverse_eq_zero (hd : 3 ≤ d)
    (γ : ℝ) (i : Fin d) (q : Fin d × Fin d)
    (hq : q ≠ (haCyclicSucc i, i) ∧ q ≠ (i, haCyclicSucc i)) :
    haCyclicProjectorSum d γ (i, haCyclicSucc i) q = 0 := by
  rw [haCyclicProjectorSum_apply_eq_single_reverse hd]
  have hu := haUVector_eq_zero_of_not_support γ i q hq
  have hv := haVVector_eq_zero_of_not_support i q hq
  simp [add_apply, haVectorProjector, vecMulVec_apply, hu, hv]

private noncomputable def haAlphaProjectorSum (d : ℕ) :
    Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ :=
  ∑ i : Fin d, haVectorProjector (haAlphaVector i)

omit [NeZero d] in
private theorem haAlphaProjectorSum_apply (p q : Fin d × Fin d) :
    haAlphaProjectorSum d p q = if p = q ∧ p.1 = p.2 then 1 else 0 := by
  classical
  rcases p with ⟨a, b⟩
  rcases q with ⟨c, e⟩
  simp [haAlphaProjectorSum, haVectorProjector, haAlphaVector, haTensorBasis,
    sum_apply, vecMulVec_apply, Pi.star_apply]
  aesop

/-- The beta-projector part of Ha's displayed decomposition. -/
private noncomputable def haBetaProjectorSum (d : ℕ) :
    Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ :=
  ∑ p ∈ haBetaPairs d, haVectorProjector (haBetaVector p.1 p.2)

omit [NeZero d] in
private theorem haBetaProjectorSum_apply_of_mem (a b : Fin d)
    (habmem : (a, b) ∈ haBetaPairs d) (q : Fin d × Fin d)
    (hq : q = (a, b) ∨ q = (b, a)) :
    haBetaProjectorSum d (a, b) q = 1 := by
  classical
  have hm : a.val + 1 < b.val ∧ ¬(a.val = 0 ∧ b.val + 1 = d) := by
    simpa only [haBetaPairs, Finset.mem_filter, Finset.mem_univ, true_and] using habmem
  have habord : a.val < b.val := by omega
  have hab : a ≠ b := by intro h; subst b; omega
  rcases hq with rfl | rfl
  · rw [haBetaProjectorSum, sum_apply, Finset.sum_eq_single (a, b)]
    · simp [haVectorProjector, haBetaVector, haTensorBasis, vecMulVec_apply,
        Pi.star_apply, hab]
    · intro p hp hne
      have hpm : p.1.val + 1 < p.2.val ∧
          ¬(p.1.val = 0 ∧ p.2.val + 1 = d) := by
        simpa only [haBetaPairs, Finset.mem_filter, Finset.mem_univ, true_and] using hp
      have hpord : p.1.val < p.2.val := by omega
      have hnevals : p.1.val ≠ a.val ∨ p.2.val ≠ b.val := by
        by_contra h
        push Not at h
        apply hne
        exact Prod.ext (Fin.ext h.1) (Fin.ext h.2)
      have hv : haBetaVector p.1 p.2 (a, b) = 0 := by
        apply haBetaVector_eq_zero_of_not_support
        rintro (⟨rfl, rfl⟩ | ⟨rfl, rfl⟩)
        · omega
        · exact hne (Prod.ext rfl rfl)
      simp [haVectorProjector, vecMulVec_apply, hv]
    · exact fun h ↦ (h habmem).elim
  · rw [haBetaProjectorSum, sum_apply, Finset.sum_eq_single (a, b)]
    · simp [haVectorProjector, haBetaVector, haTensorBasis, vecMulVec_apply,
        Pi.star_apply, hab]
    · intro p hp hne
      have hpm : p.1.val + 1 < p.2.val ∧
          ¬(p.1.val = 0 ∧ p.2.val + 1 = d) := by
        simpa only [haBetaPairs, Finset.mem_filter, Finset.mem_univ, true_and] using hp
      have hpord : p.1.val < p.2.val := by omega
      have hnevals : p.1.val ≠ a.val ∨ p.2.val ≠ b.val := by
        by_contra h
        push Not at h
        apply hne
        exact Prod.ext (Fin.ext h.1) (Fin.ext h.2)
      have hv : haBetaVector p.1 p.2 (a, b) = 0 := by
        apply haBetaVector_eq_zero_of_not_support
        rintro (⟨rfl, rfl⟩ | ⟨rfl, rfl⟩)
        · omega
        · exact hne (Prod.ext rfl rfl)
      simp [haVectorProjector, vecMulVec_apply, hv]
    · exact fun h ↦ (h habmem).elim

omit [NeZero d] in
private theorem haBetaProjectorSum_apply_eq_zero (a b : Fin d)
    (hnone : (a, b) ∉ haBetaPairs d ∧ (b, a) ∉ haBetaPairs d)
    (q : Fin d × Fin d) : haBetaProjectorSum d (a, b) q = 0 := by
  classical
  rw [haBetaProjectorSum, sum_apply]
  apply Finset.sum_eq_zero
  intro p hp
  have hv : haBetaVector p.1 p.2 (a, b) = 0 := by
    apply haBetaVector_eq_zero_of_not_support
    rintro (⟨rfl, rfl⟩ | ⟨rfl, rfl⟩)
    · exact hnone.2 hp
    · exact hnone.1 hp
  simp [haVectorProjector, vecMulVec_apply, hv]

omit [NeZero d] in
private theorem haBetaProjectorSum_apply_eq_zero_of_right (a b : Fin d)
    (q : Fin d × Fin d) (hq : q ≠ (a, b) ∧ q ≠ (b, a)) :
    haBetaProjectorSum d (a, b) q = 0 := by
  classical
  rw [haBetaProjectorSum, sum_apply]
  apply Finset.sum_eq_zero
  intro p _
  by_cases hpzero : haBetaVector p.1 p.2 (a, b) = 0
  · simp [haVectorProjector, vecMulVec_apply, hpzero]
  · have hp := (haBetaVector_ne_zero_iff p.1 p.2 a b).mp hpzero
    have hqzero : haBetaVector p.1 p.2 q = 0 := by
      rcases q with ⟨c, e⟩
      apply haBetaVector_eq_zero_of_not_support
      intro hqs
      rcases hp with hp | hp <;> rcases hqs with hqs | hqs
      · apply hq.1
        exact Prod.ext (hqs.1.trans hp.1.symm) (hqs.2.trans hp.2.symm)
      · apply hq.2
        exact Prod.ext (hqs.1.trans hp.2.symm) (hqs.2.trans hp.1.symm)
      · apply hq.2
        exact Prod.ext (hqs.1.trans hp.2.symm) (hqs.2.trans hp.1.symm)
      · apply hq.1
        exact Prod.ext (hqs.1.trans hp.1.symm) (hqs.2.trans hp.2.symm)
    simp [haVectorProjector, vecMulVec_apply, hqzero]

omit [NeZero d] in
private theorem haBetaProjectorSum_apply_swap_left (a b : Fin d)
    (q : Fin d × Fin d) :
    haBetaProjectorSum d (b, a) q = haBetaProjectorSum d (a, b) q := by
  classical
  simp only [haBetaProjectorSum, sum_apply]
  apply Finset.sum_congr rfl
  intro p _
  simp [haVectorProjector, vecMulVec_apply, haBetaVector_apply_swap]

/-- The right-hand side of Ha's displayed identity on p. 595. -/
noncomputable def haBlockTransposeDecomposition (d : ℕ) [NeZero d] (γ : ℝ) :
    Matrix (Fin d × Fin d) (Fin d × Fin d) ℂ :=
  (∑ i : Fin d, (
      haVectorProjector (haUVector d γ i) +
      haVectorProjector (haVVector d i) +
      haVectorProjector (haAlphaVector i))) +
    ∑ p ∈ haBetaPairs d, haVectorProjector (haBetaVector p.1 p.2)

private theorem haBlockTransposeDecomposition_eq_components (γ : ℝ) :
    haBlockTransposeDecomposition d γ =
      haCyclicProjectorSum d γ + haAlphaProjectorSum d + haBetaProjectorSum d := by
  ext p q
  simp only [haBlockTransposeDecomposition, haCyclicProjectorSum, haAlphaProjectorSum,
    haBetaProjectorSum, sum_apply, add_apply]
  rw [← Finset.sum_add_distrib]

/-- The entry formula common to Ha's root average and his displayed projector
decomposition. -/
noncomputable def haBlockTransposeEntry (d : ℕ) [NeZero d] (γ : ℝ)
    (p q : Fin d × Fin d) : ℂ :=
  if p = q then
    ((d : ℝ)⁻¹ : ℝ) *
      (haCyclicWeight d γ p.2 p.1 * star (haCyclicWeight d γ p.2 p.1) +
        (d - 1 : ℕ))
  else if p.1 = q.2 ∧ p.2 = q.1 then 1 else 0

/-- Entrywise evaluation of the block transpose of Ha's root average. -/
theorem partialTransposeRight_haAGamma_apply (hd : 3 ≤ d) (γ : ℝ)
    (p q : Fin d × Fin d) :
    partialTransposeRight (haAGamma d γ) p q = haBlockTransposeEntry d γ p q := by
  classical
  rcases p with ⟨a, b⟩
  rcases q with ⟨c, e⟩
  rw [partialTransposeRight_apply, haAGamma]
  simp only [smul_apply, sum_apply]
  rw [RCLike.real_smul_eq_coe_smul (K := ℂ) (E := ℂ)]
  simp only [smul_eq_mul]
  simp_rw [haArGamma_apply]
  by_cases hpq : (a, b) = (c, e)
  · have hac : a = c := congrArg Prod.fst hpq
    have hbe : b = e := congrArg Prod.snd hpq
    subst c
    subst e
    simp only [and_self, true_or, ↓reduceIte, mul_one]
    rw [sum_haTwoSimpleWeight_self]
    simp [haBlockTransposeEntry]
  · by_cases hswap : a = e ∧ b = c
    · rcases hswap with ⟨rfl, rfl⟩
      have hab : a ≠ b := by
        intro h
        apply hpq
        simp [h]
      have hdiag (r : Fin d) :
          haTwoSimpleWeight d γ r (a, a) *
              star (haTwoSimpleWeight d γ r (b, b)) = 1 := by
        rw [haTwoSimpleWeight_diag hd, haTwoSimpleWeight_diag hd]
        simp
      simp_rw [hdiag]
      simp [haBlockTransposeEntry, hpq, hab]
    · have hpairs : ¬((a = c ∧ b = e) ∨ (a = e ∧ b = c)) := by
        intro h
        rcases h with h | h
        · apply hpq
          exact Prod.ext h.1 h.2
        · exact hswap h
      simp_rw [ite_eq_right hpairs, mul_zero]
      simp [haBlockTransposeEntry, hpq, hswap]

private theorem haBlockTransposeDecomposition_apply (hd : 3 ≤ d) {γ : ℝ}
    (hγ : 0 < γ) (p q : Fin d × Fin d) :
    haBlockTransposeDecomposition d γ p q = haBlockTransposeEntry d γ p q := by
  classical
  rcases p with ⟨a, b⟩
  rcases q with ⟨c, e⟩
  rw [haBlockTransposeDecomposition_eq_components, add_apply, add_apply]
  by_cases hpq : (a, b) = (c, e)
  · have hac : a = c := congrArg Prod.fst hpq
    have hbe : b = e := congrArg Prod.snd hpq
    subst c
    subst e
    by_cases hab : a = b
    · subst b
      have hcyc : haCyclicProjectorSum d γ (a, a) (a, a) = 0 := by
        apply haCyclicProjectorSum_apply_eq_zero
        intro i
        constructor
        · intro h
          apply haCyclicSucc_ne hd i
          exact (congrArg Prod.fst h).symm.trans (congrArg Prod.snd h)
        · intro h
          apply haCyclicSucc_ne hd i
          exact (congrArg Prod.snd h).symm.trans (congrArg Prod.fst h)
      have hnone : (a, a) ∉ haBetaPairs d ∧ (a, a) ∉ haBetaPairs d := by
        simp [haBetaPairs]
      rw [hcyc, haAlphaProjectorSum_apply,
        haBetaProjectorSum_apply_eq_zero a a hnone]
      have hfix : a ≠ haCyclicSucc a := (haCyclicSucc_ne hd a).symm
      rw [haBlockTransposeEntry, haCyclicWeight_mul_star hd γ a a]
      simp only [hfix, ↓reduceIte]
      rw [Nat.cast_sub (by omega : 1 ≤ d), Nat.cast_one]
      norm_num
    · by_cases hforward : a = haCyclicSucc b
      · have hnotmem : ¬((a, b) ∈ haBetaPairs d ∨ (b, a) ∈ haBetaPairs d) := by
          intro hm
          exact (mem_haBetaPairs_or_swap_iff hd a b hab).mp hm |>.1 hforward
        have hnone := not_or.mp hnotmem
        rw [show haCyclicProjectorSum d γ (a, b) (a, b) =
            ((d : ℝ)⁻¹ : ℝ) * ((γ : ℂ) ^ 2 + (d - 1 : ℕ)) by
              subst a
              exact haCyclicProjectorSum_apply_forward_diag hd γ b,
          haAlphaProjectorSum_apply,
          haBetaProjectorSum_apply_eq_zero a b hnone]
        rw [haBlockTransposeEntry, haCyclicWeight_mul_star hd γ a b]
        simp [hforward, haCyclicSucc_ne hd b]
      · by_cases hreverse : b = haCyclicSucc a
        · have hnotmem :
              ¬((a, b) ∈ haBetaPairs d ∨ (b, a) ∈ haBetaPairs d) := by
            intro hm
            exact (mem_haBetaPairs_or_swap_iff hd a b hab).mp hm |>.2 hreverse
          have hnone := not_or.mp hnotmem
          rw [show haCyclicProjectorSum d γ (a, b) (a, b) =
              ((d : ℝ)⁻¹ : ℝ) *
                (((γ : ℂ)⁻¹) ^ 2 + (d - 1 : ℕ)) by
                subst b
                exact haCyclicProjectorSum_apply_reverse_diag hd hγ a,
            haAlphaProjectorSum_apply,
            haBetaProjectorSum_apply_eq_zero a b hnone]
          rw [haBlockTransposeEntry, haCyclicWeight_mul_star hd γ a b]
          have hfix : a ≠ haCyclicSucc a := (haCyclicSucc_ne hd a).symm
          have htwice : a ≠ haCyclicSucc (haCyclicSucc a) :=
            (haCyclicSucc_twice_ne hd a).symm
          simp [hreverse, hfix, htwice]
        · have hcyc : haCyclicProjectorSum d γ (a, b) (a, b) = 0 := by
            apply haCyclicProjectorSum_apply_eq_zero
            intro i
            constructor
            · intro h
              apply hforward
              exact (congrArg Prod.fst h).trans
                (congrArg haCyclicSucc (congrArg Prod.snd h).symm)
            · intro h
              apply hreverse
              exact (congrArg Prod.snd h).trans
                (congrArg haCyclicSucc (congrArg Prod.fst h).symm)
          have hmem := (mem_haBetaPairs_or_swap_iff hd a b hab).mpr
            ⟨hforward, hreverse⟩
          rcases hmem with habmem | hbamem
          · rw [hcyc, haAlphaProjectorSum_apply,
              haBetaProjectorSum_apply_of_mem a b habmem (a, b) (Or.inl rfl)]
            rw [haBlockTransposeEntry, haCyclicWeight_mul_star hd γ a b]
            simp only [hforward, hreverse, ↓reduceIte]
            rw [Nat.cast_sub (by omega : 1 ≤ d), Nat.cast_one]
            norm_num
            exact hab
          · rw [hcyc, haAlphaProjectorSum_apply,
              haBetaProjectorSum_apply_swap_left b a,
              haBetaProjectorSum_apply_of_mem b a hbamem (a, b) (Or.inr rfl)]
            rw [haBlockTransposeEntry, haCyclicWeight_mul_star hd γ a b]
            simp only [hforward, hreverse, ↓reduceIte]
            rw [Nat.cast_sub (by omega : 1 ≤ d), Nat.cast_one]
            norm_num
            exact hab
  · by_cases hswap : a = e ∧ b = c
    · rcases hswap with ⟨rfl, rfl⟩
      have hab : a ≠ b := by
        intro h
        apply hpq
        simp [h]
      by_cases hforward : a = haCyclicSucc b
      · have hnotmem : ¬((a, b) ∈ haBetaPairs d ∨ (b, a) ∈ haBetaPairs d) := by
          intro hm
          exact (mem_haBetaPairs_or_swap_iff hd a b hab).mp hm |>.1 hforward
        have hnone := not_or.mp hnotmem
        rw [show haCyclicProjectorSum d γ (a, b) (b, a) = 1 by
              subst a
              exact haCyclicProjectorSum_apply_forward_reverse hd hγ b,
          haAlphaProjectorSum_apply,
          haBetaProjectorSum_apply_eq_zero a b hnone]
        simp [haBlockTransposeEntry, hpq, hab]
      · by_cases hreverse : b = haCyclicSucc a
        · have hnotmem :
              ¬((a, b) ∈ haBetaPairs d ∨ (b, a) ∈ haBetaPairs d) := by
            intro hm
            exact (mem_haBetaPairs_or_swap_iff hd a b hab).mp hm |>.2 hreverse
          have hnone := not_or.mp hnotmem
          rw [show haCyclicProjectorSum d γ (a, b) (b, a) = 1 by
                subst b
                exact haCyclicProjectorSum_apply_reverse_forward hd hγ a,
            haAlphaProjectorSum_apply,
            haBetaProjectorSum_apply_eq_zero a b hnone]
          simp [haBlockTransposeEntry, hpq, hab]
        · have hcyc : haCyclicProjectorSum d γ (a, b) (b, a) = 0 := by
            apply haCyclicProjectorSum_apply_eq_zero
            intro i
            constructor
            · intro h
              apply hforward
              exact (congrArg Prod.fst h).trans
                (congrArg haCyclicSucc (congrArg Prod.snd h).symm)
            · intro h
              apply hreverse
              exact (congrArg Prod.snd h).trans
                (congrArg haCyclicSucc (congrArg Prod.fst h).symm)
          have hmem := (mem_haBetaPairs_or_swap_iff hd a b hab).mpr
            ⟨hforward, hreverse⟩
          rcases hmem with habmem | hbamem
          · rw [hcyc, haAlphaProjectorSum_apply,
              haBetaProjectorSum_apply_of_mem a b habmem (b, a) (Or.inr rfl)]
            simp [haBlockTransposeEntry, hpq, hab]
          · rw [hcyc, haAlphaProjectorSum_apply,
              haBetaProjectorSum_apply_swap_left b a,
              haBetaProjectorSum_apply_of_mem b a hbamem (b, a) (Or.inl rfl)]
            simp [haBlockTransposeEntry, hpq, hab]
    · by_cases hforward : a = haCyclicSucc b
      · have hq : (c, e) ≠ (haCyclicSucc b, b) ∧ (c, e) ≠ (b, haCyclicSucc b) := by
          constructor
          · intro h
            apply hpq
            subst a
            exact h.symm
          · intro h
            apply hswap
            exact ⟨hforward.trans (congrArg Prod.snd h).symm,
              (congrArg Prod.fst h).symm⟩
        rw [show haCyclicProjectorSum d γ (a, b) (c, e) = 0 by
              subst a
              exact haCyclicProjectorSum_apply_forward_eq_zero hd γ b (c, e) hq,
          haAlphaProjectorSum_apply,
          haBetaProjectorSum_apply_eq_zero_of_right a b (c, e) ⟨fun h ↦ hpq h.symm, fun h ↦ hswap
            ⟨(congrArg Prod.snd h).symm, (congrArg Prod.fst h).symm⟩⟩]
        simp [haBlockTransposeEntry, hpq, hswap]
      · by_cases hreverse : b = haCyclicSucc a
        · have hq : (c, e) ≠ (haCyclicSucc a, a) ∧ (c, e) ≠ (a, haCyclicSucc a) := by
            constructor
            · intro h
              apply hswap
              subst b
              exact ⟨(congrArg Prod.snd h).symm, (congrArg Prod.fst h).symm⟩
            · intro h
              apply hpq
              subst b
              exact h.symm
          rw [show haCyclicProjectorSum d γ (a, b) (c, e) = 0 by
                subst b
                exact haCyclicProjectorSum_apply_reverse_eq_zero hd γ a (c, e) hq,
            haAlphaProjectorSum_apply,
            haBetaProjectorSum_apply_eq_zero_of_right a b (c, e) ⟨fun h ↦ hpq h.symm, fun h ↦ hswap
              ⟨(congrArg Prod.snd h).symm, (congrArg Prod.fst h).symm⟩⟩]
          simp [haBlockTransposeEntry, hpq, hswap]
        · have hcyc : haCyclicProjectorSum d γ (a, b) (c, e) = 0 := by
            apply haCyclicProjectorSum_apply_eq_zero
            intro i
            constructor
            · intro h
              apply hforward
              exact (congrArg Prod.fst h).trans
                (congrArg haCyclicSucc (congrArg Prod.snd h).symm)
            · intro h
              apply hreverse
              exact (congrArg Prod.snd h).trans
                (congrArg haCyclicSucc (congrArg Prod.fst h).symm)
          rw [hcyc, haAlphaProjectorSum_apply,
            haBetaProjectorSum_apply_eq_zero_of_right a b (c, e) ⟨fun h ↦ hpq h.symm, fun h ↦ hswap
              ⟨(congrArg Prod.snd h).symm, (congrArg Prod.fst h).symm⟩⟩]
          simp [haBlockTransposeEntry, hpq, hswap]

/-- **Ha 1998, pp. 594--595, displayed block-transpose identity.**

Ha writes `A = Σ A_{p,q} ⊗ e_{p,q}` and transposes the displayed matrix
units `e_{p,q}`.  Thus his `Aᵀ` is the repository's second-factor partial
transpose `partialTransposeRight`, not `partialTransposeLeft`. -/
theorem partialTransposeRight_haAGamma_eq_haBlockTransposeDecomposition
    (hd : 3 ≤ d) {γ : ℝ} (hγ : 0 < γ) :
    partialTransposeRight (haAGamma d γ) = haBlockTransposeDecomposition d γ := by
  ext p q
  rw [partialTransposeRight_haAGamma_apply hd γ p q,
    haBlockTransposeDecomposition_apply hd hγ p q]

/-- Ha's displayed block-transpose sum consists of projectors onto vectors of
Schmidt rank at most two. -/
theorem haBlockTransposeDecomposition_hasSchmidtNumberLE_two (γ : ℝ) :
    HasSchmidtNumberLE 2 (haBlockTransposeDecomposition d γ) := by
  rw [haBlockTransposeDecomposition]
  apply HasSchmidtNumberLE.add
  · exact hasSchmidtNumberLE_sum Finset.univ fun i _ ↦
      ((hasSchmidtNumberLE_vecMulVec (haUVector_hasSchmidtRankLE_two γ i)).add
        (hasSchmidtNumberLE_vecMulVec (haVVector_hasSchmidtRankLE_two i))).add
          (hasSchmidtNumberLE_vecMulVec (haAlphaVector_hasSchmidtRankLE_two i))
  · exact hasSchmidtNumberLE_sum (haBetaPairs d) fun p _ ↦
      hasSchmidtNumberLE_vecMulVec (haBetaVector_hasSchmidtRankLE_two p.1 p.2)

/-- **Ha 1998, pp. 594--595, second `V₂` decomposition.**

The partial transpose on Ha's displayed block factor belongs to `V₂`.  In
the repository's tensor convention this is `partialTransposeRight`, and the
witnessing decomposition is exactly the displayed sum of the vectors `u_i`,
`v_i`, `α_i`, and `β_{i,j}` above.  No negative-pairing or indecomposability
statement is included here. -/
theorem partialTransposeRight_haAGamma_hasSchmidtNumberLE_two
    (hd : 3 ≤ d) {γ : ℝ} (hγ : 0 < γ) :
    HasSchmidtNumberLE 2 (partialTransposeRight (haAGamma d γ)) := by
  rw [partialTransposeRight_haAGamma_eq_haBlockTransposeDecomposition hd hγ]
  exact haBlockTransposeDecomposition_hasSchmidtNumberLE_two γ

end Matrix
