"""Collect the three comparisons and complete library/book verification."""
from pathlib import Path
import hashlib,gzip,json,re,shutil
from pypdf import PdfReader
r=Path.cwd();e=Path(__file__).resolve().parent;sha=lambda d:hashlib.sha256(d).hexdigest()
def row(p):return {'path':str(p.relative_to(r)),'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size}
def dump(n,v):(e/n).write_text(json.dumps(v,indent=2)+'\n')
f=json.loads((e/'source-freeze.json').read_text());names=json.loads((r/'docs/provenance/evidence/schurLabelMoments8753/public-declarations.json').read_text())['new']
pdf=r/'output/pdf/area-law-schur-label-moments-blueprint.pdf';pdf.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(r/'blueprint/print/print.pdf',pdf)
raw=(e/'pdf.log').read_bytes();archive=gzip.compress(raw,mtime=0);(e/'pdf.log.gz').write_bytes(archive)
dump('compressed-logs.json',{'files':[{'raw_path':str((e/'pdf.log').relative_to(r)),'archive_path':str((e/'pdf.log.gz').relative_to(r)),'raw_bytes':len(raw),'archive_bytes':len(archive),'raw_sha256':sha(raw),'archive_sha256':sha(archive),'compression':'gzip.compress(raw,mtime=0); original bytes recover exactly.'}]})
dump('generated-output-hashes.json',{'files':[row(r/p) for p in ['blueprint/print/print.pdf','blueprint/print/print.bbl','blueprint/lean_decls','blueprint/web/ch-schur_labels.html',str(pdf.relative_to(r))]]})
visual=json.loads((e/'inspected-pages.json').read_text())
dump('pdf-visual-inspection.json',{'physical_pages':visual['physical_pages'],'printed_pages':visual['printed_pages'],'all_pages_inspected':True,'images':[row(e/f'page-{n}.png') for n in visual['physical_pages']],'inspection':visual['inspection']})
images=[row(p) for p in sorted(e.glob('*.png')) if not p.name.startswith('page-')];mobile=json.loads((e/'mobile-equations.json').read_text())
dump('web-visual-inspection.json',{'all_images_inspected':True,'widths':[1280,360],'images':images,'mobile_displayed_formulas':mobile,'mobile_local_right_endpoints':sum('right_endpoint' in x for x in mobile),'inspection':'All three complete statements and proofs inspected at desktop/mobile widths; every displayed formula checked, including local scroll endpoints. Supported kernel convention, arbitrary negative-comparison exponent and restricted copy-transfer exponent readable.'})
dump('kernel-summary.json',{'source_revision':f['source_revision'],'declarations':names,'raw_log':str((e/'axioms-final.log').relative_to(r)),'sha256':sha((e/'axioms-final.log').read_bytes()),'axioms':['propext','Classical.choice','Quot.sound'],'exact_name_reports':3,'matches_original_leaf_raw_report':True})
build=(e/'full-build.log').read_text();jobs=int(re.search(r'Build completed successfully \((\d+) jobs\)',build).group(1))
dump('verification.json',{'mathematical_source_revision':f['mathematical_source_revision'],'leaf_evidence_revision':f['leaf_evidence_revision'],'unique_inclusion_revision':f['source_revision'],'checked_source_revision':f['source_revision'],'checks':[json.loads(p.read_text()) for p in sorted(e.glob('*-exit.json')) if p.name!='manifest-check-exit.json'],'complete_library_jobs':jobs,'complete_pdf_pages':len(PdfReader(pdf).pages),'native_inventory':json.loads((e/'native-targets.json').read_text()),'whole_web_reader':json.loads((e/'whole-web-reader.log').read_text()),'fresh_exact_kernel_reports':3,'original_owned_provenance_entries':3,'source_scope':'Centered Schur-label transfer from supported surprisal moments. Positive comparison u>=0 with trace-one; negative comparison arbitrary real u without normalization; tensor-copy polynomial remainder for 0<=u and 2u<=1. Signed independent-copy rate estimate remains downstream.','preservation':'Frozen four mathematical/exposition files and entire canonical leaf exact; external Lean SHA2d460... and original22 historical records retained. Checked Holder parent source/evidence mechanically preserved with exact generated Representation import exception; ledger authority6c. No unchanged parent semantic audit repeated.','shared_source_exceptions':{'authoritative_parent':f['leaf_evidence_revision'],'QICLean/Representation.lean':'Exactly one generated SchurLabelMoments import.','blueprint/src/chapter/ch13_schur_labels.tex':'Exactly one final schur_label_moments fragment input with surrounding newline.'}})
exclude={'evidence-sha256.json','manifest-check.log','manifest-check-exit.json','pdf.log'};dump('evidence-sha256.json',{'files':[row(p) for p in sorted(e.iterdir()) if p.is_file() and p.name not in exclude]});print('Collected complete source-bound Schur-label integration evidence.')
