import QICLean.Analysis.ShiftedDensityTruncation

set_option linter.hashCommand false

#print axioms Matrix.spectralProjectionGE
#print axioms Matrix.shiftedPowerHead
#print axioms Matrix.shiftedPowerTail
#print axioms Matrix.IsHermitian.spectralProjectionGE_eq_cfc
#print axioms Matrix.IsHermitian.isStarProjection_spectralProjectionGE
#print axioms Matrix.IsHermitian.commute_spectralProjectionGE
#print axioms Matrix.PosSemidef.add_smul_one_rpow_eq_cfc
#print axioms Matrix.PosSemidef.commute_add_smul_one_rpow_spectralProjectionGE
#print axioms Matrix.shiftedPowerHead_add_shiftedPowerTail
#print axioms Matrix.PosSemidef.shiftedPowerHead_eq_cfc
#print axioms Matrix.PosSemidef.shiftedPowerTail_eq_cfc
#print axioms Matrix.PosSemidef.shiftedPowerHead_posSemidef
#print axioms Matrix.PosSemidef.shiftedPowerTail_posSemidef
#print axioms Matrix.PosSemidef.shiftedPowerHead_mul_shiftedPowerTail
#print axioms Matrix.PosSemidef.shiftedPowerTail_mul_shiftedPowerHead
#print axioms Matrix.PosSemidef.add_smul_one_rpow_mul_neg
#print axioms Matrix.PosSemidef.range_shiftedPowerHead
#print axioms Matrix.PosSemidef.rank_shiftedPowerHead
#print axioms Matrix.PosSemidef.mul_rank_spectralProjectionGE_le_trace
#print axioms Matrix.PosSemidef.rank_shiftedPowerHead_le
#print axioms Matrix.PosSemidef.l2_opNorm_shiftedPowerTail_le
