"""Collect original-source integration evidence and inspected complete artifacts."""
from pathlib import Path
import hashlib,gzip,json,shutil
r=Path.cwd();e=Path(__file__).resolve().parent;sha=lambda d:hashlib.sha256(d).hexdigest()
def row(p):return {'path':str(p.relative_to(r)),'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size}
def dump(n,v):(e/n).write_text(json.dumps(v,indent=2)+'\n')
f=json.loads((e/'source-freeze.json').read_text());names=json.loads((r/'docs/provenance/evidence/weightedTraceHolder8753/public-declarations.json').read_text())
pdf=r/'output/pdf/area-law-weighted-trace-holder-blueprint.pdf';pdf.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(r/'blueprint/print/print.pdf',pdf)
raw=(e/'pdf.log').read_bytes();archive=gzip.compress(raw,mtime=0);(e/'pdf.log.gz').write_bytes(archive)
dump('compressed-logs.json',{'files':[{'raw_path':str((e/'pdf.log').relative_to(r)),'archive_path':str((e/'pdf.log.gz').relative_to(r)),'raw_bytes':len(raw),'archive_bytes':len(archive),'raw_sha256':sha(raw),'archive_sha256':sha(archive),'compression':'gzip.compress(raw,mtime=0); original bytes recover exactly.'}]})
dump('generated-output-hashes.json',{'files':[row(r/p) for p in ['blueprint/print/print.pdf','blueprint/print/print.bbl','blueprint/lean_decls','blueprint/web/ch-schur_labels.html',str(pdf.relative_to(r))]]})
dump('pdf-visual-inspection.json',{'physical_pages':[459,460],'printed_pages':[458,459],'all_pages_inspected':True,'images':[row(e/f'page-{n}.png') for n in [459,460]],'inspection':'All three new mathematical statements and complete proofs, actual coordinate product resolutions, binary weight endpoints and arbitrary mass, direct scalar weighted Holder argument and finite-family induction inspected. Fifth-root product and arbitrary real exponent clear; no overlap or clipping.'})
images=[row(p) for p in sorted(e.glob('*.png')) if not p.name.startswith('page-')];mobile=json.loads((e/'mobile-equations.json').read_text())
dump('web-visual-inspection.json',{'all_images_inspected':True,'widths':[1280,360],'images':images,'mobile_displayed_formulas':mobile,'mobile_local_right_endpoints':sum('right_endpoint' in x for x in mobile),'inspection':'Complete coordinate, binary and finite-family statements and all open proofs visually inspected at desktop/mobile widths. All five mobile displays checked; binary statement right endpoint shows the full second trace factor and exponent. The other displays fit. Full viewport context captures also inspected.'})
dump('kernel-summary.json',{'source_revision':f['source_revision'],'declarations':names,'raw_log':str((e/'axioms-final.log').relative_to(r)),'sha256':sha((e/'axioms-final.log').read_bytes()),'axioms':['propext','Classical.choice','Quot.sound'],'exact_name_reports':11,'matches_original_leaf_raw_report':True})
dump('verification.json',{'mathematical_source_revision':f['mathematical_source_revision'],'leaf_evidence_revision':f['leaf_evidence_revision'],'unique_inclusion_revision':f['source_revision'],'checked_source_revision':f['source_revision'],'checks':[json.loads(p.read_text()) for p in sorted(e.glob('*-exit.json')) if p.name!='manifest-check-exit.json'],'complete_library_jobs':9824,'complete_pdf_pages':472,'native_inventory':json.loads((e/'native-targets.json').read_text()),'whole_web_reader':json.loads((e/'whole-web-reader.log').read_text()),'fresh_exact_kernel_reports':11,'original_owned_provenance_entries':5,'source_scope':'Auxiliary genuine weighted trace Holder for commuting Hermitian observables and arbitrary PSD weight; all real finite-family exponent, binary endpoints, zero trace weight, empty ambient and one-factor case included. Actual physical five-factor construction and signed rate remain subsequent.','preservation':'All five Lean files, fragment/reader/ledger and original leaf remain exact; original three provenance shards preserved; six old signatures unchanged; published ca72/a820 refs and prior saved PDFs exact. No wider inherited semantic audit claimed.','shared_source_exceptions':{'authoritative_parent':f['leaf_evidence_revision'],'QICLean/Analysis.lean':'Exactly one generated WeightedTraceHolder import.','blueprint/src/chapter/ch13_schur_labels.tex':'Exactly one final weighted_trace_holder fragment input with surrounding newline.'},'historical_diagnostics':'Root pre-freeze target typing attempts and own leaf wrapper/ Python dependency diagnostics are retained verbatim; all final source-bound production/verification checks passed and frozen source did not change.'})
exclude={'evidence-sha256.json','manifest-check.log','manifest-check-exit.json','pdf.log'};dump('evidence-sha256.json',{'files':[row(p) for p in sorted(e.iterdir()) if p.is_file() and p.name not in exclude]});print('Collected complete source-bound Holder integration evidence.')
