"""Collect the conditional quantitative label transfer and its full checks."""
from pathlib import Path
import hashlib,gzip,json,re,shutil
from pypdf import PdfReader
r=Path.cwd();e=Path(__file__).resolve().parent;sha=lambda d:hashlib.sha256(d).hexdigest()
def row(p):return {'path':str(p.relative_to(r)),'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size}
def dump(n,v):(e/n).write_text(json.dumps(v,indent=2)+'\n')
f=json.loads((e/'source-freeze.json').read_text());names=json.loads((r/'docs/provenance/evidence/schurLabelMGF8753/declarations.json').read_text())
pdf=r/'output/pdf/area-law-schur-label-moment-bounds-blueprint.pdf';pdf.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(r/'blueprint/print/print.pdf',pdf)
compressed=[]
for name in ['pdf.log','full-build.log','declaration-sync.log','web.log','raw-log-diff-check.log']:
 raw=(e/name).read_bytes();archive=gzip.compress(raw,mtime=0);(e/(name+'.gz')).write_bytes(archive)
 compressed.append({'raw_path':str((e/name).relative_to(r)),'archive_path':str((e/(name+'.gz')).relative_to(r)),'raw_bytes':len(raw),'archive_bytes':len(archive),'raw_sha256':sha(raw),'archive_sha256':sha(archive),'compression':'gzip.compress(raw,mtime=0); original bytes recover exactly.'})
dump('compressed-logs.json',{'files':compressed})
dump('generated-output-hashes.json',{'files':[row(r/p) for p in ['blueprint/print/print.pdf','blueprint/print/print.bbl','blueprint/lean_decls','blueprint/web/ch-schur_labels.html',str(pdf.relative_to(r))]]})
visual=json.loads((e/'inspected-pages.json').read_text())
dump('pdf-visual-inspection.json',{'physical_pages':visual['physical_pages'],'printed_pages':visual['printed_pages'],'all_pages_inspected':True,'images':[row(e/f'page-{n}.png') for n in visual['physical_pages']],'inspection':visual['inspection']})
images=[row(p) for p in sorted(e.glob('*.png')) if not p.name.startswith('page-')];mobile=json.loads((e/'mobile-equations.json').read_text())
dump('web-visual-inspection.json',{'all_images_inspected':True,'widths':[1280,360],'images':images,'mobile_displayed_formulas':mobile,'mobile_local_right_endpoints':sum('right_endpoint' in x for x in mobile),'inspection':'The complete combined mathematical statement and full proof inspected at desktop/mobile widths; every displayed formula checked, including actual local scroll endpoints. The screenshot helper hides only the fixed page header and navigation controls, and uses a taller viewport, so the full mobile title is visible; the actual page overflow checks run with the unchanged page header. The assumed centred surprisal estimate, derived interval and constants, both signs and dimension-dependent logarithmic loss remain explicit.'})
dump('kernel-summary.json',{'source_revision':f['source_revision'],'declarations':names,'raw_log':str((e/'axioms-final.log').relative_to(r)),'sha256':sha((e/'axioms-final.log').read_bytes()),'axioms':['propext','Classical.choice','Quot.sound'],'exact_name_reports':2,'matches_original_leaf_raw_report':True})
job=int(re.search(r'Build completed successfully \((\d+) jobs\)',(e/'full-build.log').read_text()).group(1))
dump('verification.json',{'mathematical_source_revision':f['mathematical_source_revision'],'leaf_evidence_revision':f['leaf_evidence_revision'],'comparison_evidence_revision':f['comparison_evidence_revision'],'joined_parent_revision':f['joined_parent_revision'],'unique_inclusion_revision':f['source_revision'],'excluded_command_attempts':json.loads((e/'excluded-commands.json').read_text()),'checks':[json.loads(p.read_text()) for p in sorted(e.glob('*-exit.json')) if p.name!='manifest-check-exit.json'],'complete_library_jobs':job,'complete_pdf_pages':len(PdfReader(pdf).pages),'native_inventory':json.loads((e/'native-targets.json').read_text()),'whole_web_reader':json.loads((e/'whole-web-reader.log').read_text()),'fresh_exact_kernel_reports':2,'original_owned_provenance_entries':2,'source_scope':'Conditional transfer from an explicitly assumed quadratic bound on the actual centred k-copy surprisal moment. No one-copy-to-iid identification, signed-rate derivation or full comparator claim.','preservation':'Three original source/exposition files, the entire root697 packet/88 bindings/12 successful records and excluded Python-dependency failure,26 historical text records and checkedS3 child retained exactly. No inherited semantic audit repeated.','shared_source_exceptions':{'root_leaf_parent':'6c8a3e8cfaf896ebf6eeac3d8782193847755905','checked_joined_parent':f['joined_parent_revision'],'QICLean/Analysis.lean':'Exact checked Holder import inherited from S3, no further change.','QICLean/Representation.lean':'Exact checked S3 import plus exactly one new SchurLabelMomentBounds import.','blueprint/src/chapter/ch13_schur_labels.tex':'Exact checked Holder and S3 inputs plus exactly one schur_label_moment_bounds input.'}})
exclude={'evidence-sha256.json','manifest-check.log','manifest-check-exit.json','pdf.log','full-build.log','declaration-sync.log','web.log','raw-log-diff-check.log'};dump('evidence-sha256.json',{'files':[row(p) for p in sorted(e.iterdir()) if p.is_file() and p.name not in exclude]});print('Collected complete source-bound quantitative label integration evidence.')
