/-
Copyright (c) 2026 QICLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: QICLean contributors
-/
-- This file is generated by scripts/generate_import_aggregators.py.
-- Do not edit it directly; run the generator instead.
-- Import architecture: docs/import_structure.md.
-- Generated aggregator module: QICLean.Algebra

import QICLean.Algebra.BlockPermutation
import QICLean.Algebra.ComplexPhasePositivity
import QICLean.Algebra.CornerCompression
import QICLean.Algebra.DependentBlockDiagonal
import QICLean.Algebra.EigenspaceMap
import QICLean.Algebra.EqualRangeRightFactor
import QICLean.Algebra.FinSum
import QICLean.Algebra.FiniteCauchySchwarz
import QICLean.Algebra.FrameOperator
import QICLean.Algebra.FrobeniusHilbert
import QICLean.Algebra.HermitianHelpers
import QICLean.Algebra.HermitianSpectrumMultiplicity
import QICLean.Algebra.HermitianSpectrumPerturbation
import QICLean.Algebra.HermitianSpectrumPreserver
import QICLean.Algebra.HermitianTracePower
import QICLean.Algebra.HermitianUnitaryConjugacy
import QICLean.Algebra.KramersDegeneracy
import QICLean.Algebra.KroneckerFactorPositivity
import QICLean.Algebra.MatrixAux
import QICLean.Algebra.MatrixCongruence
import QICLean.Algebra.MatrixFamilySupport
import QICLean.Algebra.MatrixGramUnitary
import QICLean.Algebra.MatrixKernelRigidity
import QICLean.Algebra.MatrixKroneckerEmbed
import QICLean.Algebra.MatrixMulRange
import QICLean.Algebra.MatrixOperatorSpace
import QICLean.Algebra.MatrixRankClosed
import QICLean.Algebra.MatrixReindexUnitary
import QICLean.Algebra.MatrixSpectralDecomp
import QICLean.Algebra.MatrixTracePairing
import QICLean.Algebra.MatrixTracePowerContinuity
import QICLean.Algebra.MatrixUnitaryBetween
import QICLean.Algebra.NewtonGirard
import QICLean.Algebra.OperatorBlock
import QICLean.Algebra.OperatorSchmidt
import QICLean.Algebra.OrthogonalProjection
import QICLean.Algebra.PerronFrobenius
import QICLean.Algebra.PosSemidefSupport
import QICLean.Algebra.PositiveSemidefiniteNormalization
import QICLean.Algebra.RankOneSandwich
import QICLean.Algebra.RectangularChoi
import QICLean.Algebra.ScalarCommutant
import QICLean.Algebra.ShiftedTracePowerSpectrum
import QICLean.Algebra.SkolemNoether
import QICLean.Algebra.SkolemNoetherUnitary
import QICLean.Algebra.SpinCover
import QICLean.Algebra.StarSubalgebraBlockDiagonal
import QICLean.Algebra.StarSubalgebraBlockForm
import QICLean.Algebra.StarSubalgebraIntertwinerIsometry
import QICLean.Algebra.StarSubalgebraIrreducibleDecomp
import QICLean.Algebra.StarSubalgebraIsotypic
import QICLean.Algebra.StarSubalgebraIsotypicDecomp
import QICLean.Algebra.StarSubalgebraIsotypicFactorization
import QICLean.Algebra.StarSubalgebraSchur
import QICLean.Algebra.StarSubalgebraSemisimple
import QICLean.Algebra.StarSubalgebraSimpleModule
import QICLean.Algebra.StarSubalgebraSpatial
import QICLean.Algebra.StarSubalgebraUnitaryIntertwiner
import QICLean.Algebra.TracePowerCharPoly
import QICLean.Algebra.TracePurity
import QICLean.Algebra.TraceReindex
import QICLean.Algebra.UnitModulusPowerSum
import QICLean.Algebra.ZModCyclicSums
