/-
Copyright (c) 2026 QICLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: QICLean contributors
-/
-- This file is generated by scripts/generate_import_aggregators.py.
-- Do not edit it directly; run the generator instead.
-- Import architecture: docs/import_structure.md.
-- Generated aggregator module: QICLean.Representation

import QICLean.Representation.Branching
import QICLean.Representation.BranchingPieri
import QICLean.Representation.ColumnAntisymmetrizer
import QICLean.Representation.CommutantDimension
import QICLean.Representation.GroupedCopies
import QICLean.Representation.HighestWeight
import QICLean.Representation.HookDimension
import QICLean.Representation.HookFormula
import QICLean.Representation.HookRecursion
import QICLean.Representation.IrrepLabelCount
import QICLean.Representation.IrrepLabels
import QICLean.Representation.IsotypicDimension
import QICLean.Representation.JointIsotypic
import QICLean.Representation.LabelProjectors
import QICLean.Representation.MergeDimensions
import QICLean.Representation.MergeMoment
import QICLean.Representation.PartitionCount
import QICLean.Representation.PermutationRepresentation
import QICLean.Representation.ReplicaRatio
import QICLean.Representation.ReplicaWeight
import QICLean.Representation.SchurLabelCommutation
import QICLean.Representation.SchurSurprisal
import QICLean.Representation.SchurWeylCommutant
import QICLean.Representation.SchurWeylLabels
import QICLean.Representation.SchurWeylLift
import QICLean.Representation.TensorPowerAction
