/-
Copyright (c) 2026 QICLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: QICLean contributors
-/
import Mathlib.Analysis.Normed.Algebra.MatrixExponential
import Mathlib.Analysis.SpecialFunctions.Exponential
import Mathlib.Analysis.Calculus.Deriv.Slope
import Mathlib.Analysis.Calculus.Deriv.Mul
import Mathlib.Analysis.Calculus.Deriv.Add
import Mathlib.Data.Matrix.Basis
import Mathlib.Analysis.CStarAlgebra.Matrix
import Mathlib.Tactic.FunProp
import Mathlib.Tactic.Push

/-!
# Hermitian exponential paths

The punctured-neighborhood result uses differentiation and a matrix unit,
not eigenvalue enumeration or a trigonometric framework.
-/

open scoped Matrix Matrix.Norms.Operator
open Filter NormedSpace
open scoped Topology

namespace Matrix
variable {n : Type*} [Fintype n] [DecidableEq n]

/-- The continuous path generated by a Hermitian matrix. -/
noncomputable def hermitianUnitaryPath (H : Matrix n n ℂ) (t : ℝ) : Matrix n n ℂ :=
  exp (t • (Complex.I • H))

@[simp] theorem hermitianUnitaryPath_zero (H : Matrix n n ℂ) :
    hermitianUnitaryPath H 0 = 1 := by simp [hermitianUnitaryPath]

/-- The exponential path is continuous. -/
theorem continuous_hermitianUnitaryPath (H : Matrix n n ℂ) :
    Continuous (hermitianUnitaryPath H) := by
  unfold hermitianUnitaryPath
  fun_prop

/-- The path respects addition, with a single fixed generator. -/
theorem hermitianUnitaryPath_add (H : Matrix n n ℂ) (s t : ℝ) :
    hermitianUnitaryPath H (s + t) =
      hermitianUnitaryPath H s * hermitianUnitaryPath H t := by
  unfold hermitianUnitaryPath
  rw [add_smul]
  exact NormedSpace.exp_add_of_commute ((Commute.refl (Complex.I • H)).smul_left s |>.smul_right t)

/-- Hermitian generators give unitary matrices. -/
theorem hermitianUnitaryPath_mul_conjTranspose
    (H : Matrix n n ℂ) (hH : H.IsHermitian) (t : ℝ) :
    hermitianUnitaryPath H t * (hermitianUnitaryPath H t)ᴴ = 1 := by
  have hskew : (t • (Complex.I • H))ᴴ = -(t • (Complex.I • H)) := by
    simp [Matrix.conjTranspose_smul, hH.eq]
  change exp (t • (Complex.I • H)) * (exp (t • (Complex.I • H)))ᴴ = 1
  rw [← Matrix.exp_conjTranspose, hskew,
    ← Matrix.exp_add_of_commute (t • (Complex.I • H)) (-(t • (Complex.I • H)))
      (Commute.refl (t • (Complex.I • H))).neg_right]
  simp

/-- The same exponential path viewed as a group homomorphism. -/
noncomputable def hermitianUnitaryRepresentation
    (H : Matrix n n ℂ) (hH : H.IsHermitian) :
    Multiplicative ℝ →* Matrix.unitaryGroup n ℂ where
  toFun t := ⟨hermitianUnitaryPath H t.toAdd,
    Matrix.mem_unitaryGroup_iff.mpr (hermitianUnitaryPath_mul_conjTranspose H hH _)⟩
  map_one' := by ext; simp
  map_mul' s t := by
    apply Subtype.ext
    exact hermitianUnitaryPath_add H s.toAdd t.toAdd

/-- A differentiable curve with nonzero derivative and zero initial value
is nonzero in a punctured neighborhood of its initial parameter. -/
private theorem eventually_ne_zero_of_hasDerivAt
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    {f : ℝ → E} {v : E} (hf : HasDerivAt f v 0) (hf0 : f 0 = 0) (hv : v ≠ 0) :
    ∀ᶠ t in 𝓝[≠] (0 : ℝ), f t ≠ 0 := by
  have hs : ∀ᶠ t in 𝓝[≠] (0 : ℝ), slope f 0 t ≠ 0 :=
    hf.tendsto_slope (isClosed_singleton.isOpen_compl.mem_nhds hv)
  filter_upwards [hs] with t ht
  intro hft
  apply ht
  simp [slope, hf0, hft]

/-- A nonscalar matrix exponential remains nonscalar for sufficiently small
nonzero real parameters. Hermiticity is not needed for this analytic fact. -/
theorem eventually_hermitianUnitaryPath_nonscalar
    (K : Matrix n n ℂ) (hK : ∀ c : ℂ, K ≠ c • 1) :
    ∀ᶠ t in 𝓝[≠] (0 : ℝ), ∀ c : ℂ, hermitianUnitaryPath K t ≠ c • 1 := by
  classical
  have hWitness : ∃ a b : n, ¬ Commute (Matrix.single a b 1) K := by
    by_contra! hAll
    obtain ⟨c, hc⟩ := Matrix.mem_range_scalar_iff_commute_single'.mpr hAll
    apply hK c
    rw [← hc]
    ext a b
    simp [Matrix.scalar, Matrix.diagonal, Matrix.one_apply]
  obtain ⟨a, b, hBK⟩ := hWitness
  let B : Matrix n n ℂ := Matrix.single a b 1
  have hdiff : B * K - K * B ≠ 0 := by
    intro h
    exact hBK (sub_eq_zero.mp h)
  have hd := hasDerivAt_exp_smul_const (𝕂 := ℝ) (Complex.I • K) 0
  have hderiv := (hd.const_mul B).sub (hd.mul_const B)
  have hderiv_ne : B * (exp ((0 : ℝ) • (Complex.I • K)) * (Complex.I • K)) -
      (exp ((0 : ℝ) • (Complex.I • K)) * (Complex.I • K)) * B ≠ 0 := by
    simpa only [zero_smul, exp_zero, one_mul, Matrix.mul_smul, smul_mul_assoc,
      ← smul_sub] using smul_ne_zero Complex.I_ne_zero hdiff
  have hevent := eventually_ne_zero_of_hasDerivAt hderiv (by simp) hderiv_ne
  filter_upwards [hevent] with t ht
  intro c hc
  apply ht
  change B * hermitianUnitaryPath K t - hermitianUnitaryPath K t * B = 0
  simp [hc]

end Matrix
