/-
Copyright (c) 2026 QICLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: QICLean contributors
-/
import QICLean.Analysis.UnitaryEvolution
import QICLean.Analysis.SpectralFilter.MatrixFilter
import Mathlib.Analysis.Calculus.ContDiff.Operations
import Mathlib.Analysis.Normed.Module.FiniteDimension

/-!
# Evolution generated by a projected interaction-picture observable

For a complex-linear, Hermitian-preserving contraction `P` on finite matrices,
the generator `G(t) = P (e^{itH} B e^{-itH})` is smooth, Hermitian, and bounded
in operator norm by `‖B‖`, whenever `H` and `B` are Hermitian. Consequently it
has a unique global unitary evolution, starting at the identity, which solves
`U'(t) = (I • G(t)) * U(t)`.

Continuity of `P` follows from finite dimensionality. The hypotheses contain
neither a supplied propagator nor a regularity or boundedness assumption on
the time-dependent generator. All norms are the L2 operator norm, and empty
finite matrix index types are allowed. No idempotence of `P` is needed.

For two Hermitian Hamiltonians `H'` and `H`, the explicit product
`e^{itH'} e^{-itH}` solves the unprojected equation with observable `H' - H`.
The final theorem constructs the projected evolution and bounds its distance
from this product by `ε * |t|`, whenever the generator-projection error is at
most `ε` between `0` and `t`.

## References

Polynomial-PEPS, September 24, 2026, Section 2, lines 513–536.
<https://github.com/openai/math/blob/adc7f1241b42e322a6451854ab7e4b4c146bf78a/preprints/Polynomial-PEPS-approximation-of-gapped-square-grid-ground-states-September-24-2026/build/sections/02-information.tex>
This is the generic linear-map specialization of the localized evolution in
that argument. The construction of a physical conditional expectation and
its support properties belong to the separate physical adapter.
Independently formalized; no upstream Lean proof text reused.
-/

open scoped Matrix Matrix.Norms.L2Operator NNReal ContDiff

variable {n : Type*} [Fintype n] [DecidableEq n]

/-- The exponential path is smooth at every order, without requiring the
matrix to be Hermitian. -/
theorem Matrix.contDiff_hermitianUnitaryPath (H : Matrix n n ℂ) (k : ℕ∞ω) :
    ContDiff ℝ k (Matrix.hermitianUnitaryPath H) := by
  have hexp : ContDiff ℝ k (NormedSpace.exp : Matrix n n ℂ → Matrix n n ℂ) :=
    contDiff_iff_contDiffAt.mpr fun A ↦
      (NormedSpace.exp_analytic (𝕂 := ℝ) A).contDiffAt
  exact hexp.comp (contDiff_id.smul contDiff_const)

namespace MatrixEvolution

/-- The projected interaction-picture generator `P (e^{itH} B e^{-itH})`.
This definition uses the L2 operator norm on the matrix algebra. -/
noncomputable def projectedGenerator
    (P : Matrix n n ℂ →ₗ[ℂ] Matrix n n ℂ) (H B : Matrix n n ℂ)
    (t : ℝ) : Matrix n n ℂ :=
  P (Matrix.hermitianUnitaryPath H t * B * Matrix.hermitianUnitaryPath H (-t))

@[simp] theorem projectedGenerator_zero
    (P : Matrix n n ℂ →ₗ[ℂ] Matrix n n ℂ) (H B : Matrix n n ℂ) :
    projectedGenerator P H B 0 = P B := by
  simp [projectedGenerator]

/-- Every finite-dimensional complex linear map gives a smooth projected
generator. Neither norm contraction nor Hermitian preservation is needed
for this regularity statement. -/
theorem contDiff_projectedGenerator
    (P : Matrix n n ℂ →ₗ[ℂ] Matrix n n ℂ) (H B : Matrix n n ℂ) (k : ℕ∞ω) :
    ContDiff ℝ k (projectedGenerator P H B) := by
  let L : Matrix n n ℂ →L[ℝ] Matrix n n ℂ :=
    P.toContinuousLinearMap.restrictScalars ℝ
  have hconj : ContDiff ℝ k (fun t : ℝ ↦
      Matrix.hermitianUnitaryPath H t * B * Matrix.hermitianUnitaryPath H (-t)) :=
    ((Matrix.contDiff_hermitianUnitaryPath H k).mul contDiff_const).mul
      ((Matrix.contDiff_hermitianUnitaryPath H k).comp contDiff_neg)
  exact L.contDiff.comp hconj

/-- A Hermitian-preserving map preserves Hermiticity of the interaction-picture
observable at every real time. -/
theorem isHermitian_projectedGenerator
    (P : Matrix n n ℂ →ₗ[ℂ] Matrix n n ℂ)
    (hP : ∀ A, A.IsHermitian → (P A).IsHermitian)
    {H B : Matrix n n ℂ} (hH : H.IsHermitian) (hB : B.IsHermitian) (t : ℝ) :
    (projectedGenerator P H B t).IsHermitian := by
  apply hP
  rw [← SpectralFilter.hermitianUnitaryPath_conjTranspose hH t]
  exact Matrix.isHermitian_mul_mul_conjTranspose _ hB

/-- A contractive map gives the uniform physical operator-norm bound `‖B‖`.
The observable `B` need not be Hermitian for this estimate. -/
theorem norm_projectedGenerator_le
    (P : Matrix n n ℂ →ₗ[ℂ] Matrix n n ℂ) (hP : ∀ A, ‖P A‖ ≤ ‖A‖)
    {H : Matrix n n ℂ} (hH : H.IsHermitian) (B : Matrix n n ℂ) (t : ℝ) :
    ‖projectedGenerator P H B t‖ ≤ ‖B‖ := by
  exact (hP _).trans_eq (SpectralFilter.norm_hermitianUnitaryPath_conj hH B t)

/-- The projected interaction-picture generator has an actual unique global
unitary evolution. Only the static linear-map laws and Hermiticity of `H` and
`B` are assumed; smoothness and the uniform bound are proved above.
Polynomial-PEPS, September 24, 2026, Section 2, lines 513–536. -/
theorem exists_unique_projected_unitary_solution
    (P : Matrix n n ℂ →ₗ[ℂ] Matrix n n ℂ)
    (hPherm : ∀ A, A.IsHermitian → (P A).IsHermitian)
    (hPnorm : ∀ A, ‖P A‖ ≤ ‖A‖)
    {H B : Matrix n n ℂ} (hH : H.IsHermitian) (hB : B.IsHermitian) :
    ∃ U : ℝ → Matrix n n ℂ, U 0 = 1 ∧
      (∀ t, HasDerivAt U ((Complex.I • projectedGenerator P H B t) * U t) t) ∧
      (∀ t, U t ∈ Matrix.unitaryGroup n ℂ) ∧
      ∀ V : ℝ → Matrix n n ℂ, V 0 = 1 →
        (∀ t, HasDerivAt V ((Complex.I • projectedGenerator P H B t) * V t) t) →
        V = U := by
  exact exists_unique_unitary_solution (projectedGenerator P H B)
    (contDiff_projectedGenerator P H B 1)
    (isHermitian_projectedGenerator P hPherm hH hB) ‖B‖₊
    (norm_projectedGenerator_le P hPnorm hH B)

/-- Differentiating the explicit interaction-picture product gives its actual
time-dependent generator. Exponential cancellation proves the identity
without assuming either a derivative formula or unitarity of the product.
Hermiticity is not needed for this differential identity.
Polynomial-PEPS, September 24, 2026, Section 2, lines 513–536. -/
theorem hasDerivAt_hermitianUnitaryPath_mul_neg
    (H' H : Matrix n n ℂ) (t : ℝ) :
    HasDerivAt
      (fun s ↦ Matrix.hermitianUnitaryPath H' s * Matrix.hermitianUnitaryPath H (-s))
      ((Complex.I • (Matrix.hermitianUnitaryPath H' t * (H' - H) *
          Matrix.hermitianUnitaryPath H' (-t))) *
        (Matrix.hermitianUnitaryPath H' t * Matrix.hermitianUnitaryPath H (-t))) t := by
  have hleft : HasDerivAt (Matrix.hermitianUnitaryPath H')
      (Matrix.hermitianUnitaryPath H' t * (Complex.I • H')) t :=
    hasDerivAt_exp_smul_const (𝕂 := ℝ) (Complex.I • H') t
  have hright : HasDerivAt (fun s ↦ Matrix.hermitianUnitaryPath H (-s))
      (-(Complex.I • H) * Matrix.hermitianUnitaryPath H (-t)) t := by
    simpa only [Matrix.hermitianUnitaryPath, Function.comp_def, neg_one_smul, neg_mul] using
      (hasDerivAt_exp_smul_const' (𝕂 := ℝ) (Complex.I • H) (-t)).scomp t
        (hasDerivAt_neg t)
  have hcancel :
      Matrix.hermitianUnitaryPath H' (-t) * Matrix.hermitianUnitaryPath H' t = 1 := by
    simpa only [neg_neg] using SpectralFilter.hermitianUnitaryPath_mul_neg H' (-t)
  have hprod :
      (Complex.I • (Matrix.hermitianUnitaryPath H' t * (H' - H) *
        Matrix.hermitianUnitaryPath H' (-t))) *
        (Matrix.hermitianUnitaryPath H' t * Matrix.hermitianUnitaryPath H (-t)) =
      Complex.I • (Matrix.hermitianUnitaryPath H' t * (H' - H) *
        Matrix.hermitianUnitaryPath H (-t)) := by
    rw [smul_mul_assoc]
    congr 1
    calc
      (Matrix.hermitianUnitaryPath H' t * (H' - H) *
          Matrix.hermitianUnitaryPath H' (-t)) *
          (Matrix.hermitianUnitaryPath H' t * Matrix.hermitianUnitaryPath H (-t)) =
          Matrix.hermitianUnitaryPath H' t * (H' - H) *
            (Matrix.hermitianUnitaryPath H' (-t) * Matrix.hermitianUnitaryPath H' t) *
            Matrix.hermitianUnitaryPath H (-t) := by simp only [mul_assoc]
      _ = _ := by rw [hcancel, mul_one]
  apply (hleft.mul hright).congr_deriv
  rw [hprod]
  simp only [Matrix.mul_smul, smul_mul_assoc, neg_mul, mul_neg, sub_eq_add_neg,
    mul_assoc, add_mul, mul_add, smul_add, smul_neg]

/-- Construct the unique projected evolution and compare it to the explicit
product `e^{itH'} e^{-itH}`. The same constructed path works at every real
time, including negative times. The only remaining estimate to supply is the
projection error of the generator on the unordered interval between `0` and
`t`; no propagator or derivative is assumed.
Polynomial-PEPS, September 24, 2026, Section 2, lines 513–536. -/
theorem exists_unique_projected_unitary_solution_compare
    (P : Matrix n n ℂ →ₗ[ℂ] Matrix n n ℂ)
    (hPherm : ∀ A, A.IsHermitian → (P A).IsHermitian)
    (hPnorm : ∀ A, ‖P A‖ ≤ ‖A‖)
    {H' H : Matrix n n ℂ} (hH' : H'.IsHermitian) (hH : H.IsHermitian) :
    ∃ U : ℝ → Matrix n n ℂ, U 0 = 1 ∧
      (∀ t, HasDerivAt U ((Complex.I • projectedGenerator P H' (H' - H) t) * U t) t) ∧
      (∀ t, U t ∈ Matrix.unitaryGroup n ℂ) ∧
      (∀ W : ℝ → Matrix n n ℂ, W 0 = 1 →
        (∀ t, HasDerivAt W ((Complex.I • projectedGenerator P H' (H' - H) t) * W t) t) →
        W = U) ∧
      ∀ t ε : ℝ,
        (∀ s ∈ Set.uIcc 0 t,
          ‖Matrix.hermitianUnitaryPath H' s * (H' - H) *
            Matrix.hermitianUnitaryPath H' (-s) - projectedGenerator P H' (H' - H) s‖ ≤ ε) →
        ‖Matrix.hermitianUnitaryPath H' t * Matrix.hermitianUnitaryPath H (-t) - U t‖ ≤
          ε * |t| := by
  obtain ⟨U, hU0, hU, hunit, huniq⟩ := exists_unique_projected_unitary_solution
    P hPherm hPnorm hH' (hH'.sub hH)
  refine ⟨U, hU0, hU, hunit, huniq, ?_⟩
  intro t ε herror
  exact norm_sub_le_of_generator_bound
    (G := projectedGenerator LinearMap.id H' (H' - H))
    (H := projectedGenerator P H' (H' - H))
    (U := fun s ↦ Matrix.hermitianUnitaryPath H' s * Matrix.hermitianUnitaryPath H (-s))
    (V := U)
    (contDiff_projectedGenerator LinearMap.id H' (H' - H) 1).continuous
    (contDiff_projectedGenerator P H' (H' - H) 1).continuous
    (isHermitian_projectedGenerator LinearMap.id (fun _ hA ↦ hA) hH' (hH'.sub hH))
    (isHermitian_projectedGenerator P hPherm hH' (hH'.sub hH))
    (by simp) hU0 (hasDerivAt_hermitianUnitaryPath_mul_neg H' H) hU t ε herror

end MatrixEvolution
