"""Collect the immutable command records, inspected artifacts and portable evidence hashes."""
from pathlib import Path
import gzip,hashlib,json,shutil
root=Path.cwd();e=Path(__file__).resolve().parent
sha=lambda data:hashlib.sha256(data).hexdigest()
def dump(name,value): (e/name).write_text(json.dumps(value,indent=2)+'\n')
def row(path):
 data=path.read_bytes();return {'path':str(path.relative_to(root)),'sha256':sha(data),'bytes':len(data)}
freeze=json.loads((e/'source-freeze.json').read_text())
output=root/'output/pdf/area-law-replica-physical-label-moment-blueprint.pdf'
output.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(root/'blueprint/print/print.pdf',output)
raw=(e/'pdf.log').read_bytes();archive=gzip.compress(raw,mtime=0);(e/'pdf.log.gz').write_bytes(archive)
dump('compressed-logs.json',{'files':[{'raw_path':str((e/'pdf.log').relative_to(root)),'archive_path':str((e/'pdf.log.gz').relative_to(root)),'raw_bytes':len(raw),'archive_bytes':len(archive),'raw_sha256':sha(raw),'archive_sha256':sha(archive),'compression':'gzip.compress(raw,mtime=0); original bytes recover exactly.'}]})
dump('generated-output-hashes.json',{'files':[row(root/p) for p in ['blueprint/print/print.pdf','blueprint/print/print.bbl','blueprint/lean_decls','blueprint/web/ch-schur_labels.html',str(output.relative_to(root))]]})
dump('pdf-visual-inspection.json',{'physical_pages':[460,461],'printed_pages':[459,460],'all_pages_inspected':True,'inspection':'Entire good-region/exterior setting, actual regrouped component, retained label exponential, all-real exact trace identity, complete proof and subsequent signed-rate scope paragraph inspected in rendered PNGs. Clear mathematics, no clipping or overlap.','images':[row(e/f'page-{n}.png') for n in [460,461]]})
images=sorted(p for p in e.glob('*.png') if not p.name.startswith('page-'))
dump('web-visual-inspection.json',{'all_images_inspected':True,'widths':[1280,360],'images':[row(p) for p in images],'inspection':'Complete setting, statement, full open proof and closing scope paragraph inspected at desktop/mobile widths. Both setting displays fit their local containers. The main numbered equation uses the existing reader horizontal scroll container; its right endpoint was reached and the full equality and closing equation number inspected. No production layout change was needed.','mobile_context_displays':json.loads((e/'mobile-context-equations.json').read_text()),'mobile_statement_displays':json.loads((e/'mobile-equations.json').read_text()),'mobile_reader_right_endpoint':json.loads((e/'mobile-reader-endpoint.json').read_text()),'source_scope_checked':'Unit one-copy ground vector only; arbitrary exterior register and vector, all real exponent, zero copies and zero component included; exact expectation without signed analytic rate claim.'})
axioms=(e/'axioms-final.log').read_bytes()
dump('kernel-summary.json',{'declarations':freeze['declarations'],'axioms':['propext','Classical.choice','Quot.sound'],'source_revision':freeze['source_revision'],'raw_log':str((e/'axioms-final.log').relative_to(root)),'sha256':sha(axioms),'matches_original_leaf_raw_report':axioms==(root/'docs/provenance/evidence/replicaPhysicalLabelMoment8750/bound-axioms.log').read_bytes()})
records=[json.loads(p.read_text()) for p in sorted(e.glob('*-exit.json')) if p.name!='manifest-check-exit.json']
dump('verification.json',{'mathematical_source_revision':freeze['mathematical_source_revision'],'leaf_evidence_revision':freeze['leaf_evidence_revision'],'unique_inclusion_revision':freeze['source_revision'],'checked_source_revision':freeze['source_revision'],'published_parent_revision':'a820e67e2f30782485361fa71c8c0763981f8edb','declarations':freeze['declarations'],'checks':records,'complete_library_jobs':9826,'complete_pdf_pages':473,'native_inventory':json.loads((e/'native-targets.json').read_text()),'whole_web_reader':json.loads((e/'whole-web-reader.log').read_text()),'fresh_owned_original_provenance_entries':1,'fresh_owned_standard_kernel_reports':1,'inherited_evidence':'Mechanical SHA/Git preservation only; all49 original leaf files and89 portable parent bindings preserved; inherited semantic audits not repeated.','shared_source_exceptions':{'authoritative_parent':freeze['leaf_evidence_revision'],'QICLean/Analysis.lean':'Exactly one generated import QICLean.Analysis.ReplicaPhysicalLabelMoment.','blueprint/src/chapter/ch13_schur_labels.tex':'Exactly one final input fragment/replica_physical_label_moment, with surrounding newline.'},'historical_diagnostics':[{'record':'native-before-web-exit.json','exit_code':1,'cause':'The chapter-only pre-web sync inventory had3692 declarations and excluded fragment targets. The early native inventory assertion failed before the actual complete web generation. The complete web generated3766 unique declarations including the owned target exactly once; final native helper and actual checkdecls passed0. No proof/source change.'},{'packet':'docs/provenance/evidence/replicaPhysicalLabelMoment8750','cause':'The original leaf retains two audit-wrapper module-header/hash-command linter failures. Corrected wrappers and every final source-bound mathematical check passed. Frozen proof/exposition unchanged.'}],'mathematical_scope':'Exact complex physical label-exponential trace identity for all real exponents, derived from the actual excitation component and regional product density. No signed centred label-moment rate or sharp comparator is assumed or proved.'})
exclude={'evidence-sha256.json','manifest-check.log','manifest-check-exit.json','pdf.log'}
dump('evidence-sha256.json',{'files':[row(p) for p in sorted(e.iterdir()) if p.is_file() and p.name not in exclude]})
print('Collected portable original-source integration evidence and exact inspected output hashes.')
