/-
Copyright (c) 2026 QICLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: QICLean contributors
-/
import Mathlib.Algebra.Algebra.Subalgebra.Lattice
import Mathlib.Analysis.Complex.Basic
import Mathlib.LinearAlgebra.Matrix.ToLin

/-!
# Actions of finite matrix families

This file defines the unital algebra generated by a finite family of complex matrices,
invariant submodules for the family's natural action, and irreducibility of that action.
-/

namespace Matrix

variable {d D : ℕ}

/-- The unital subalgebra of `M_D(ℂ)` generated by the matrix family. -/
def algSpan
    (A : Fin d → Matrix (Fin D) (Fin D) ℂ) : Subalgebra ℂ (Matrix (Fin D) (Fin D) ℂ) :=
  Algebra.adjoin ℂ (Set.range A)

/-- Each matrix in the family is in the algebra span. -/
theorem algSpan_mem (A : Fin d → Matrix (Fin D) (Fin D) ℂ) (i : Fin d) : A i ∈ algSpan A :=
  Algebra.subset_adjoin ⟨i, rfl⟩

/-- A submodule `W` of `ℂ^D` is `A`-invariant if every `A i` maps `W` into itself. -/
def IsInvariantSubmodule
    (A : Fin d → Matrix (Fin D) (Fin D) ℂ) (W : Submodule ℂ (Fin D → ℂ)) : Prop :=
  ∀ i : Fin d, ∀ v ∈ W, (A i).mulVec v ∈ W

/-- The irreducible-action condition: no nontrivial `A`-invariant submodule. -/
def IsIrreducibleAction (A : Fin d → Matrix (Fin D) (Fin D) ℂ) : Prop :=
  ∀ W : Submodule ℂ (Fin D → ℂ), IsInvariantSubmodule A W → W = ⊥ ∨ W = ⊤

end Matrix
