"""Check immutable parent proof bytes and the original recorded evidence."""
from pathlib import Path
import hashlib,json,subprocess,re
root=Path(__file__).resolve().parents[4];e=Path(__file__).resolve().parent
refs=['5a83568097c77798bdd3f77dc892c338749381bf','d96fcdb7e3f3fe66b4bd622163e6d64fcbf0e4d3']
def tree(rev,paths):
 raw=subprocess.check_output(['git','ls-tree','-r','-z',rev,*paths],cwd=root)
 return {record.split(b'\t',1)[1].decode():record.split(b'\t',1)[0].split()[2].decode() for record in raw.split(b'\0') if record}
def blob(data):return hashlib.sha1(b'blob '+str(len(data)).encode()+b'\0'+data).hexdigest()
rows=[]
for rev in refs:
 for p,expected in tree(rev,['docs/provenance/evidence','docs/provenance/openai-math.d']).items():
  data=(root/p).read_bytes();assert blob(data)==expected,(rev,p)
  rows.append({'revision':rev,'path':p,'sha256':hashlib.sha256(data).hexdigest()})
write=lambda n,j:(e/n).write_text(json.dumps(j,indent=2)+'\n')
write('inherited-byte-preservation.json',{'records':rows,'count':len(rows)})
inventories=[]
for p in sorted((root/'docs/provenance/evidence').glob('*/evidence-sha256.json')):
 if p.parent==e:continue
 obj=json.loads(p.read_text())
 if isinstance(obj,list):items=obj
 elif 'files' in obj:items=obj['files']
 else:items=[{'path':str((p.parent/k).relative_to(root)) if not k.startswith('docs/') else k,'sha256':v} for k,v in obj.items()]
 for item in items:
  data=(root/item['path']).read_bytes();assert hashlib.sha256(data).hexdigest()==item['sha256'],(p,item['path'])
 inventories.append({'inventory':str(p.relative_to(root)),'verified_bindings':len(items),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
for p in sorted((root/'docs/provenance/evidence').glob('*/manifest.json')):
 obj=json.loads(p.read_text());bindings=obj.get('sha256',{})
 if not isinstance(bindings,dict):continue
 count=0
 for name,digest in bindings.items():
  if not isinstance(digest,str):continue
  target=root/name if name.startswith('docs/') else p.parent/name
  if not str(target.relative_to(root)).startswith('docs/provenance/'):continue
  assert hashlib.sha256(target.read_bytes()).hexdigest()==digest,(p,name)
  count+=1
 inventories.append({'inventory':str(p.relative_to(root)),'verified_bindings':count,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
write('inherited-inventory-check.json',{'inventories':inventories,'total_bindings':sum(x['verified_bindings'] for x in inventories)})
proofs=[];inherited_updates=[];generated=[]
authoritative=tree(refs[0],['QICLean'])
for rev in refs[:2]:
 for p,expected in tree(rev,['QICLean']).items():
  data=(root/p).read_bytes()
  if b'This file is generated by scripts/generate_import_aggregators.py.' in data:
   generated.append({'revision':rev,'path':p,'original_blob':expected,'current_blob':blob(data),'current_sha256':hashlib.sha256(data).hexdigest(),'exact_original_bytes':blob(data)==expected});continue
  actual=blob(data)
  assert actual==expected,(rev,p)
  proofs.append({'revision':rev,'path':p,'sha256':hashlib.sha256(data).hexdigest(),'exact_original_bytes':actual==expected})
write('generated-import-preservation.json',{'records':generated,'changed_paths':[row for row in generated if not row['exact_original_bytes']],'generator_check':'imports-exit.json'})
write('production-preservation.json',{'records':proofs,'count':len(proofs),'inherited_accepted_main_updates':inherited_updates,'excluded_generated_aggregators':'Generated imports are checked by the generator; every handwritten source is compared with its original Git blob, with newer accepted-main versions explicitly identified.'})
print('Preserved',len(rows),'parent evidence/shard bindings, verified',sum(x['verified_bindings'] for x in inventories),'inventory hashes and',len(proofs),'parent source bindings.')
