/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import QICLean.Channel.Semigroup.Basic
import QICLean.Channel.Basic
import Mathlib.Analysis.Calculus.Deriv.Mul
import Mathlib.Analysis.Calculus.MeanValue
import Mathlib.Topology.Algebra.Module.Spaces.CompactConvergenceCLM
import Mathlib.Topology.Algebra.Module.Spaces.ContinuousLinearMap

/-!
# Kernel / fixed-point connections for semigroup generators

This file develops witness-based notions for the mixing theory of quantum
semigroups and proves the basic connection between the generator kernel and fixed
points of the exponential semigroup.

## Main definitions

* `HasFaithfulStationaryState`:
  the generator kernel contains a positive-definite density matrix.
* `HasSimpleKernel`:
  a positive-definite matrix spans the whole kernel.
* `HasSimpleFaithfulKernel`:
  the kernel is one-dimensional and generated by a faithful density matrix.
* `RelaxesTo`, `IsRelaxingQDS`:
  witness-based relaxation predicates for semigroup mixing.

## Main results

* `generator_apply_eq_zero_iff_expSemigroup_fixed_nonneg`:
  `L X = 0` iff `expSemigroup L t X = X` for all `t ≥ 0`.
* `exists_pos_forall_lt_expSemigroup_fixedPoint_iff_generator_apply_eq_zero`:
  throughout some interval of positive times, the fixed-point space of
  `expSemigroup L` is exactly the kernel of `L`.
* `exists_pos_expSemigroup_fixedPoint_iff_generator_apply_eq_zero`:
  the corresponding existence statement at one positive time.
* `generator_apply_eq_zero_iff_fixed_nonneg`:
  the same connection for any semigroup identified with `expSemigroup`.

These statements are the semigroup-side kernel/fixed-point connections needed for
Wolf Chapter 7.
-/

open scoped Matrix Matrix.Norms.Operator ComplexOrder BigOperators NNReal TNOperatorSpace
open Matrix Finset NormedSpace TNLean

noncomputable section

variable {D : ℕ}

local notation "Mat" => Matrix (Fin D) (Fin D) ℂ

/-- `L` has a faithful stationary state if its kernel contains a positive-definite
trace-one matrix. -/
def HasFaithfulStationaryState (L : Mat →ₗ[ℂ] Mat) : Prop :=
  ∃ ρ : Mat, ρ ∈ densityMatrices D ∧ ρ.PosDef ∧ L ρ = 0

/-- `ρ` spans the kernel of `L` and is positive definite. -/
structure HasSimpleKernel (L : Mat →ₗ[ℂ] Mat) (ρ : Mat) : Prop where
  /-- `ρ` lies in the kernel. -/
  kernel : L ρ = 0
  /-- `ρ` is faithful. -/
  posDef : ρ.PosDef
  /-- Every kernel element is a scalar multiple of `ρ`. -/
  unique : ∀ X : Mat, L X = 0 → ∃ c : ℂ, X = c • ρ

/-- `L` has a simple faithful kernel if some positive-definite density matrix
spans the whole kernel. -/
def HasSimpleFaithfulKernel (L : Mat →ₗ[ℂ] Mat) : Prop :=
  ∃ ρ : Mat, ρ ∈ densityMatrices D ∧ HasSimpleKernel L ρ

/-- `T` relaxes to `ρ∞` if every density matrix converges to `ρ∞` as
`t → +∞`, and `ρ∞` is faithful. -/
def RelaxesTo (T : ℝ → Mat →ₗ[ℂ] Mat) (ρInf : Mat) : Prop :=
  ρInf ∈ densityMatrices D ∧ ρInf.PosDef ∧
    ∀ ρ : Mat, ρ ∈ densityMatrices D →
      Filter.Tendsto (fun t : ℝ => T t ρ) Filter.atTop (nhds ρInf)

/-- A semigroup is relaxing if it relaxes to some faithful density matrix. -/
def IsRelaxingQDS (T : ℝ → Mat →ₗ[ℂ] Mat) : Prop :=
  ∃ ρInf : Mat, RelaxesTo (D := D) T ρInf

/-- If `L X = 0`, then `X` is fixed by the exponential semigroup at every
nonnegative time. -/
theorem expSemigroup_apply_eq_self_of_generator_apply_eq_zero
    (L : Mat →ₗ[ℂ] Mat) {X : Mat} (hX : L X = 0) :
    ∀ t : ℝ, 0 ≤ t → expSemigroup L t X = X := by
  let : AddCommGroup Mat := Matrix.linftyOpNormedAddCommGroup.toAddCommGroup
  let : NormedAddCommGroup Mat := Matrix.linftyOpNormedAddCommGroup
  let : Module ℝ Mat :=
    (TNOperatorSpace.instNormedSpaceRealMatrixComplex (Fin D)).toModule
  let : TopologicalSpace Mat := PseudoMetricSpace.toUniformSpace.toTopologicalSpace
  let : NormedSpace ℝ Mat :=
    TNOperatorSpace.instNormedSpaceRealMatrixComplex (Fin D)
  let : ContinuousSMul ℝ Mat := inferInstance
  intro t _ht
  have hdiff :
      @Differentiable ℝ _ ℝ _ _ _ Mat
        Matrix.linftyOpNormedAddCommGroup.toAddCommGroup
        (TNOperatorSpace.instNormedSpaceRealMatrixComplex (Fin D)).toModule
        PseudoMetricSpace.toUniformSpace.toTopologicalSpace
        (fun u : ℝ => expSemigroup L u X) := by
    intro u
    exact @HasDerivAt.differentiableAt ℝ _ Mat
      Matrix.linftyOpNormedAddCommGroup
      (TNOperatorSpace.instNormedSpaceRealMatrixComplex (Fin D))
      (f := fun u : ℝ => expSemigroup L u X) (f' := (expSemigroup L u) (L X)) (x := u)
      (hasDerivAt_expSemigroup_apply (L := L) X u)
  have hderiv :
      ∀ u : ℝ,
        @deriv ℝ _ Mat
          Matrix.linftyOpNormedAddCommGroup.toAddCommGroup
          (TNOperatorSpace.instNormedSpaceRealMatrixComplex (Fin D)).toModule
          PseudoMetricSpace.toUniformSpace.toTopologicalSpace
          (fun s : ℝ => expSemigroup L s X) u = 0 := by
    intro u
    have hu :
        @HasDerivAt ℝ _ Mat
          Matrix.linftyOpNormedAddCommGroup.toAddCommGroup
          (TNOperatorSpace.instNormedSpaceRealMatrixComplex (Fin D)).toModule
          PseudoMetricSpace.toUniformSpace.toTopologicalSpace
          (inferInstance : ContinuousSMul ℝ Mat)
          (fun u : ℝ => expSemigroup L u X) 0 u := by
      simpa [hX] using (hasDerivAt_expSemigroup_apply (L := L) X u)
    exact @HasDerivAt.deriv ℝ _ Mat
      Matrix.linftyOpNormedAddCommGroup
      (TNOperatorSpace.instNormedSpaceRealMatrixComplex (Fin D))
      (f := fun u : ℝ => expSemigroup L u X) (f' := 0) (x := u) hu
  have hconst := @is_const_of_deriv_eq_zero ℝ Mat _
    Matrix.linftyOpNormedAddCommGroup
    (TNOperatorSpace.instNormedSpaceRealMatrixComplex (Fin D))
    (f := fun u : ℝ => expSemigroup L u X) hdiff hderiv 0 t
  simpa [expSemigroup_zero] using hconst.symm

/-- If `X` is fixed by `exp(tL)` for every `t ≥ 0`, then `L X = 0`. -/
theorem generator_apply_eq_zero_of_expSemigroup_apply_eq_self
    (L : Mat →ₗ[ℂ] Mat) {X : Mat}
    (hX : ∀ t : ℝ, 0 ≤ t → expSemigroup L t X = X) :
    L X = 0 := by
  have hd₁ :
      @HasDerivWithinAt ℝ _ Mat
        Matrix.linftyOpNormedAddCommGroup.toAddCommGroup
        (TNOperatorSpace.instNormedSpaceRealMatrixComplex (Fin D)).toModule
        PseudoMetricSpace.toUniformSpace.toTopologicalSpace
        (inferInstance : ContinuousSMul ℝ Mat)
        (fun u : ℝ => expSemigroup L u X) (L X) (Set.Ici 0) 0 := by
    have hAt :
        @HasDerivAt ℝ _ Mat
          Matrix.linftyOpNormedAddCommGroup.toAddCommGroup
          (TNOperatorSpace.instNormedSpaceRealMatrixComplex (Fin D)).toModule
          PseudoMetricSpace.toUniformSpace.toTopologicalSpace
          (inferInstance : ContinuousSMul ℝ Mat)
          (fun u : ℝ => expSemigroup L u X) (L X) 0 := by
      simpa [expSemigroup_zero] using hasDerivAt_expSemigroup_apply (L := L) X 0
    exact @HasDerivAt.hasDerivWithinAt ℝ _ Mat
      Matrix.linftyOpNormedAddCommGroup
      (TNOperatorSpace.instNormedSpaceRealMatrixComplex (Fin D))
      (f := fun u : ℝ => expSemigroup L u X) (f' := L X) (x := 0) (s := Set.Ici 0)
      hAt
  have hd₂' :
      @HasDerivWithinAt ℝ _ Mat
        Matrix.linftyOpNormedAddCommGroup.toAddCommGroup
        (TNOperatorSpace.instNormedSpaceRealMatrixComplex (Fin D)).toModule
        PseudoMetricSpace.toUniformSpace.toTopologicalSpace
        (inferInstance : ContinuousSMul ℝ Mat)
        (fun _ : ℝ => X) 0 (Set.Ici 0) 0 := by
    exact @HasDerivAt.hasDerivWithinAt ℝ _ Mat
      Matrix.linftyOpNormedAddCommGroup
      (TNOperatorSpace.instNormedSpaceRealMatrixComplex (Fin D))
      (f := fun _ : ℝ => X) (f' := 0) (x := 0) (s := Set.Ici 0)
      (hasDerivAt_const (x := 0) (c := X))
  have hd₂ :
      @HasDerivWithinAt ℝ _ Mat
        Matrix.linftyOpNormedAddCommGroup.toAddCommGroup
        (TNOperatorSpace.instNormedSpaceRealMatrixComplex (Fin D)).toModule
        PseudoMetricSpace.toUniformSpace.toTopologicalSpace
        (inferInstance : ContinuousSMul ℝ Mat)
        (fun u : ℝ => expSemigroup L u X) 0 (Set.Ici 0) 0 :=
    hd₂'.congr (fun u hu => hX u hu) (by simp [expSemigroup_zero])
  exact (uniqueDiffWithinAt_Ici 0).eq_deriv _ hd₁ hd₂

/-- Kernel elements of `L` are exactly the matrices fixed by `exp(tL)` for every
nonnegative time. -/
theorem generator_apply_eq_zero_iff_expSemigroup_fixed_nonneg
    (L : Mat →ₗ[ℂ] Mat) (X : Mat) :
    L X = 0 ↔ ∀ t : ℝ, 0 ≤ t → expSemigroup L t X = X := by
  constructor
  · exact expSemigroup_apply_eq_self_of_generator_apply_eq_zero L
  · exact generator_apply_eq_zero_of_expSemigroup_apply_eq_self L

/-- If the integral factor in
`exp(tL) - 1 = (∫ s in 0..t, exp(sL)) L` is invertible, then the fixed-point
space of `exp(tL)` is exactly `ker L`. -/
theorem expSemigroup_fixedPoint_iff_generator_apply_eq_zero_of_intervalIntegral_isUnit
    (L : Mat →ₗ[ℂ] Mat) (t : ℝ) (ht : 0 ≤ t)
    (hP_unit : IsUnit
      (intervalIntegral (fun s : ℝ => expSemigroupCLM (endEquiv L) s)
        0 t MeasureTheory.volume))
    (X : Mat) :
    expSemigroup L t X = X ↔ L X = 0 := by
  let L' : MatrixCLM (Fin D) := endEquiv L
  let P : MatrixCLM (Fin D) :=
    intervalIntegral (fun s : ℝ => expSemigroupCLM L' s)
      0 t MeasureTheory.volume
  have hP_unit' : IsUnit P := by
    simpa [P, L'] using hP_unit
  have hP_injective : Function.Injective P :=
    (ContinuousLinearMap.isUnit_iff_bijective.mp hP_unit').1
  constructor
  · intro hX
    have hX' : expSemigroupCLM L' t X = X := by
      change endEquiv (expSemigroup L t) X = X
      rw [expSemigroup_toCLM]
      exact hX
    have hzero : (expSemigroupCLM L' t - 1) X = 0 := by
      simpa using sub_eq_zero.mpr hX'
    rw [expSemigroupCLM_sub_one_eq_intervalIntegral_mul] at hzero
    have hPLX : P (L' X) = 0 := by
      simpa [P] using hzero
    have hLX' : L' X = 0 := by
      apply hP_injective
      simpa using hPLX
    exact hLX'
  · intro hLX
    exact expSemigroup_apply_eq_self_of_generator_apply_eq_zero L hLX t ht

/-- For every finite-dimensional generator `L`, there is a `δ > 0` such
that the fixed-point space of `exp(tL)` is exactly `ker L` whenever
`0 < t < δ`.

The factorization
`exp(tL) - 1 = (∫ s in 0..t, exp(sL)) L`
shows that a fixed point lies in `ker L` whenever the integral factor is
invertible.  The normalized integral tends to the identity as `t ↓ 0`, so
this invertibility holds throughout a punctured right-neighborhood of zero.
This is the nonresonant-time step used in Wolf Proposition 7.5. -/
theorem exists_pos_forall_lt_expSemigroup_fixedPoint_iff_generator_apply_eq_zero
    (L : Mat →ₗ[ℂ] Mat) :
    ∃ δ : ℝ, 0 < δ ∧ ∀ t : ℝ, 0 < t → t < δ →
      ∀ X : Mat, expSemigroup L t X = X ↔ L X = 0 := by
  let L' : MatrixCLM (Fin D) := endEquiv L
  obtain ⟨δ, hδ, hP_unit⟩ :=
    exists_pos_forall_lt_intervalIntegral_isUnit_of_continuous_zero_eq_one
      (fun t : ℝ => expSemigroupCLM L' t)
      (expSemigroupCLM_zero L') (expSemigroupCLM_continuous L')
  refine ⟨δ, hδ, fun t ht htδ X => ?_⟩
  exact expSemigroup_fixedPoint_iff_generator_apply_eq_zero_of_intervalIntegral_isUnit
    L t ht.le (by simpa [L'] using hP_unit t ht htδ) X

/-- For every finite-dimensional generator `L`, there is a positive time `t₀`
at which the fixed-point space of `exp(t₀L)` is exactly `ker L`. -/
theorem exists_pos_expSemigroup_fixedPoint_iff_generator_apply_eq_zero
    (L : Mat →ₗ[ℂ] Mat) :
    ∃ t₀ : ℝ, 0 < t₀ ∧
      ∀ X : Mat, expSemigroup L t₀ X = X ↔ L X = 0 := by
  obtain ⟨δ, hδ, hfix⟩ :=
    exists_pos_forall_lt_expSemigroup_fixedPoint_iff_generator_apply_eq_zero L
  exact ⟨δ / 2, by positivity, hfix (δ / 2) (by positivity) (by linarith)⟩

/-- Kernel elements of `L` are exactly the matrices fixed by a semigroup family
`T` identified with `expSemigroup L` on nonnegative times. -/
theorem generator_apply_eq_zero_iff_fixed_nonneg
    (L : Mat →ₗ[ℂ] Mat)
    (T : ℝ → Mat →ₗ[ℂ] Mat)
    (hexp : ∀ t : ℝ, 0 ≤ t → T t = expSemigroup L t)
    (X : Mat) :
    L X = 0 ↔ ∀ t : ℝ, 0 ≤ t → T t X = X := by
  constructor
  · intro hX t ht
    rw [hexp t ht]
    exact (generator_apply_eq_zero_iff_expSemigroup_fixed_nonneg (L := L) X).1 hX t ht
  · intro hX
    exact (generator_apply_eq_zero_iff_expSemigroup_fixed_nonneg (L := L) X).2 <|
      fun t ht => by
        rw [← hexp t ht]
        exact hX t ht
