/-
Copyright (c) 2026 QICLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: QICLean contributors
-/
import QICLean.Algebra.MatrixFamilyAction
import QICLean.Kraus.Wielandt.SpanGrowth.CumulativeSpan
import Mathlib.RingTheory.Noetherian.Defs

/-!
# Algebra span and cumulative word-span growth

This file relates the unital algebra generated by a finite family of complex square matrices to
the cumulative spans of its words. Every element of the generated algebra appears at some finite
word length, so if the generated algebra is the full matrix algebra, a cumulative span eventually
reaches the full matrix space.
-/

open scoped Matrix

namespace Kraus

variable {d D : ℕ}

/-- Every word evaluation lies in the algebra span. -/
theorem evalWord_mem_algSpan (K : Fin d → Matrix (Fin D) (Fin D) ℂ) (w : List (Fin d)) :
    Kraus.evalWord K w ∈ Matrix.algSpan K := by
  induction w with
  | nil => exact (Matrix.algSpan K).one_mem
  | cons i w ih => exact (Matrix.algSpan K).mul_mem (Matrix.algSpan_mem K i) ih

/-- The word span at any length is contained in the algebra span (as submodules). -/
theorem wordSpan_le_algSpan_toSubmodule (K : Fin d → Matrix (Fin D) (Fin D) ℂ) (n : ℕ) :
    Kraus.wordSpan K n ≤ (Matrix.algSpan K).toSubmodule := by
  apply Submodule.span_le.mpr
  rintro M ⟨σ, rfl⟩
  exact evalWord_mem_algSpan K (List.ofFn σ)

/-- The cumulative span is contained in the algebra span. -/
theorem cumulativeSpan_le_algSpan_toSubmodule (K : Fin d → Matrix (Fin D) (Fin D) ℂ) (n : ℕ) :
    Kraus.cumulativeSpan K n ≤ (Matrix.algSpan K).toSubmodule := by
  apply Submodule.span_le.mpr
  rintro M ⟨w, _, rfl⟩
  exact evalWord_mem_algSpan K w

/-! ### Multiplication closure for cumulative span -/

/-- Product of generators lands in the right cumulative span. -/
theorem evalWord_mul_evalWord_mem_cumulativeSpan
    (K : Fin d → Matrix (Fin D) (Fin D) ℂ)
    {w₁ w₂ : List (Fin d)} {m n : ℕ}
    (hw₁ : w₁.length ≤ m) (hw₂ : w₂.length ≤ n) :
    Kraus.evalWord K w₁ * Kraus.evalWord K w₂ ∈ Kraus.cumulativeSpan K (m + n) := by
  rw [← Kraus.evalWord_append]
  apply Kraus.mem_cumulativeSpan_generator
  rw [List.length_append]
  omega

/-- The cumulative span is closed under multiplication (adding lengths). -/
theorem mul_mem_cumulativeSpan_add (K : Fin d → Matrix (Fin D) (Fin D) ℂ) {m n : ℕ}
    {x y : Matrix (Fin D) (Fin D) ℂ}
    (hx : x ∈ Kraus.cumulativeSpan K m) (hy : y ∈ Kraus.cumulativeSpan K n) :
    x * y ∈ Kraus.cumulativeSpan K (m + n) := by
  -- Matrix multiplication is bilinear, so generator closure extends to both spans.
  apply LinearMap.BilinMap.apply_apply_mem_of_mem_span
    (P' := Kraus.cumulativeSpan K (m + n))
    (s := {M | ∃ w : List (Fin d), w.length ≤ m ∧ M = Kraus.evalWord K w})
    (t := {M | ∃ w : List (Fin d), w.length ≤ n ∧ M = Kraus.evalWord K w})
    (B := LinearMap.mul ℂ (Matrix (Fin D) (Fin D) ℂ))
  · intro x hx y hy
    rcases hx with ⟨w₁, hw₁, rfl⟩
    rcases hy with ⟨w₂, hw₂, rfl⟩
    exact evalWord_mul_evalWord_mem_cumulativeSpan K hw₁ hw₂
  · exact hx
  · exact hy

/-- Every element of the algebra span lies in some cumulative span.

Proven via `Algebra.adjoin_induction`. -/
theorem mem_cumulativeSpan_of_mem_algSpan (K : Fin d → Matrix (Fin D) (Fin D) ℂ)
    {x : Matrix (Fin D) (Fin D) ℂ} (hx : x ∈ Matrix.algSpan K) :
    ∃ N : ℕ, x ∈ Kraus.cumulativeSpan K N := by
  induction hx using Algebra.adjoin_induction with
  | mem x hxS =>
    rcases hxS with ⟨i, rfl⟩
    refine ⟨1, ?_⟩
    simpa only [Kraus.evalWord, Matrix.mul_one] using
      (Kraus.mem_cumulativeSpan_generator K (n := 1) (w := [i]) (by simp))
  | algebraMap r =>
    refine ⟨0, ?_⟩
    rw [Algebra.algebraMap_eq_smul_one]
    exact (Kraus.cumulativeSpan K 0).smul_mem r (Kraus.one_mem_cumulativeSpan K 0)
  | add x y _ _ ihx ihy =>
    rcases ihx with ⟨Nx, hNx⟩
    rcases ihy with ⟨Ny, hNy⟩
    refine ⟨max Nx Ny, ?_⟩
    exact (Kraus.cumulativeSpan K (max Nx Ny)).add_mem
      ((Kraus.cumulativeSpan_mono' K (le_max_left Nx Ny)) hNx)
      ((Kraus.cumulativeSpan_mono' K (le_max_right Nx Ny)) hNy)
  | mul x y _ _ ihx ihy =>
    rcases ihx with ⟨Nx, hNx⟩
    rcases ihy with ⟨Ny, hNy⟩
    exact ⟨Nx + Ny, mul_mem_cumulativeSpan_add K hNx hNy⟩

/-- **From algebra span to cumulative span**: if the algebra generated by `{K i}`
is all of `M_D(ℂ)`, then the cumulative span reaches ⊤ at some finite level.

Uses the Noetherian property of finite-dimensional modules. -/
lemma exists_cumulativeSpan_eq_top_of_algSpan_eq_top (K : Fin d → Matrix (Fin D) (Fin D) ℂ)
    (h : Matrix.algSpan K = ⊤) :
    ∃ N : ℕ, Kraus.cumulativeSpan K N = ⊤ := by
  -- Every matrix is in the algebra span, hence in some cumulative span.
  have hx : ∀ x : Matrix (Fin D) (Fin D) ℂ, ∃ N, x ∈ Kraus.cumulativeSpan K N :=
    fun x => mem_cumulativeSpan_of_mem_algSpan K (by
      rw [h]
      exact Algebra.mem_top)
  -- The module is Noetherian (finite-dimensional over a field)
  have : IsNoetherian ℂ (Matrix (Fin D) (Fin D) ℂ) :=
    isNoetherian_of_isNoetherianRing_of_finite ℂ _
  -- Construct the monotone chain as an order homomorphism
  let f : ℕ →o Submodule ℂ (Matrix (Fin D) (Fin D) ℂ) :=
    ⟨Kraus.cumulativeSpan K, fun _ _ h => Kraus.cumulativeSpan_mono' K h⟩
  -- Noetherian ⟹ the ascending chain stabilizes
  obtain ⟨N₀, hstab⟩ := (monotone_stabilizes_iff_noetherian.mpr ‹_›) f
  -- Show the stable value is ⊤.
  refine ⟨N₀, eq_top_iff.mpr ?_⟩
  intro x _
  rcases hx x with ⟨M, hM⟩
  rcases le_total M N₀ with hMN | hNM
  · exact (Kraus.cumulativeSpan_mono' K hMN) hM
  · have heq : Kraus.cumulativeSpan K M = Kraus.cumulativeSpan K N₀ := (hstab M hNM).symm
    simpa [heq] using hM

end Kraus
