/-
Copyright (c) 2026 QICLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: QICLean contributors
-/
-- This file is generated by scripts/generate_import_aggregators.py.
-- Do not edit it directly; run the generator instead.
-- Import architecture: docs/import_structure.md.
-- Generated aggregator module: QICLean.Channel.Irreducible

import QICLean.Channel.Irreducible.AdjointFamily
import QICLean.Channel.Irreducible.Basic
import QICLean.Channel.Irreducible.CollatzWielandt
import QICLean.Channel.Irreducible.Ergodicity
import QICLean.Channel.Irreducible.FixedPoint
import QICLean.Channel.Irreducible.FixedPointUniqueness
import QICLean.Channel.Irreducible.FromSpectral
import QICLean.Channel.Irreducible.Growth
import QICLean.Channel.Irreducible.Growth.Exponential
import QICLean.Channel.Irreducible.Growth.KernelDescent
import QICLean.Channel.Irreducible.Growth.OneStep
import QICLean.Channel.Irreducible.Growth.OrthogonalTrace
import QICLean.Channel.Irreducible.Growth.Preservation
import QICLean.Channel.Irreducible.KrausSetup
import QICLean.Channel.Irreducible.PerronFrobenius
import QICLean.Channel.Irreducible.Scaling
import QICLean.Channel.Irreducible.Similarity
import QICLean.Channel.Irreducible.SpectralRadius
