/-
Copyright (c) 2026 QICLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: QICLean contributors
-/
-- This file is generated by scripts/generate_import_aggregators.py.
-- Do not edit it directly; run the generator instead.
-- Import architecture: docs/import_structure.md.
-- Generated aggregator module: QICLean.Channel.Peripheral

import QICLean.Channel.Peripheral.AdjointSpectrum
import QICLean.Channel.Peripheral.AntilinearConjugation
import QICLean.Channel.Peripheral.AsymptoticImage
import QICLean.Channel.Peripheral.CesaroRecurrence
import QICLean.Channel.Peripheral.ClosureFixedPointKraus
import QICLean.Channel.Peripheral.Conjugation
import QICLean.Channel.Peripheral.Cycles
import QICLean.Channel.Peripheral.CyclicDecomposition
import QICLean.Channel.Peripheral.CyclicDecomposition.Basic
import QICLean.Channel.Peripheral.CyclicDecomposition.CyclicProjections
import QICLean.Channel.Peripheral.CyclicDecomposition.Decomposition
import QICLean.Channel.Peripheral.CyclicDecomposition.LetterShift
import QICLean.Channel.Peripheral.CyclicDecomposition.PeripheralUnitary
import QICLean.Channel.Peripheral.CyclicDecomposition.Primitivity
import QICLean.Channel.Peripheral.CyclicGroupKraus
import QICLean.Channel.Peripheral.DensityBlockCoordinates
import QICLean.Channel.Peripheral.DensityBlockDynamics
import QICLean.Channel.Peripheral.DensityBlockFacePermutation
import QICLean.Channel.Peripheral.DensityBlockSchwarz
import QICLean.Channel.Peripheral.DirectSumFacePermutation
import QICLean.Channel.Peripheral.GroupStructure
import QICLean.Channel.Peripheral.IrreducibleChannel
import QICLean.Channel.Peripheral.JordanBlocks
import QICLean.Channel.Peripheral.MatchedBlockEndomorphism
import QICLean.Channel.Peripheral.MultiCycleDecomposition
import QICLean.Channel.Peripheral.PeriodicityRemoval
import QICLean.Channel.Peripheral.Powers
import QICLean.Channel.Peripheral.PureStateFace
import QICLean.Channel.Peripheral.RecurrentInverse
import QICLean.Channel.Peripheral.SchurAsymptoticConvergence
import QICLean.Channel.Peripheral.SpectralProjection
import QICLean.Channel.Peripheral.SpectralRadius
import QICLean.Channel.Peripheral.Spectrum
import QICLean.Channel.Peripheral.StructureOfCycles
import QICLean.Channel.Peripheral.TransferMatrix
import QICLean.Channel.Peripheral.UnitalKraus
import QICLean.Channel.Peripheral.WeightedCesaro
