import QICLean.Entropy.ConditionalTwoFamilies
set_option linter.hashCommand false
#print axioms
  FiniteProduct.conditionalMutualInformation_union_left
#print axioms
  FiniteProduct.mutualInformation_le_two_entropy
#print axioms
  FiniteProduct.conditionalMutualInformation_le_two_entropy
#print axioms
  FiniteProduct.conditionalMutualInformation_biUnion_le_sum
#print axioms
  FiniteProduct.target_union_complement_eq_exterior
#print axioms
  FiniteProduct.conditionalMutualInformation_le_two_family_mutualInformation
#print axioms
  FiniteProduct.conditionalMutualInformation_le_two_family_sum
