/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import QICLean.Representation.SchurWeylCommutant

/-!
# Highest weights in tensor powers

On `(ℂ^q)^{⊗k}`, with basis indexed by configurations `x : Fin k → Fin q`, the diagonal
action of the matrix units, `E_{ab} = Δ(e_{ab})`, is the action of the general linear Lie
algebra `gl_q`. A configuration `x` has weight `wt(x)_a = #{j | x_j = a}`; the operator
`E_{ab}` moves weight `μ` to `μ + e_a - e_b`. A highest-weight vector is a nonzero weight
vector annihilated by the raising operators `E_{ab}`, `a < b`.

This file develops the highest-weight theory needed for the Schur–Weyl identification of
the labels in the area-law paper (*A two-dimensional area law from a global spectral
gap*, `05-replicas.tex`, lines 46–64, and the star-operator computation in the proof of
Lemma 6.1, lines 250–263) for subspaces invariant under the commutant of the copy
permutations, which by `TensorPower.commutant_le_diagAlgebra` is the algebra generated by
the operators `E_{ab}`:

* a nonzero invariant subspace contains a highest-weight vector (of lexicographically
  maximal weight);
* in an irreducible invariant subspace the highest-weight vector is unique up to scalars,
  every weight is lexicographically at most its weight, and that weight is a partition.

## Main declarations

* `TensorPower.weight`, `TensorPower.gen`, `TensorPower.IsWeightVector`,
  `TensorPower.IsHighestWeight`.
* `TensorPower.IsInvariant`, `TensorPower.IsIrreducible` — invariance and irreducibility
  under the commutant of the copy permutations.
* `TensorPower.exists_isHighestWeight` — existence.
* `TensorPower.IsIrreducible.mem_span_of_isWeightVector`,
  `TensorPower.IsIrreducible.weight_eq_of_isHighestWeight` — uniqueness.
* `TensorPower.IsIrreducible.antitone_of_isHighestWeight` — the highest weight is a
  partition.
-/

open Finset Matrix PermutationRepresentation

namespace PermutationRepresentation

variable {G X : Type*} [Group G] [Fintype X] [DecidableEq X] (φ : G →* Equiv.Perm X)

/-- A matrix invariant under the diagonal action commutes with the permutation operators. -/
theorem mem_commutant_of_apply_eq {M : Matrix X X ℂ}
    (hM : ∀ g x y, M (φ g x) (φ g y) = M x y) : M ∈ commutant φ := by
  intro g
  ext x y
  simp only [mul_apply, permOp_apply_apply]
  have e1 : (φ g) ((φ g)⁻¹ x) = x := by
    rw [← Equiv.Perm.mul_apply, mul_inv_cancel, Equiv.Perm.one_apply]
  have e2 : ∀ z, (φ g)⁻¹ ((φ g) z) = z := fun z => by
    rw [← Equiv.Perm.mul_apply, inv_mul_cancel, Equiv.Perm.one_apply]
  rw [Finset.sum_eq_single ((φ g)⁻¹ x), Finset.sum_eq_single (φ g y)]
  · rw [e1, ← hM g ((φ g)⁻¹ x) y, e1]
    simp
  · intro z _ hz; simp [Ne.symm hz]
  · simp
  · intro z _ hz
    have : φ g z ≠ x := fun h => hz (by rw [← h, e2])
    simp [this]
  · simp

end PermutationRepresentation

namespace TensorPower

variable {q k : ℕ}

/-- The weight `wt(x)_a = #{j | x_j = a}` of a configuration. -/
def weight (x : Fin k → Fin q) (a : Fin q) : ℤ := ∑ j, if x j = a then 1 else 0

theorem weight_update (x : Fin k → Fin q) (j : Fin k) (b : Fin q) :
    weight (Function.update x j b) = weight x - Pi.single (x j) 1 + Pi.single b 1 := by
  funext c
  simp only [weight, Pi.add_apply, Pi.sub_apply, Pi.single_apply]
  rw [Fintype.sum_eq_add_sum_compl j,
    Fintype.sum_eq_add_sum_compl j (fun i => if x i = c then (1 : ℤ) else 0)]
  have h : ∑ i ∈ {j}ᶜ, (if Function.update x j b i = c then (1 : ℤ) else 0) =
      ∑ i ∈ {j}ᶜ, if x i = c then 1 else 0 :=
    sum_congr rfl fun i hi => by rw [Function.update_of_ne (by simpa using hi)]
  rw [h, Function.update_self]
  simp only [show (c = x j) ↔ (x j = c) from eq_comm, show (c = b) ↔ (b = c) from eq_comm]
  by_cases h1 : b = c <;> by_cases h2 : x j = c <;> simp only [h1, h2, ite_true, ite_false] <;>
    ring

section Operators

variable {Ω : Type*} [Fintype Ω] [DecidableEq Ω]

theorem siteOp_mulVec_apply (j : Fin k) (A : Matrix Ω Ω ℂ) (u : (Fin k → Ω) → ℂ)
    (x : Fin k → Ω) : (siteOp j A *ᵥ u) x = ∑ c, A (x j) c * u (Function.update x j c) := by
  rw [mulVec, dotProduct]
  have hsupp : ∀ y ∈ (univ : Finset (Fin k → Ω)), y ∉ univ.image (Function.update x j) →
      siteOp j A x y * u y = 0 := by
    intro y _ hy
    rw [siteOp_apply, ite_eq_right, zero_mul]
    intro h
    apply hy
    refine mem_image.mpr ⟨y j, mem_univ _, ?_⟩
    funext i
    by_cases hij : i = j
    · subst hij; simp
    · simp [hij, h i hij]
  rw [← sum_subset (subset_univ _) hsupp,
    sum_image (fun a _ b _ h => by simpa using congrFun h j)]
  refine sum_congr rfl fun c _ => ?_
  rw [siteOp_apply, ite_eq_left (fun i hi => by simp [hi]), Function.update_self]

theorem siteOp_add (j : Fin k) (A B : Matrix Ω Ω ℂ) :
    siteOp j (A + B) = siteOp j A + siteOp j B := by
  ext x y; simp only [siteOp_apply, Matrix.add_apply]; split_ifs <;> simp

theorem siteOp_smul (j : Fin k) (c : ℂ) (A : Matrix Ω Ω ℂ) :
    siteOp j (c • A) = c • siteOp j A := by
  ext x y; simp only [siteOp_apply, Matrix.smul_apply]; split_ifs <;> simp

theorem siteOp_sub (j : Fin k) (A B : Matrix Ω Ω ℂ) :
    siteOp j (A - B) = siteOp j A - siteOp j B := by
  ext x y; simp only [siteOp_apply, Matrix.sub_apply]; split_ifs <;> simp

@[simp]
theorem siteOp_zero (j : Fin k) : siteOp j (0 : Matrix Ω Ω ℂ) = 0 := by
  ext x y; simp [siteOp_apply]

theorem diagOp_sub (A B : Matrix Ω Ω ℂ) :
    diagOp (k := k) (A - B) = diagOp A - diagOp B := by
  simp [diagOp, siteOp_sub, sum_sub_distrib]

@[simp]
theorem diagOp_zero : diagOp (k := k) (0 : Matrix Ω Ω ℂ) = 0 := by
  simp [diagOp]

/-- The diagonal action is a Lie algebra homomorphism. -/
theorem diagOp_mul_sub_mul (A B : Matrix Ω Ω ℂ) :
    diagOp (k := k) A * diagOp B - diagOp B * diagOp A = diagOp (A * B - B * A) := by
  have h1 : diagOp (k := k) A * diagOp B = ∑ i, ∑ j, siteOp i A * siteOp j B := by
    rw [diagOp, diagOp, sum_mul_sum]
  have h2 : diagOp (k := k) B * diagOp A = ∑ i, ∑ j, siteOp j B * siteOp i A := by
    rw [diagOp, diagOp, sum_mul_sum, sum_comm]
  rw [h1, h2, ← sum_sub_distrib, diagOp]
  refine sum_congr rfl fun i _ => ?_
  rw [← sum_sub_distrib, sum_eq_single i]
  · rw [siteOp_mul_siteOp, siteOp_mul_siteOp, siteOp_sub]
  · intro j _ hj
    have hc : Commute (siteOp i A) (siteOp j B) :=
      commute_partialTensor (disjoint_singleton.mpr (Ne.symm hj)) _ _
    rw [hc.eq, sub_self]
  · simp

theorem diagOp_mem_commutant (A : Matrix Ω Ω ℂ) :
    diagOp (k := k) A ∈ commutant (copyPerm Ω k) := by
  refine mem_commutant_of_apply_eq _ fun σ x y => ?_
  simp only [diagOp, Matrix.sum_apply, siteOp_apply, copyPerm_apply]
  refine Fintype.sum_equiv σ.symm _ _ fun j => ?_
  have h : (∀ i, i ≠ j → x (σ⁻¹ i) = y (σ⁻¹ i)) ↔ (∀ i, i ≠ σ.symm j → x i = y i) := by
    constructor
    · intro h i hi
      simpa using h (σ i) (fun e => hi (by rw [← e]; simp))
    · intro h i hi
      exact h _ (fun e => hi (by simpa using congrArg σ e))
  simp only [h]
  rfl

theorem diagAlgebra_le_commutant :
    Subalgebra.toSubmodule (diagAlgebra Ω k) ≤ commutant (copyPerm Ω k) := by
  intro M hM
  induction hM using Algebra.adjoin_induction with
  | mem x hx => obtain ⟨A, rfl⟩ := hx; exact diagOp_mem_commutant A
  | algebraMap r => exact fun g => (Algebra.commutes r _).symm
  | add x y _ _ hx hy => exact Submodule.add_mem _ hx hy
  | mul x y _ _ hx hy => exact fun g => (hx g).mul_right (hy g)

/-- **Schur–Weyl duality**: the commutant of the copy permutations is the algebra
generated by the diagonal action. -/
theorem commutant_eq_diagAlgebra :
    commutant (copyPerm Ω k) = Subalgebra.toSubmodule (diagAlgebra Ω k) :=
  le_antisymm commutant_le_diagAlgebra diagAlgebra_le_commutant

end Operators

/-- The operator `E_{ab} = Δ(e_{ab})` of the diagonal `gl_q` action. -/
def gen (a b : Fin q) : Matrix (Fin k → Fin q) (Fin k → Fin q) ℂ :=
  diagOp (Matrix.single a b 1)

theorem gen_mulVec_apply (a b : Fin q) (u : (Fin k → Fin q) → ℂ) (x : Fin k → Fin q) :
    (gen a b *ᵥ u) x = ∑ j, if x j = a then u (Function.update x j b) else 0 := by
  simp only [gen, diagOp, sum_mulVec, Finset.sum_apply, siteOp_mulVec_apply, single_apply]
  refine sum_congr rfl fun j _ => ?_
  rw [sum_eq_single b]
  · by_cases h : x j = a
    · simp [h]
    · have h' : ¬a = x j := fun e => h e.symm
      simp [h, h']
  · intro c _ hc; simp [Ne.symm hc]
  · simp

theorem gen_mem_commutant (a b : Fin q) : gen (k := k) a b ∈ commutant (copyPerm (Fin q) k) :=
  diagOp_mem_commutant _

theorem gen_mul_sub_mul (a b c d : Fin q) :
    gen (k := k) a b * gen c d - gen c d * gen a b =
      (if b = c then gen a d else 0) - (if d = a then gen c b else 0) := by
  rw [gen, gen, diagOp_mul_sub_mul]
  have : Matrix.single a b (1 : ℂ) * Matrix.single c d 1 - Matrix.single c d 1 * Matrix.single a b 1
      = (if b = c then Matrix.single a d 1 else 0) - (if d = a then Matrix.single c b 1 else 0) := by
    by_cases h1 : b = c <;> by_cases h2 : d = a
    · subst h1 h2; simp [single_mul_single_same]
    · subst h1; simp [h2]
    · subst h2; simp [h1]
    · simp [h1, h2]
  rw [this, diagOp_sub]
  split_ifs <;> simp [gen]

/-- A weight vector of weight `μ`: supported on configurations of weight `μ`. -/
def IsWeightVector (μ : Fin q → ℤ) (u : (Fin k → Fin q) → ℂ) : Prop :=
  ∀ x, u x ≠ 0 → weight x = μ

theorem isWeightVector_zero (μ : Fin q → ℤ) : IsWeightVector μ (0 : (Fin k → Fin q) → ℂ) :=
  fun _ h => absurd rfl h

theorem IsWeightVector.add {μ : Fin q → ℤ} {u v : (Fin k → Fin q) → ℂ}
    (hu : IsWeightVector μ u) (hv : IsWeightVector μ v) : IsWeightVector μ (u + v) := by
  intro x hx
  by_cases h : u x = 0
  · exact hv x (by simpa [h] using hx)
  · exact hu x h

theorem IsWeightVector.smul {μ : Fin q → ℤ} {u : (Fin k → Fin q) → ℂ}
    (hu : IsWeightVector μ u) (c : ℂ) : IsWeightVector μ (c • u) :=
  fun x hx => hu x (fun h => hx (by simp [h]))

theorem IsWeightVector.gen_mulVec {μ : Fin q → ℤ} {u : (Fin k → Fin q) → ℂ}
    (hu : IsWeightVector μ u) (a b : Fin q) :
    IsWeightVector (μ + Pi.single a 1 - Pi.single b 1) (gen a b *ᵥ u) := by
  intro x hx
  rw [gen_mulVec_apply] at hx
  obtain ⟨j, _, hj⟩ := exists_ne_zero_of_sum_ne_zero hx
  have hxj : x j = a := by by_contra h; simp [h] at hj
  simp only [hxj, ↓reduceIte] at hj
  have h := hu _ hj
  rw [weight_update, hxj] at h
  rw [← h]
  abel

theorem IsWeightVector.gen_self_mulVec {μ : Fin q → ℤ} {u : (Fin k → Fin q) → ℂ}
    (hu : IsWeightVector μ u) (a : Fin q) : gen a a *ᵥ u = (μ a : ℂ) • u := by
  funext x
  rw [gen_mulVec_apply, Pi.smul_apply, smul_eq_mul]
  have : ∀ j, (if x j = a then u (Function.update x j a) else 0) =
      ((if x j = a then (1 : ℤ) else 0 : ℤ) : ℂ) * u x := by
    intro j
    by_cases h : x j = a
    · simp only [h, ↓reduceIte, Int.cast_one, one_mul]
      rw [Function.update_eq_self_iff.mpr h.symm]
    · simp [h]
  simp_rw [this]
  rw [← sum_mul, ← Int.cast_sum]
  by_cases hx : u x = 0
  · simp [hx]
  · rw [show (∑ j, if x j = a then (1 : ℤ) else 0) = weight x a from rfl, hu x hx]

/-- A lowering step strictly decreases the weight lexicographically. -/
theorem toLex_add_single_sub_single_lt {a b : Fin q} (h : b < a) (μ : Fin q → ℤ) :
    toLex (μ + Pi.single a 1 - Pi.single b 1) < toLex μ :=
  ⟨b, fun j hj => by simp [hj.ne, (hj.trans h).ne],
    by simp [h.ne]⟩

end TensorPower
