/-
Copyright (c) 2026 QICLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: QICLean contributors
-/
import QICLean.Representation.ReplicaMarkedRatio
import QICLean.Representation.MergeMoment

/-!
# Inverse estimates for the marked ratio on symmetric vectors

Let `k = m + 1` and `0 < t < 1/2`. The area-law paper (*A two-dimensional area law from a
global spectral gap*, `05-replicas.tex`, Lemma 6.2, lines 324–335 and 418–430) bounds the
inverse marked ratio only on symmetric vectors: `‖R_{Q,k}^{-1} z‖ ≤ C` for unit `z ∈ 𝒮_k`, and

`limsup_k sup_z ‖(R_{Q,k}^{-1} - max(J_{Q,k}, δ)^{-t}) z‖ ≤ C δ^{(1-2t)/2}`.

The proof (lines 418–430) uses that the `Q` marginal of a symmetric vector is permutation
invariant, so that the branch `ν = λ - e_i` carries the fraction `d_ν/d_λ ≤ 2^d l_i/k` of the
weight of the label `λ`. In matrix form, the marginal is replaced by the average of `|z⟩⟨z|`
over the copy permutations of `Qᶜ`, which commutes with the copy permutations of `Q` and has
the same pairing as `|z⟩⟨z|` with every operator generated by them.

The proofs are written from the paper; no Lean source was adapted.

## Main declarations

* `TensorPower.complAverage`, `TensorPower.commute_complAverage`,
  `TensorPower.trace_complAverage_mul`.
* `TensorPower.weight_branch` — the branch weight `d_ν/d_λ` of a symmetric vector.
* `TensorPower.markedRatio_inv_eq_hom`.
* `TensorPower.exists_norm_markedRatio_inv_mulVec_le` — `‖R_{Q,k}^{-1} z‖ ≤ C ‖z‖`.
* `TensorPower.exists_norm_markedRatio_inv_sub_clipped_le` — the clipped inverse estimate
  `replicas:R-inverse`.
-/

open Matrix PermutationRepresentation Filter Topology

namespace TensorPower

variable {F : Type*} [DecidableEq F] [Fintype F] (ι : F → Type*) [∀ f, Fintype (ι f)]
  [∀ f, DecidableEq (ι f)]

/-! ### The complement average of a symmetric vector -/

/-- Permutation operators of pointwise-commuting actions commute. -/
theorem commute_permOp_subsystemPerm_of_disjoint {k : ℕ} {Q Q' : Finset F} (h : Disjoint Q Q')
    (σ τ : Equiv.Perm (Fin k)) :
    Commute (permOp (subsystemPerm k ι Q) σ) (permOp (subsystemPerm k ι Q') τ) := by
  simpa using commute_groupAlgebraRep_subsystemPerm_of_disjoint ι k h
    (MonoidAlgebra.single σ 1) (MonoidAlgebra.single τ 1)

/-- The average `∑_π U_{Qᶜ}(π) |z⟩⟨z| U_{Qᶜ}(π)^{-1}` over the copy permutations of the
complement. -/
noncomputable def complAverage (k : ℕ) (Q : Finset F) (z : Config k ι → ℂ) :
    Matrix (Config k ι) (Config k ι) ℂ :=
  ∑ π : Equiv.Perm (Fin k),
    permOp (subsystemPerm k ι Qᶜ) π * vecMulVec z (star z) * permOp (subsystemPerm k ι Qᶜ) π⁻¹

/-- The complement average pairs with every operator commuting with the copy permutations of
`Qᶜ` as `k!` times `|z⟩⟨z|`. -/
theorem trace_complAverage_mul (k : ℕ) (Q : Finset F) (z : Config k ι → ℂ)
    {X : Matrix (Config k ι) (Config k ι) ℂ}
    (hX : ∀ π, Commute (permOp (subsystemPerm k ι Qᶜ) π) X) :
    (complAverage ι k Q z * X).trace =
      (Fintype.card (Equiv.Perm (Fin k)) : ℂ) * (star z ⬝ᵥ (X *ᵥ z)) := by
  rw [complAverage, Finset.sum_mul, trace_sum]
  have hterm : ∀ π : Equiv.Perm (Fin k),
      (permOp (subsystemPerm k ι Qᶜ) π * vecMulVec z (star z) *
        permOp (subsystemPerm k ι Qᶜ) π⁻¹ * X).trace = star z ⬝ᵥ (X *ᵥ z) := by
    intro π
    set U := permOp (subsystemPerm k ι Qᶜ) π
    set V := permOp (subsystemPerm k ι Qᶜ) π⁻¹
    have h1 : U * vecMulVec z (star z) * V * X = U * (vecMulVec z (star z) * X) * V := by
      simp only [mul_assoc]
      rw [(hX π⁻¹).eq]
    rw [h1, trace_mul_cycle, ← mul_assoc, permOp_inv_mul_self, one_mul, vecMulVec_mul,
      trace_vecMulVec, dotProduct_comm, ← dotProduct_mulVec]
  rw [Finset.sum_congr rfl fun π _ => hterm π, Finset.sum_const, Finset.card_univ,
    nsmul_eq_mul]

/-- For a symmetric vector, the complement average commutes with the copy permutations of
`Q`: the `Q` marginal of a symmetric vector is permutation invariant (`05-replicas.tex`,
line 418). -/
theorem commute_complAverage {k : ℕ} (Q : Finset F) {z : Config k ι → ℂ}
    (hz : z ∈ symmetricSubspace k ι) (σ : Equiv.Perm (Fin k)) :
    Commute (permOp (subsystemPerm k ι Q) σ) (complAverage ι k Q z) := by
  unfold complAverage
  set φ := subsystemPerm k ι Q
  set ψ := subsystemPerm k ι Qᶜ
  have hcomm : ∀ a b, Commute (permOp φ a) (permOp ψ b) := fun a b =>
    commute_permOp_subsystemPerm_of_disjoint ι disjoint_compl_right a b
  have hcopy : ∀ g, permOp (copyPerm ((f : F) → ι f) k) g = permOp φ g * permOp ψ g :=
    permOp_of_eq_mul φ ψ _ (fun g => copyPerm_eq_mul_compl Q g)
  -- `U_Q(g) z = U_{Qᶜ}(g⁻¹) z` on symmetric vectors.
  have key : ∀ g, permOp φ g *ᵥ z = permOp ψ g⁻¹ *ᵥ z := by
    intro g
    calc permOp φ g *ᵥ z = permOp φ g *ᵥ ((permOp ψ g⁻¹ * permOp ψ g) *ᵥ z) := by
          rw [permOp_inv_mul_self, one_mulVec]
      _ = (permOp ψ g⁻¹ * (permOp φ g * permOp ψ g)) *ᵥ z := by
          rw [mulVec_mulVec, ← mul_assoc, (hcomm g g⁻¹).eq, mul_assoc]
      _ = permOp ψ g⁻¹ *ᵥ z := by rw [← mulVec_mulVec, ← hcopy, hz g]
  have hA1 : permOp φ σ * vecMulVec z (star z) = permOp ψ σ⁻¹ * vecMulVec z (star z) := by
    rw [mul_vecMulVec, mul_vecMulVec, key]
  have hA2 : vecMulVec z (star z) * permOp φ σ = vecMulVec z (star z) * permOp ψ σ⁻¹ := by
    rw [vecMulVec_mul, vecMulVec_mul]
    congr 1
    have h := key σ⁻¹
    rw [inv_inv] at h
    rw [← conjTranspose_conjTranspose (permOp φ σ), ← star_mulVec, conjTranspose_permOp, h,
      star_mulVec, conjTranspose_permOp]
  rw [Commute, SemiconjBy, Finset.mul_sum, Finset.sum_mul]
  have hL : ∀ π, permOp φ σ * (permOp ψ π * vecMulVec z (star z) * permOp ψ π⁻¹) =
      permOp ψ (π * σ⁻¹) * vecMulVec z (star z) * permOp ψ π⁻¹ := by
    intro π
    rw [← mul_assoc, ← mul_assoc, (hcomm σ π).eq, mul_assoc (permOp ψ π), hA1, ← mul_assoc,
      ← map_mul]
  have hR : ∀ π, permOp ψ π * vecMulVec z (star z) * permOp ψ π⁻¹ * permOp φ σ =
      permOp ψ π * vecMulVec z (star z) * permOp ψ (π * σ)⁻¹ := by
    intro π
    rw [mul_assoc, (hcomm σ π⁻¹).eq.symm, ← mul_assoc, mul_assoc (permOp ψ π), hA2, mul_assoc,
      mul_assoc, ← map_mul, ← _root_.mul_inv_rev, ← mul_assoc]
  simp_rw [hL, hR]
  exact Fintype.sum_equiv (Equiv.mulRight σ⁻¹) _ _ fun π => by
    simp only [Equiv.coe_mulRight, inv_mul_cancel_right]

/-! ### Branch weights -/

variable {ι} in
/-- The weight `‖π^λ π^ν z‖²` of a vector on a branch. -/
noncomputable abbrev branchWeight {m : ℕ} (Q : Finset F) (z : Config (m + 1) ι → ℂ)
    (p : IrrepLabel (Equiv.Perm (Fin (m + 1))) × IrrepLabel (Equiv.Perm (Fin m))) : ℝ :=
  RCLike.re (star z ⬝ᵥ ((labelProj (subsystemPerm (m + 1) ι Q) p.1 *
    labelProj ((subsystemPerm (m + 1) ι Q).comp (firstCopies m)) p.2) *ᵥ z))

theorem commute_permOp_compl_labelProj {k : ℕ} (Q : Finset F) (l : IrrepLabel (Equiv.Perm (Fin k)))
    (π : Equiv.Perm (Fin k)) :
    Commute (permOp (subsystemPerm k ι Qᶜ) π) (labelProj (subsystemPerm k ι Q) l) :=
  (commute_labelProj_of_forall_commute _
    (fun g => (commute_permOp_subsystemPerm_of_disjoint ι disjoint_compl_right g π)) l).symm

theorem commute_permOp_compl_labelProj_first {m : ℕ} (Q : Finset F)
    (n : IrrepLabel (Equiv.Perm (Fin m))) (π : Equiv.Perm (Fin (m + 1))) :
    Commute (permOp (subsystemPerm (m + 1) ι Qᶜ) π)
      (labelProj ((subsystemPerm (m + 1) ι Q).comp (firstCopies m)) n) :=
  (commute_labelProj_of_forall_commute _
    (fun g => by
      have h := commute_permOp_subsystemPerm_of_disjoint ι (k := m + 1) disjoint_compl_right
        (Q := Q) (firstCopies m g) π
      simpa only [permOp_apply, MonoidHom.comp_apply] using h) n).symm

/-- **Branch weights of a symmetric vector** (`05-replicas.tex`, lines 418–421): on a branch
`ν = λ - e_i`, `d_λ ‖π^λ π^ν z‖² = d_ν ‖π^λ z‖²`. -/
theorem weight_branch {m : ℕ} (Q : Finset F) {z : Config (m + 1) ι → ℂ}
    (hz : z ∈ symmetricSubspace (m + 1) ι)
    {p : IrrepLabel (Equiv.Perm (Fin (m + 1))) × IrrepLabel (Equiv.Perm (Fin m))}
    (hbr : ∃ i, labelPart p.1 = Function.update (labelPart p.2) i (labelPart p.2 i + 1)) :
    (p.1.dim : ℝ) * branchWeight Q z p =
      p.2.dim * RCLike.re (star z ⬝ᵥ (labelProj (subsystemPerm (m + 1) ι Q) p.1 *ᵥ z)) := by
  have h := trace_mul_labelProj_mul_labelProj_firstCopies (subsystemPerm (m + 1) ι Q)
    (M := complAverage ι (m + 1) Q z) (fun g => commute_complAverage ι Q hz g) hbr
  rw [trace_complAverage_mul ι (m + 1) Q z (fun π =>
      (commute_permOp_compl_labelProj ι Q p.1 π).mul_right
        (commute_permOp_compl_labelProj_first ι Q p.2 π)),
    trace_complAverage_mul ι (m + 1) Q z (fun π => commute_permOp_compl_labelProj ι Q p.1 π)]
    at h
  have hk : (Fintype.card (Equiv.Perm (Fin (m + 1))) : ℂ) ≠ 0 := by
    exact_mod_cast Fintype.card_ne_zero
  have h' : (p.1.dim : ℂ) * (star z ⬝ᵥ ((labelProj (subsystemPerm (m + 1) ι Q) p.1 *
      labelProj ((subsystemPerm (m + 1) ι Q).comp (firstCopies m)) p.2) *ᵥ z)) =
      p.2.dim * (star z ⬝ᵥ (labelProj (subsystemPerm (m + 1) ι Q) p.1 *ᵥ z)) := by
    have := h
    rw [mul_left_comm, mul_left_comm (p.2.dim : ℂ)] at this
    exact mul_left_cancel₀ hk this
  have := congrArg RCLike.re h'
  simpa [branchWeight] using this

/-- Summing the branch weights over `ν` gives the weight of `λ`. -/
theorem sum_branchWeight_snd {m : ℕ} (Q : Finset F) (z : Config (m + 1) ι → ℂ)
    (l : IrrepLabel (Equiv.Perm (Fin (m + 1)))) :
    ∑ n, branchWeight Q z (l, n) =
      RCLike.re (star z ⬝ᵥ (labelProj (subsystemPerm (m + 1) ι Q) l *ᵥ z)) := by
  simp only [branchWeight, ← map_sum, ← dotProduct_sum,
    ← sum_mulVec, ← Finset.mul_sum, (isOrthogonalResolution_labelProj _).sum_eq, mul_one]

/-- A label `λ` has at most `d` branches with nonzero projector. -/
theorem card_branch_le [∀ f, Nonempty (ι f)] {m : ℕ} (Q : Finset F)
    (l : IrrepLabel (Equiv.Perm (Fin (m + 1)))) :
    (Finset.univ.filter fun n : IrrepLabel (Equiv.Perm (Fin m)) =>
      labelProj (subsystemPerm (m + 1) ι Q) l *
        labelProj ((subsystemPerm (m + 1) ι Q).comp (firstCopies m)) n ≠ 0).card ≤
      replicaDim ι := by
  classical
  set S := Finset.univ.filter fun n : IrrepLabel (Equiv.Perm (Fin m)) =>
    labelProj (subsystemPerm (m + 1) ι Q) l *
      labelProj ((subsystemPerm (m + 1) ι Q).comp (firstCopies m)) n ≠ 0
  have hmem : ∀ n ∈ S, markedRow (l, n) ∈ Finset.range (replicaDim ι) := by
    intro n hn
    have hp := (Finset.mem_filter.mp hn).2
    obtain ⟨hl, hbr⟩ := (labelProj_mul_labelProj_firstCopies_ne_zero_iff _ l n).mp hp
    have hspec := markedRow_spec (p := (l, n)) hbr
    have hrows : ∀ a, replicaDim ι ≤ a → labelPart l a = 0 := fun a ha =>
      labelPart_eq_zero_of_subsystemPerm ι (m + 1) Q hl a ((card_subConfig_le ι Q).trans ha)
    rw [Finset.mem_range]
    by_contra h
    have h1 := hrows _ (not_lt.mp h)
    have h2 : labelPart l (markedRow (l, n)) = labelPart n (markedRow (l, n)) + 1 := by
      conv_lhs => rw [hspec]
      simp
    omega
  have hinj : Set.InjOn (fun n => markedRow (l, n)) S := by
    intro n hn n' hn' hrow
    have hbr := ((labelProj_mul_labelProj_firstCopies_ne_zero_iff _ l n).mp
      (Finset.mem_filter.mp hn).2).2
    have hbr' := ((labelProj_mul_labelProj_firstCopies_ne_zero_iff _ l n').mp
      (Finset.mem_filter.mp hn').2).2
    have hs := markedRow_spec (p := (l, n)) hbr
    have hs' := markedRow_spec (p := (l, n')) hbr'
    simp only at hrow hs hs'
    rw [hrow] at hs
    refine labelPart_injective (funext fun a => ?_)
    have e := congrFun (hs.symm.trans hs') a
    by_cases ha : a = markedRow (l, n')
    · subst ha; simpa using e
    · simpa [Function.update_of_ne ha] using e
  calc S.card ≤ (Finset.range (replicaDim ι)).card :=
        Finset.card_le_card_of_injOn _ (fun n hn => hmem n hn) hinj
    _ = replicaDim ι := Finset.card_range _

/-- Summation over branches: if each branch term is at most `G λ` on nonzero branches and
vanishes otherwise, the total is at most `d ∑_λ G λ`. -/
theorem sum_le_of_branch [∀ f, Nonempty (ι f)] {m : ℕ} (Q : Finset F)
    (T : IrrepLabel (Equiv.Perm (Fin (m + 1))) × IrrepLabel (Equiv.Perm (Fin m)) → ℝ)
    (G : IrrepLabel (Equiv.Perm (Fin (m + 1))) → ℝ) (hG : ∀ l, 0 ≤ G l)
    (hT : ∀ p, T p ≤ if labelProj (subsystemPerm (m + 1) ι Q) p.1 *
      labelProj ((subsystemPerm (m + 1) ι Q).comp (firstCopies m)) p.2 ≠ 0 then G p.1 else 0) :
    ∑ p, T p ≤ replicaDim ι * ∑ l, G l := by
  classical
  refine (Finset.sum_le_sum fun p _ => hT p).trans ?_
  rw [Fintype.sum_prod_type, Finset.mul_sum]
  refine Finset.sum_le_sum fun l _ => ?_
  rw [← Finset.sum_filter]
  dsimp only
  rw [Finset.sum_const, nsmul_eq_mul]
  exact mul_le_mul_of_nonneg_right (by exact_mod_cast card_branch_le ι Q l) (hG l)

/-! ### The inverse marked ratio -/

/-- `R_{Q,k}^{-1} = ∑ (w_{k-1}(ν)/w_k(λ)) π^λ π^ν`. -/
theorem markedRatio_inv_eq_hom [∀ f, Nonempty (ι f)] {t : ℝ} (ht : 0 ≤ t) (m : ℕ)
    (Q : Finset F) :
    (markedRatio ι t m Q)⁻¹ = (isOrthogonalResolution_branch m Q).hom
      fun p => ((replicaLabelWeight ι t p.2 / replicaLabelWeight ι t p.1 : ℝ) : ℂ) := by
  rw [markedRatio_eq_hom ι ht]
  refine Matrix.inv_eq_left_inv ?_
  rw [← map_mul, ← map_one (isOrthogonalResolution_branch (ι := ι) m Q).hom]
  congr 1
  ext p
  have h1 := (replicaLabelWeight_pos ι ht p.1).ne'
  have h2 := (replicaLabelWeight_pos ι ht p.2).ne'
  simp only [Pi.mul_apply, Pi.one_apply, ← Complex.ofReal_mul]
  rw [div_mul_div_comm, mul_comm (replicaLabelWeight ι t p.2), div_self (mul_ne_zero h1 h2)]
  simp

/-- The squared norm of `∑ c_p π^λ π^ν z` in terms of branch weights. -/
theorem re_star_dotProduct_branch_hom_mulVec_self {m : ℕ} (Q : Finset F)
    (c : IrrepLabel (Equiv.Perm (Fin (m + 1))) × IrrepLabel (Equiv.Perm (Fin m)) → ℂ)
    (z : Config (m + 1) ι → ℂ) :
    RCLike.re (star ((isOrthogonalResolution_branch m Q).hom c *ᵥ z) ⬝ᵥ
        ((isOrthogonalResolution_branch m Q).hom c *ᵥ z)) =
      ∑ p, ‖c p‖ ^ 2 * branchWeight Q z p :=
  (isOrthogonalResolution_branch m Q).re_star_dotProduct_hom_mulVec_self
    (isHermitian_branch ι m Q) c z

theorem branchWeight_nonneg {m : ℕ} (Q : Finset F) (z : Config (m + 1) ι → ℂ)
    (p : IrrepLabel (Equiv.Perm (Fin (m + 1))) × IrrepLabel (Equiv.Perm (Fin m))) :
    0 ≤ branchWeight Q z p :=
  (isOrthogonalResolution_branch m Q).weight_nonneg (isHermitian_branch ι m Q) z p

theorem labelWeight_nonneg {k : ℕ} (Q : Finset F) (z : Config k ι → ℂ)
    (l : IrrepLabel (Equiv.Perm (Fin k))) :
    0 ≤ RCLike.re (star z ⬝ᵥ (labelProj (subsystemPerm k ι Q) l *ᵥ z)) :=
  (isOrthogonalResolution_labelProj _).weight_nonneg (isHermitian_labelProj _) z l

theorem sum_labelWeight {k : ℕ} (Q : Finset F) (z : Config k ι → ℂ) :
    ∑ l, RCLike.re (star z ⬝ᵥ (labelProj (subsystemPerm k ι Q) l *ᵥ z)) =
      RCLike.re (star z ⬝ᵥ z) :=
  (isOrthogonalResolution_labelProj _).sum_weight z

theorem sum_branchWeight {m : ℕ} (Q : Finset F) (z : Config (m + 1) ι → ℂ) :
    ∑ p, branchWeight Q z p = RCLike.re (star z ⬝ᵥ z) :=
  (isOrthogonalResolution_branch m Q).sum_weight z

theorem branchWeight_eq_zero {m : ℕ} (Q : Finset F) (z : Config (m + 1) ι → ℂ)
    {p : IrrepLabel (Equiv.Perm (Fin (m + 1))) × IrrepLabel (Equiv.Perm (Fin m))}
    (hp : labelProj (subsystemPerm (m + 1) ι Q) p.1 *
      labelProj ((subsystemPerm (m + 1) ι Q).comp (firstCopies m)) p.2 = 0) :
    branchWeight Q z p = 0 := by
  simp [branchWeight, hp]

/-- The scalar data of a nonzero branch of a symmetric vector: the marked ratio `r(k, L)`,
the star eigenvalue `(L - d)/k`, and the branch weight at most `2^d (L/k)` times the weight of
`λ`. -/
theorem exists_branch_data [∀ f, Nonempty (ι f)] {t : ℝ} (ht : 0 ≤ t) {m : ℕ} (Q : Finset F)
    {z : Config (m + 1) ι → ℂ} (hz : z ∈ symmetricSubspace (m + 1) ι)
    (p : IrrepLabel (Equiv.Perm (Fin (m + 1))) × IrrepLabel (Equiv.Perm (Fin m)))
    (hp : labelProj (subsystemPerm (m + 1) ι Q) p.1 *
      labelProj ((subsystemPerm (m + 1) ι Q).comp (firstCopies m)) p.2 ≠ 0) :
    ∃ L : ℕ, 1 ≤ L ∧ L ≤ (m + 1) + replicaDim ι ∧
      replicaLabelWeight ι t p.1 / replicaLabelWeight ι t p.2 =
        Partition.replicaRatio (replicaDim ι) t (m + 1 : ℕ) L ∧
      starValue p = ((L : ℝ) - replicaDim ι) / (m + 1 : ℕ) ∧
      branchWeight Q z p ≤ 2 ^ replicaDim ι * ((L : ℝ) / (m + 1 : ℕ)) *
        RCLike.re (star z ⬝ᵥ (labelProj (subsystemPerm (m + 1) ι Q) p.1 *ᵥ z)) := by
  obtain ⟨L, h1, h2, h3, h4, h5⟩ := exists_branch_scalars ι ht m Q p hp
  refine ⟨L, h1, h2, h3, h4, ?_⟩
  have hbr := ((labelProj_mul_labelProj_firstCopies_ne_zero_iff _ p.1 p.2).mp hp).2
  have hw := weight_branch ι Q hz hbr
  have hd1 : (0 : ℝ) < p.1.dim := by exact_mod_cast p.1.dim_pos
  have heq : branchWeight Q z p = (p.2.dim : ℝ) / p.1.dim *
      RCLike.re (star z ⬝ᵥ (labelProj (subsystemPerm (m + 1) ι Q) p.1 *ᵥ z)) := by
    field_simp
    linarith
  rw [heq]
  exact mul_le_mul_of_nonneg_right h5 (labelWeight_nonneg ι Q z p.1)

/-- Scalar estimate for the inverse bound: if `r ≥ C⁻¹ x^t` with `0 < x ≤ 1 + d` and
`0 < t < 1/2`, then `r⁻² x ≤ C² (1 + d)`. -/
private theorem inv_sq_mul_le {r x C d t : ℝ} (hC : 1 ≤ C) (hd : 0 ≤ d) (hx0 : 0 < x)
    (hxd : x ≤ 1 + d)
    (ht0 : 0 < t) (ht1 : t < 1 / 2) (hr : C⁻¹ * x ^ t ≤ r) :
    (r⁻¹) ^ 2 * x ≤ C ^ 2 * (1 + d) := by
  have hxt : 0 < x ^ t := Real.rpow_pos_of_pos hx0 t
  have hr0 : 0 < r := lt_of_lt_of_le (by positivity) hr
  have hinv : r⁻¹ ≤ C * (x ^ t)⁻¹ := by
    rw [inv_le_comm₀ hr0 (by positivity), mul_inv, inv_inv]
    exact hr
  have h1 : (r⁻¹) ^ 2 * x ≤ C ^ 2 * (x ^ (1 - 2 * t)) := by
    have hsq : (r⁻¹) ^ 2 ≤ (C * (x ^ t)⁻¹) ^ 2 :=
      pow_le_pow_left₀ (inv_nonneg.mpr hr0.le) hinv 2
    have hpow : ((x ^ t)⁻¹) ^ 2 * x = x ^ (1 - 2 * t) := by
      rw [← Real.rpow_natCast, ← Real.rpow_neg hx0.le, ← Real.rpow_mul hx0.le,
        ← Real.rpow_add_one hx0.ne']
      congr 1
      push_cast
      ring
    calc (r⁻¹) ^ 2 * x ≤ (C * (x ^ t)⁻¹) ^ 2 * x := mul_le_mul_of_nonneg_right hsq hx0.le
      _ = C ^ 2 * (((x ^ t)⁻¹) ^ 2 * x) := by ring
      _ = C ^ 2 * x ^ (1 - 2 * t) := by rw [hpow]
  refine h1.trans (mul_le_mul_of_nonneg_left ?_ (by positivity))
  rcases le_or_gt x 1 with hx1 | hx1
  · calc x ^ (1 - 2 * t) ≤ 1 := Real.rpow_le_one hx0.le hx1 (by linarith)
      _ ≤ 1 + d := by linarith
  · calc x ^ (1 - 2 * t) ≤ x ^ (1 : ℝ) := Real.rpow_le_rpow_of_exponent_le hx1.le (by linarith)
      _ = x := Real.rpow_one x
      _ ≤ 1 + d := hxd

/-- **Lemma 6.2, inverse bound on symmetric vectors** (`05-replicas.tex`, lines 324–325 and
418–425): for `0 < t < 1/2` there is `C` with `‖R_{Q,k}^{-1} z‖ ≤ C ‖z‖` for every symmetric
vector `z`, uniformly in `k` and `Q`. No full-space inverse bound is asserted. -/
theorem exists_norm_markedRatio_inv_mulVec_le [∀ f, Nonempty (ι f)] {t : ℝ} (ht0 : 0 < t)
    (ht1 : t < 1 / 2) :
    ∃ C, ∀ (m : ℕ) (Q : Finset F) (z : Config (m + 1) ι → ℂ),
      z ∈ symmetricSubspace (m + 1) ι →
        ‖(EuclideanSpace.equiv _ ℂ).symm ((markedRatio ι t m Q)⁻¹ *ᵥ z)‖ ≤
          C * ‖(EuclideanSpace.equiv _ ℂ).symm z‖ := by
  set d := replicaDim ι
  obtain ⟨C₀, hC₀, hC₀r⟩ := Partition.exists_replicaRatio_bounds (replicaDim_pos ι) ht0
    (by linarith)
  set B : ℝ := 2 ^ d * (C₀ ^ 2 * (1 + d))
  have hB : 0 ≤ B := by positivity
  refine ⟨Real.sqrt (d * B), fun m Q z hz => ?_⟩
  have hsq : RCLike.re (star ((markedRatio ι t m Q)⁻¹ *ᵥ z) ⬝ᵥ ((markedRatio ι t m Q)⁻¹ *ᵥ z)) ≤
      d * B * RCLike.re (star z ⬝ᵥ z) := by
    rw [markedRatio_inv_eq_hom ι ht0.le, re_star_dotProduct_branch_hom_mulVec_self,
      ← sum_labelWeight ι Q z, mul_assoc, Finset.mul_sum]
    refine sum_le_of_branch ι Q _ _ (fun l => mul_nonneg hB (labelWeight_nonneg ι Q z l))
      fun p => ?_
    split_ifs with hp
    · obtain ⟨L, hL1, hL2, hr, -, hw⟩ := exists_branch_data ι ht0.le Q hz p hp
      have hk : (0 : ℝ) < (m + 1 : ℕ) := by positivity
      have hx0 : (0 : ℝ) < L / (m + 1 : ℕ) := div_pos (by exact_mod_cast hL1) hk
      have hxd : (L : ℝ) / (m + 1 : ℕ) ≤ 1 + d := by
        rw [div_le_iff₀ hk]
        have : (L : ℝ) ≤ (m + 1 : ℕ) + d := by exact_mod_cast hL2
        have : (d : ℝ) ≤ d * (m + 1 : ℕ) := le_mul_of_one_le_right (by positivity)
          (by exact_mod_cast Nat.succ_pos m)
        nlinarith
      have hrb := (hC₀r (m + 1) L (by omega) hL1 hL2).1
      have hc : ‖((replicaLabelWeight ι t p.2 / replicaLabelWeight ι t p.1 : ℝ) : ℂ)‖ =
          (Partition.replicaRatio d t (m + 1 : ℕ) L)⁻¹ := by
        rw [Complex.norm_real, Real.norm_eq_abs, ← inv_div, hr, abs_of_pos]
        exact inv_pos.mpr (lt_of_lt_of_le (by positivity) hrb)
      have hscalar := inv_sq_mul_le hC₀ d.cast_nonneg hx0 hxd ht0 ht1 hrb
      rw [hc]
      have hW := labelWeight_nonneg ι Q z p.1
      calc (Partition.replicaRatio d t (m + 1 : ℕ) L)⁻¹ ^ 2 * branchWeight Q z p
          ≤ (Partition.replicaRatio d t (m + 1 : ℕ) L)⁻¹ ^ 2 *
            (2 ^ d * ((L : ℝ) / (m + 1 : ℕ)) *
              RCLike.re (star z ⬝ᵥ (labelProj (subsystemPerm (m + 1) ι Q) p.1 *ᵥ z))) :=
            mul_le_mul_of_nonneg_left hw (by positivity)
        _ = 2 ^ d * ((Partition.replicaRatio d t (m + 1 : ℕ) L)⁻¹ ^ 2 *
              ((L : ℝ) / (m + 1 : ℕ))) *
              RCLike.re (star z ⬝ᵥ (labelProj (subsystemPerm (m + 1) ι Q) p.1 *ᵥ z)) := by ring
        _ ≤ 2 ^ d * (C₀ ^ 2 * (1 + d)) *
              RCLike.re (star z ⬝ᵥ (labelProj (subsystemPerm (m + 1) ι Q) p.1 *ᵥ z)) := by
            gcongr
    · rw [branchWeight_eq_zero ι Q z (not_not.mp hp), mul_zero]
  rw [re_star_dotProduct_self_eq_norm_sq, re_star_dotProduct_self_eq_norm_sq] at hsq
  have hdB : 0 ≤ (d : ℝ) * B := by positivity
  rw [← Real.sqrt_le_sqrt_iff (by positivity), Real.sqrt_sq (norm_nonneg _),
    Real.sqrt_mul hdB, Real.sqrt_sq (norm_nonneg _)] at hsq
  exact hsq

/-! ### The clipped inverse -/

/-- Scalar estimate on `J ≥ δ`: if `r ≥ C⁻¹ x^t`, `δ ≤ e ≤ x` and `|r - e^t| ≤ η`, then
`|r⁻¹ - e^{-t}| ≤ C η δ^{-2t}`. -/
private theorem abs_inv_sub_rpow_neg_le {r x e δ C η t : ℝ} (hC : 1 ≤ C) (hδ : 0 < δ)
    (hδe : δ ≤ e) (hex : e ≤ x) (ht0 : 0 < t) (hr : C⁻¹ * x ^ t ≤ r) (hη : |r - e ^ t| ≤ η) :
    |r⁻¹ - e ^ (-t)| ≤ C * η * (δ ^ (2 * t))⁻¹ := by
  have he0 : 0 < e := lt_of_lt_of_le hδ hδe
  have hx0 : 0 < x := lt_of_lt_of_le he0 hex
  have het : 0 < e ^ t := Real.rpow_pos_of_pos he0 t
  have hr0 : 0 < r := lt_of_lt_of_le (by positivity) hr
  have hδ2 : δ ^ (2 * t) ≤ e ^ t * e ^ t := by
    rw [← Real.rpow_add he0, ← two_mul]
    exact Real.rpow_le_rpow hδ.le hδe (by positivity)
  have hxe : e ^ t ≤ x ^ t := Real.rpow_le_rpow he0.le hex ht0.le
  have hre : C⁻¹ * δ ^ (2 * t) ≤ r * e ^ t := by
    calc C⁻¹ * δ ^ (2 * t) ≤ C⁻¹ * (e ^ t * e ^ t) :=
          mul_le_mul_of_nonneg_left hδ2 (by positivity)
      _ = C⁻¹ * e ^ t * e ^ t := by ring
      _ ≤ C⁻¹ * x ^ t * e ^ t := by gcongr
      _ ≤ r * e ^ t := mul_le_mul_of_nonneg_right hr het.le
  rw [Real.rpow_neg he0.le, inv_sub_inv hr0.ne' het.ne', abs_div, abs_of_pos (mul_pos hr0 het),
    abs_sub_comm, div_le_iff₀ (mul_pos hr0 het)]
  have hη0 : 0 ≤ η := (abs_nonneg _).trans hη
  calc |r - e ^ t| ≤ η := hη
    _ = C * η * (δ ^ (2 * t))⁻¹ * (C⁻¹ * δ ^ (2 * t)) := by
        have : (0 : ℝ) < δ ^ (2 * t) := by positivity
        field_simp
    _ ≤ C * η * (δ ^ (2 * t))⁻¹ * (r * e ^ t) := by gcongr

/-- `r⁻² x ≤ C² x^{1-2t}` when `r ≥ C⁻¹ x^t`. -/
private theorem inv_sq_mul_le_rpow {r x C t : ℝ} (hC : 1 ≤ C) (hx0 : 0 < x)
    (hr : C⁻¹ * x ^ t ≤ r) : (r⁻¹) ^ 2 * x ≤ C ^ 2 * x ^ (1 - 2 * t) := by
  have hxt : 0 < x ^ t := Real.rpow_pos_of_pos hx0 t
  have hr0 : 0 < r := lt_of_lt_of_le (by positivity) hr
  have hinv : r⁻¹ ≤ C * (x ^ t)⁻¹ := by
    rw [inv_le_comm₀ hr0 (by positivity), mul_inv, inv_inv]
    exact hr
  have hsq : (r⁻¹) ^ 2 ≤ (C * (x ^ t)⁻¹) ^ 2 := pow_le_pow_left₀ (inv_nonneg.mpr hr0.le) hinv 2
  have hpow : ((x ^ t)⁻¹) ^ 2 * x = x ^ (1 - 2 * t) := by
    rw [← Real.rpow_natCast, ← Real.rpow_neg hx0.le, ← Real.rpow_mul hx0.le,
      ← Real.rpow_add_one hx0.ne']
    congr 1
    push_cast
    ring
  calc (r⁻¹) ^ 2 * x ≤ (C * (x ^ t)⁻¹) ^ 2 * x := mul_le_mul_of_nonneg_right hsq hx0.le
    _ = C ^ 2 * (((x ^ t)⁻¹) ^ 2 * x) := by ring
    _ = C ^ 2 * x ^ (1 - 2 * t) := by rw [hpow]

/-- The finite-copy form of the clipped inverse estimate: for symmetric `z`,
`‖(R_{Q,k}^{-1} - max(J_{Q,k}, δ)^{-t}) z‖² ≤ (A_k + d B_k) ‖z‖²` with
`A_k = (C₀ C₁ k^{-t} δ^{-2t})²` and `B_k = 2^d (2 C₀² (δ + d/k)^{1-2t} + 2 δ^{-2t} (δ + d/k))`. -/
theorem exists_markedRatio_inv_sub_clipped_sq_le [∀ f, Nonempty (ι f)] {t : ℝ} (ht0 : 0 < t)
    (ht1 : t < 1 / 2) :
    ∃ C₀ C₁ : ℝ, 1 ≤ C₀ ∧ 0 ≤ C₁ ∧ ∀ (δ : ℝ), 0 < δ → ∀ (m : ℕ) (Q : Finset F)
      (z : Config (m + 1) ι → ℂ), z ∈ symmetricSubspace (m + 1) ι →
        RCLike.re (star (((markedRatio ι t m Q)⁻¹ -
            cfc (fun x : ℝ => (max x δ) ^ (-t)) (starOp (subsystemPerm (m + 1) ι Q))) *ᵥ z) ⬝ᵥ
          (((markedRatio ι t m Q)⁻¹ -
            cfc (fun x : ℝ => (max x δ) ^ (-t)) (starOp (subsystemPerm (m + 1) ι Q))) *ᵥ z)) ≤
        ((C₀ * C₁ * ((m + 1 : ℕ) : ℝ) ^ (-t) * (δ ^ (2 * t))⁻¹) ^ 2 +
          replicaDim ι * (2 ^ replicaDim ι * (2 * C₀ ^ 2 *
            (δ + replicaDim ι / ((m + 1 : ℕ) : ℝ)) ^ (1 - 2 * t) +
            2 * (δ ^ (2 * t))⁻¹ * (δ + replicaDim ι / ((m + 1 : ℕ) : ℝ))))) *
          RCLike.re (star z ⬝ᵥ z) := by
  set d := replicaDim ι
  obtain ⟨C₀, hC₀, hC₀r⟩ := Partition.exists_replicaRatio_bounds (replicaDim_pos ι) ht0
    (by linarith)
  obtain ⟨C₁, hC₁⟩ := Partition.exists_abs_replicaRatio_sub_le (replicaDim_pos ι) ht0
    (by linarith)
  refine ⟨C₀, max C₁ 0, hC₀, le_max_right _ _, fun δ hδ m Q z hz => ?_⟩
  set k : ℝ := ((m + 1 : ℕ) : ℝ)
  have hk : 0 < k := by positivity
  set A := (C₀ * max C₁ 0 * k ^ (-t) * (δ ^ (2 * t))⁻¹) ^ 2
  set B := 2 ^ d * (2 * C₀ ^ 2 * (δ + d / k) ^ (1 - 2 * t) +
    2 * (δ ^ (2 * t))⁻¹ * (δ + d / k))
  have hB : 0 ≤ B := by positivity
  set hJ := isOrthogonalResolution_branch (ι := ι) m Q
  have hD : cfc (fun x : ℝ => (max x δ) ^ (-t)) (starOp (subsystemPerm (m + 1) ι Q)) =
      hJ.hom fun p => (((max (starValue p) δ) ^ (-t) : ℝ) : ℂ) := by
    rw [starOp_subsystemPerm_eq_hom, IsOrthogonalResolution.cfc_hom _ (isHermitian_branch ι m Q)]
  rw [hD, markedRatio_inv_eq_hom ι ht0.le, ← map_sub, re_star_dotProduct_branch_hom_mulVec_self]
  -- Each term is at most `A · (branch weight) + [nonzero] B · (weight of λ)`.
  have hterm : ∀ p, ‖(((fun q : IrrepLabel (Equiv.Perm (Fin (m + 1))) ×
      IrrepLabel (Equiv.Perm (Fin m)) =>
        ((replicaLabelWeight ι t q.2 / replicaLabelWeight ι t q.1 : ℝ) : ℂ)) -
      fun q : IrrepLabel (Equiv.Perm (Fin (m + 1))) × IrrepLabel (Equiv.Perm (Fin m)) =>
        (((max (starValue q) δ) ^ (-t) : ℝ) : ℂ)) p)‖ ^ 2 * branchWeight Q z p -
      A * branchWeight Q z p ≤
        if labelProj (subsystemPerm (m + 1) ι Q) p.1 *
          labelProj ((subsystemPerm (m + 1) ι Q).comp (firstCopies m)) p.2 ≠ 0 then
          B * RCLike.re (star z ⬝ᵥ (labelProj (subsystemPerm (m + 1) ι Q) p.1 *ᵥ z)) else 0 := by
    intro p
    have hbw := branchWeight_nonneg ι Q z p
    have hW := labelWeight_nonneg ι Q z p.1
    split_ifs with hp
    · obtain ⟨L, hL1, hL2, hr, hs, hw⟩ := exists_branch_data ι ht0.le Q hz p hp
      set r := Partition.replicaRatio d t (m + 1 : ℕ) L
      set x : ℝ := (L : ℝ) / k
      set e := starValue p
      have hx0 : 0 < x := div_pos (by exact_mod_cast hL1) hk
      have hrb := (hC₀r (m + 1) L (by omega) hL1 hL2).1
      have hr0 : 0 < r := lt_of_lt_of_le (by positivity) hrb
      have hc : ‖(((fun q : IrrepLabel (Equiv.Perm (Fin (m + 1))) ×
          IrrepLabel (Equiv.Perm (Fin m)) =>
            ((replicaLabelWeight ι t q.2 / replicaLabelWeight ι t q.1 : ℝ) : ℂ)) -
          fun q : IrrepLabel (Equiv.Perm (Fin (m + 1))) × IrrepLabel (Equiv.Perm (Fin m)) =>
            (((max (starValue q) δ) ^ (-t) : ℝ) : ℂ)) p)‖ =
          |r⁻¹ - (max e δ) ^ (-t)| := by
        simp only [Pi.sub_apply]
        rw [← Complex.ofReal_sub, Complex.norm_real, Real.norm_eq_abs, ← inv_div, hr]
      rw [hc]
      have hex : e = x - d / k := by rw [hs]; simp only [x, k]; ring
      rcases le_or_gt δ e with hδe | hδe
      · -- On `J ≥ δ`.
        rw [max_eq_left hδe]
        have hη : |r - e ^ t| ≤ max C₁ 0 * k ^ (-t) := by
          have h := hC₁ (m + 1) L (by omega) hL1 hL2
          rw [← hs, max_eq_left (le_trans hδ.le hδe)] at h
          exact h.trans (mul_le_mul_of_nonneg_right (le_max_left _ _) (by positivity))
        have hexle : e ≤ x := by rw [hex]; linarith [div_nonneg d.cast_nonneg hk.le]
        have h := abs_inv_sub_rpow_neg_le hC₀ hδ hδe hexle ht0 hrb hη
        have h2 : |r⁻¹ - e ^ (-t)| ^ 2 ≤ A := by
          calc |r⁻¹ - e ^ (-t)| ^ 2 ≤ (C₀ * (max C₁ 0 * k ^ (-t)) * (δ ^ (2 * t))⁻¹) ^ 2 :=
                pow_le_pow_left₀ (abs_nonneg _) h 2
            _ = A := by simp only [A]; ring
        have : |r⁻¹ - e ^ (-t)| ^ 2 * branchWeight Q z p ≤ A * branchWeight Q z p :=
          mul_le_mul_of_nonneg_right h2 hbw
        have : 0 ≤ B * RCLike.re (star z ⬝ᵥ (labelProj (subsystemPerm (m + 1) ι Q) p.1 *ᵥ z)) :=
          mul_nonneg hB hW
        linarith
      · -- On `J < δ`.
        rw [max_eq_right hδe.le]
        have hxlt : x ≤ δ + d / k := by rw [hex] at hδe; linarith
        have hsq : |r⁻¹ - δ ^ (-t)| ^ 2 ≤ 2 * (r⁻¹) ^ 2 + 2 * (δ ^ (2 * t))⁻¹ := by
          have hδt : (δ ^ (-t)) ^ 2 = (δ ^ (2 * t))⁻¹ := by
            rw [← Real.rpow_natCast, ← Real.rpow_mul hδ.le, ← Real.rpow_neg hδ.le]
            congr 1
            push_cast
            ring
          rw [sq_abs, ← hδt]
          nlinarith [sq_nonneg (r⁻¹ + δ ^ (-t))]
        have h1 := inv_sq_mul_le_rpow hC₀ hx0 hrb
        have h2 : x ^ (1 - 2 * t) ≤ (δ + d / k) ^ (1 - 2 * t) :=
          Real.rpow_le_rpow hx0.le hxlt (by linarith)
        have hAbw : 0 ≤ A * branchWeight Q z p := by positivity
        calc |r⁻¹ - δ ^ (-t)| ^ 2 * branchWeight Q z p - A * branchWeight Q z p
            ≤ |r⁻¹ - δ ^ (-t)| ^ 2 * branchWeight Q z p := by linarith
          _ ≤ (2 * (r⁻¹) ^ 2 + 2 * (δ ^ (2 * t))⁻¹) *
              (2 ^ d * x * RCLike.re (star z ⬝ᵥ
                (labelProj (subsystemPerm (m + 1) ι Q) p.1 *ᵥ z))) := by
              gcongr
          _ = 2 ^ d * (2 * ((r⁻¹) ^ 2 * x) + 2 * (δ ^ (2 * t))⁻¹ * x) *
              RCLike.re (star z ⬝ᵥ (labelProj (subsystemPerm (m + 1) ι Q) p.1 *ᵥ z)) := by
              ring
          _ ≤ B * RCLike.re (star z ⬝ᵥ (labelProj (subsystemPerm (m + 1) ι Q) p.1 *ᵥ z)) := by
              refine mul_le_mul_of_nonneg_right ?_ hW
              have h3 : (r⁻¹) ^ 2 * x ≤ C₀ ^ 2 * (δ + d / k) ^ (1 - 2 * t) :=
                h1.trans (mul_le_mul_of_nonneg_left h2 (by positivity))
              have h4 : (δ ^ (2 * t))⁻¹ * x ≤ (δ ^ (2 * t))⁻¹ * (δ + d / k) :=
                mul_le_mul_of_nonneg_left hxlt (by positivity)
              simp only [B]
              refine mul_le_mul_of_nonneg_left ?_ (by positivity)
              linarith
    · rw [branchWeight_eq_zero ι Q z (not_not.mp hp)]
      simp
  have hsum := sum_le_of_branch ι Q _ (fun l => B * RCLike.re (star z ⬝ᵥ
    (labelProj (subsystemPerm (m + 1) ι Q) l *ᵥ z))) (fun l => mul_nonneg hB
      (labelWeight_nonneg ι Q z l)) hterm
  rw [Finset.sum_sub_distrib, ← Finset.mul_sum, sum_branchWeight, ← Finset.mul_sum,
    sum_labelWeight] at hsum
  have : (A + d * B) * RCLike.re (star z ⬝ᵥ z) =
      A * RCLike.re (star z ⬝ᵥ z) + d * (B * RCLike.re (star z ⬝ᵥ z)) := by ring
  simp only [A, B, k] at hsum this ⊢
  linarith

/-- **Lemma 6.2, clipped inverse marked ratio** (`05-replicas.tex`, equation
`replicas:R-inverse`, lines 326–335 and 425–430): for `0 < t < 1/2` there is `C` such that,
for every `0 < δ < 1`,

`limsup_k sup_{z ∈ 𝒮_k, ‖z‖ = 1} ‖(R_{Q,k}^{-1} - max(J_{Q,k}, δ)^{-t}) z‖ ≤ C δ^{(1-2t)/2}`,

in the equivalent form: for every `ε > 0` the bound `(C δ^{(1-2t)/2} + ε) ‖z‖` holds for all
sufficiently many copies, uniformly in the subsystem and in the symmetric vector `z`. -/
theorem exists_norm_markedRatio_inv_sub_clipped_le [∀ f, Nonempty (ι f)] {t : ℝ} (ht0 : 0 < t)
    (ht1 : t < 1 / 2) :
    ∃ C, ∀ δ : ℝ, 0 < δ → δ < 1 → ∀ ε : ℝ, 0 < ε → ∃ K : ℕ, ∀ m ≥ K, ∀ (Q : Finset F)
      (z : Config (m + 1) ι → ℂ), z ∈ symmetricSubspace (m + 1) ι →
        ‖(EuclideanSpace.equiv _ ℂ).symm (((markedRatio ι t m Q)⁻¹ -
            cfc (fun x : ℝ => (max x δ) ^ (-t)) (starOp (subsystemPerm (m + 1) ι Q))) *ᵥ z)‖ ≤
          (C * δ ^ ((1 - 2 * t) / 2) + ε) * ‖(EuclideanSpace.equiv _ ℂ).symm z‖ := by
  set d := replicaDim ι
  obtain ⟨C₀, C₁, hC₀, hC₁, hbound⟩ := exists_markedRatio_inv_sub_clipped_sq_le ι ht0 ht1
  set c : ℝ := d * 2 ^ (d + 1) * (C₀ ^ 2 + 1)
  have hc : 0 ≤ c := by positivity
  refine ⟨Real.sqrt c, fun δ hδ _ ε hε => ?_⟩
  -- The bracket of the finite-copy estimate tends to `c δ^{1-2t}`.
  set X : ℕ → ℝ := fun m => (C₀ * C₁ * ((m + 1 : ℕ) : ℝ) ^ (-t) * (δ ^ (2 * t))⁻¹) ^ 2 +
    d * (2 ^ d * (2 * C₀ ^ 2 * (δ + d / ((m + 1 : ℕ) : ℝ)) ^ (1 - 2 * t) +
      2 * (δ ^ (2 * t))⁻¹ * (δ + d / ((m + 1 : ℕ) : ℝ))))
  have hk : Tendsto (fun m : ℕ => ((m + 1 : ℕ) : ℝ)) atTop atTop :=
    tendsto_natCast_atTop_atTop.comp (tendsto_add_atTop_nat 1)
  have hpow : Tendsto (fun m : ℕ => ((m + 1 : ℕ) : ℝ) ^ (-t)) atTop (𝓝 0) :=
    (tendsto_rpow_neg_atTop ht0).comp hk
  have hdiv : Tendsto (fun m : ℕ => δ + d / ((m + 1 : ℕ) : ℝ)) atTop (𝓝 δ) := by
    simpa using tendsto_const_nhds.add (tendsto_const_nhds.div_atTop hk)
  have hlim : Tendsto X atTop (𝓝 (c * δ ^ (1 - 2 * t))) := by
    have h1 : Tendsto (fun m : ℕ => (C₀ * C₁ * ((m + 1 : ℕ) : ℝ) ^ (-t) * (δ ^ (2 * t))⁻¹) ^ 2)
        atTop (𝓝 0) := by
      simpa using (((tendsto_const_nhds.mul hpow).mul tendsto_const_nhds).pow 2)
    have h2 : Tendsto (fun m : ℕ => (δ + d / ((m + 1 : ℕ) : ℝ)) ^ (1 - 2 * t)) atTop
        (𝓝 (δ ^ (1 - 2 * t))) :=
      hdiv.rpow_const (Or.inl hδ.ne')
    have h3 : Tendsto X atTop (𝓝 (0 + (d : ℝ) * (2 ^ d * (2 * C₀ ^ 2 * δ ^ (1 - 2 * t) +
        2 * (δ ^ (2 * t))⁻¹ * δ)))) :=
      h1.add (tendsto_const_nhds.mul (tendsto_const_nhds.mul
        ((tendsto_const_nhds.mul h2).add (tendsto_const_nhds.mul hdiv))))
    convert h3 using 2
    have hδδ : (δ ^ (2 * t))⁻¹ * δ = δ ^ (1 - 2 * t) := by
      rw [← Real.rpow_neg hδ.le, ← Real.rpow_add_one hδ.ne']
      congr 1
      ring
    rw [mul_assoc 2 (δ ^ (2 * t))⁻¹, hδδ]
    simp only [c]
    ring
  set Y := Real.sqrt c * δ ^ ((1 - 2 * t) / 2) + ε
  have hYsq : c * δ ^ (1 - 2 * t) < Y ^ 2 := by
    have hδp : 0 ≤ δ ^ ((1 - 2 * t) / 2) := by positivity
    have hsq : (Real.sqrt c * δ ^ ((1 - 2 * t) / 2)) ^ 2 = c * δ ^ (1 - 2 * t) := by
      rw [mul_pow, Real.sq_sqrt hc, ← Real.rpow_natCast, ← Real.rpow_mul hδ.le]
      congr 2
      push_cast
      ring
    rw [← hsq]
    have : 0 ≤ Real.sqrt c * δ ^ ((1 - 2 * t) / 2) := by positivity
    nlinarith
  obtain ⟨K, hK⟩ := eventually_atTop.mp (hlim.eventually (gt_mem_nhds hYsq))
  refine ⟨K, fun m hm Q z hz => ?_⟩
  have hsq := hbound δ hδ m Q z hz
  rw [re_star_dotProduct_self_eq_norm_sq, re_star_dotProduct_self_eq_norm_sq] at hsq
  have hXY : X m ≤ Y ^ 2 := (hK m hm).le
  have h := hsq.trans (mul_le_mul_of_nonneg_right hXY (by positivity))
  have hY : 0 ≤ Y := by positivity
  rw [← mul_pow] at h
  exact (pow_le_pow_iff_left₀ (norm_nonneg _) (by positivity) two_ne_zero).mp h

end TensorPower
