/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import QICLean.Representation.TensorPowerAction

/-!
# Commutation of Schur labels and complementary labels on the symmetric subspace

This file proves part 2 of Lemma 6.1 (`lem:schur`) of the area-law paper
(*A two-dimensional area law from a global spectral gap*, `05-replicas.tex`,
lines 101–103, with proof at lines 168–181):

* central label functions commute for nested or disjoint subsystems;
* on the symmetric subspace `𝒮_k`, complementary label projectors agree,
  `π^λ_{Q,k} = π^λ_{Qᶜ,k}`, even when the two subsystem dimensions differ.

A *central label function* of the subsystem `Q` is the image under the copy
permutations of `Q` of a central element of `ℂ[S_k]`; the label projectors `π^λ_{Q,k}`
and label observables such as `F_{Q,k}` are central label functions.

The general mechanism is stated for a permutation action that factors as a
pointwise-commuting product of two actions: a central function of one factor
commutes with everything generated by the product, and on vectors fixed by the
product, a central function with inversion-invariant coefficients takes the same
value for both factors.

## Main declarations

* `TensorPower.commute_groupAlgebraRep_subsystemPerm_of_subset` — nested commutation.
* `TensorPower.commute_groupAlgebraRep_subsystemPerm_of_disjoint` — disjoint commutation.
* `TensorPower.labelProj_mulVec_compl_of_mem_symmetricSubspace`,
  `TensorPower.labelProj_mul_symProj_compl` — complementary labels on `𝒮_k`.
-/

open MonoidAlgebra Matrix

namespace PermutationRepresentation

variable {G X : Type*} [Group G] [Fintype X] [DecidableEq X]

/-- A central element of `ℂ[G]` acts by an operator commuting with every permutation
operator. -/
theorem commute_groupAlgebraRep_permOp_of_mem_center (φ : G →* Equiv.Perm X)
    {a : MonoidAlgebra ℂ G} (ha : a ∈ Subalgebra.center ℂ (MonoidAlgebra ℂ G)) (g : G) :
    Commute (groupAlgebraRep φ a) (permOp φ g) := by
  rw [Commute, SemiconjBy, ← one_smul ℂ (permOp φ g), ← groupAlgebraRep_single, ← map_mul,
    ← map_mul, Subalgebra.mem_center_iff.mp ha]

theorem permOp_of_eq_mul (φ χ ψ : G →* Equiv.Perm X) (hψ : ∀ g, ψ g = φ g * χ g) (g : G) :
    permOp ψ g = permOp φ g * permOp χ g := by
  rw [permOp_apply, permOp_apply, permOp_apply, hψ, _root_.mul_inv_rev, permMatrix_mul]

/-- **Nested commutation.** If `ψ = φ · χ` pointwise with `φ, χ` commuting, then a
central function of `φ` commutes with every operator generated by `ψ`. -/
theorem commute_groupAlgebraRep_of_eq_mul (φ χ ψ : G →* Equiv.Perm X)
    (hψ : ∀ g, ψ g = φ g * χ g) (hcomm : ∀ g h, Commute (φ g) (χ h))
    {a : MonoidAlgebra ℂ G} (ha : a ∈ Subalgebra.center ℂ (MonoidAlgebra ℂ G))
    (b : MonoidAlgebra ℂ G) : Commute (groupAlgebraRep φ a) (groupAlgebraRep ψ b) := by
  refine (commute_groupAlgebraRep_of_forall_commute ψ (fun g => ?_) b).symm
  rw [permOp_of_eq_mul φ χ ψ hψ g]
  refine Commute.mul_left (commute_groupAlgebraRep_permOp_of_mem_center φ ha g).symm ?_
  simpa using (commute_groupAlgebraRep_of_commute φ χ hcomm a (single g 1)).symm

/-- **Complementary labels on fixed vectors.** If `ψ = φ · χ` pointwise and `a ∈ ℂ[G]`
has inversion-invariant coefficients (as every central element of `ℂ[S_k]` does), then
`a` acts identically through `φ` and through `χ` on every vector fixed by `ψ`. -/
theorem groupAlgebraRep_mulVec_eq_of_eq_mul [Finite G] (φ χ ψ : G →* Equiv.Perm X)
    (hψ : ∀ g, ψ g = φ g * χ g) {a : MonoidAlgebra ℂ G}
    (hinv : ∀ g, a.coeff g⁻¹ = a.coeff g) {v : X → ℂ} (hv : v ∈ invariantSubspace ψ) :
    groupAlgebraRep φ a *ᵥ v = groupAlgebraRep χ a *ᵥ v := by
  have := Fintype.ofFinite G
  -- On fixed vectors, `U_χ(g) v = U_φ(g⁻¹) v`.
  have key : ∀ g, permOp χ g *ᵥ v = permOp φ g⁻¹ *ᵥ v := by
    intro g
    have h1 := hv g
    rw [permOp_of_eq_mul φ χ ψ hψ g, ← mulVec_mulVec] at h1
    calc permOp χ g *ᵥ v = permOp φ g⁻¹ *ᵥ (permOp φ g *ᵥ (permOp χ g *ᵥ v)) := by
          rw [mulVec_mulVec, permOp_inv_mul_self, one_mulVec]
      _ = permOp φ g⁻¹ *ᵥ v := by rw [h1]
  rw [groupAlgebraRep_eq_sum, groupAlgebraRep_eq_sum, sum_mulVec, sum_mulVec]
  simp_rw [smul_mulVec, key]
  refine Fintype.sum_equiv (Equiv.inv G) _ _ (fun g => ?_)
  rw [Equiv.inv_apply, inv_inv, hinv]

end PermutationRepresentation

namespace TensorPower

open PermutationRepresentation

variable {F : Type*} [DecidableEq F] (ι : F → Type*) [∀ f, Fintype (ι f)]
  [∀ f, DecidableEq (ι f)] (k : ℕ) [Fintype F]

/-- **Lemma 6.1(2), disjoint subsystems** (`05-replicas.tex`, lines 101–102, 176):
operators generated by the copy permutations of disjoint subsystems commute; in
particular their central label functions commute. -/
theorem commute_groupAlgebraRep_subsystemPerm_of_disjoint {Q Q' : Finset F}
    (h : Disjoint Q Q') (a b : MonoidAlgebra ℂ (Equiv.Perm (Fin k))) :
    Commute (groupAlgebraRep (subsystemPerm k ι Q) a)
      (groupAlgebraRep (subsystemPerm k ι Q') b) :=
  commute_groupAlgebraRep_of_commute _ _ (commute_subsystemPerm_of_disjoint k ι h) a b

/-- **Lemma 6.1(2), nested subsystems** (`05-replicas.tex`, lines 101–102, 172–175):
for `Q ⊆ Q'`, a central label function of `Q` commutes with every operator generated
by the copy permutations of `Q'`, in particular with every central label function
of `Q'`. -/
theorem commute_groupAlgebraRep_subsystemPerm_of_subset {Q Q' : Finset F} (h : Q ⊆ Q')
    {a : MonoidAlgebra ℂ (Equiv.Perm (Fin k))}
    (ha : a ∈ Subalgebra.center ℂ (MonoidAlgebra ℂ (Equiv.Perm (Fin k))))
    (b : MonoidAlgebra ℂ (Equiv.Perm (Fin k))) :
    Commute (groupAlgebraRep (subsystemPerm k ι Q) a)
      (groupAlgebraRep (subsystemPerm k ι Q') b) := by
  refine commute_groupAlgebraRep_of_eq_mul _ (subsystemPerm k ι (Q' \ Q)) _ (fun σ => ?_)
    (commute_subsystemPerm_of_disjoint k ι Finset.disjoint_sdiff) ha b
  conv_lhs => rw [← Finset.union_sdiff_of_subset h]
  exact subsystemPerm_union k ι Finset.disjoint_sdiff σ

/-- Label projectors of nested subsystems commute (`05-replicas.tex`, line 101). -/
theorem commute_labelProj_subsystemPerm_of_subset {Q Q' : Finset F} (h : Q ⊆ Q')
    (l l' : IrrepLabel (Equiv.Perm (Fin k))) :
    Commute (labelProj (subsystemPerm k ι Q) l) (labelProj (subsystemPerm k ι Q') l') :=
  commute_groupAlgebraRep_subsystemPerm_of_subset ι k h (IrrepLabel.centralIdem_mem_center l) _

/-- Label projectors of disjoint subsystems commute (`05-replicas.tex`, line 101). -/
theorem commute_labelProj_subsystemPerm_of_disjoint {Q Q' : Finset F} (h : Disjoint Q Q')
    (l l' : IrrepLabel (Equiv.Perm (Fin k))) :
    Commute (labelProj (subsystemPerm k ι Q) l) (labelProj (subsystemPerm k ι Q') l') :=
  commute_groupAlgebraRep_subsystemPerm_of_disjoint ι k h _ _

/-- On the symmetric subspace, a central label function of `Q` agrees with the same
central label function of the complement `Qᶜ` (`05-replicas.tex`, lines 176–181). -/
theorem groupAlgebraRep_mulVec_compl_of_mem_symmetricSubspace (Q : Finset F)
    {a : MonoidAlgebra ℂ (Equiv.Perm (Fin k))}
    (ha : a ∈ Subalgebra.center ℂ (MonoidAlgebra ℂ (Equiv.Perm (Fin k))))
    {v : Config k ι → ℂ} (hv : v ∈ symmetricSubspace k ι) :
    groupAlgebraRep (subsystemPerm k ι Q) a *ᵥ v =
      groupAlgebraRep (subsystemPerm k ι Qᶜ) a *ᵥ v := by
  refine groupAlgebraRep_mulVec_eq_of_eq_mul _ _ (copyPerm ((f : F) → ι f) k) (fun σ => ?_)
    (IrrepLabel.coeff_inv_of_mem_center ha) hv
  rw [← subsystemPerm_univ, ← Finset.union_compl Q]
  exact subsystemPerm_union k ι disjoint_compl_right σ

/-- **Lemma 6.1(2), complementary labels** (`05-replicas.tex`, lines 102–103): on the
symmetric subspace `𝒮_k`, `π^λ_{Q,k} = π^λ_{Qᶜ,k}`. -/
theorem labelProj_mulVec_compl_of_mem_symmetricSubspace (Q : Finset F)
    (l : IrrepLabel (Equiv.Perm (Fin k))) {v : Config k ι → ℂ}
    (hv : v ∈ symmetricSubspace k ι) :
    labelProj (subsystemPerm k ι Q) l *ᵥ v = labelProj (subsystemPerm k ι Qᶜ) l *ᵥ v :=
  groupAlgebraRep_mulVec_compl_of_mem_symmetricSubspace ι k Q
    (IrrepLabel.centralIdem_mem_center l) hv

/-- Operator form of complementary labels: `π^λ_{Q,k} Π_k = π^λ_{Qᶜ,k} Π_k`, where `Π_k`
is the orthogonal projector onto `𝒮_k`. -/
theorem labelProj_mul_symProj_compl (Q : Finset F) (l : IrrepLabel (Equiv.Perm (Fin k))) :
    labelProj (subsystemPerm k ι Q) l * symProj (copyPerm ((f : F) → ι f) k) =
      labelProj (subsystemPerm k ι Qᶜ) l * symProj (copyPerm ((f : F) → ι f) k) := by
  ext x y
  have h := labelProj_mulVec_compl_of_mem_symmetricSubspace ι k Q l
    (symProj_mulVec_mem (copyPerm ((f : F) → ι f) k) (Pi.single y 1))
  simp only [mulVec_single_one] at h
  exact congrFun h x

end TensorPower
