/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import QICLean.Representation.CommutantDimension

import Mathlib.RingTheory.MvPolynomial.Symmetric.NewtonIdentities

/-!
# The commutant of the copy permutations is generated by the diagonal action

Let `ℂ^Ω` be a finite-dimensional space and `(ℂ^Ω)^{⊗k}` its `k`-th tensor power, with
basis indexed by `Fin k → Ω`. For a matrix `A` on `ℂ^Ω` write `A^{(j)}` for `A` acting on
the `j`-th copy, and `Δ(A) = ∑_j A^{(j)}` for the diagonal (Lie-algebra) action. This file
proves the half of Schur–Weyl duality used for the Schur-label estimates of the area-law
paper (*A two-dimensional area law from a global spectral gap*, `05-replicas.tex`,
lines 46–64; the paper cites Etingof et al., Theorem 5.18.4): **every operator commuting
with the copy permutations lies in the algebra generated by the operators `Δ(A)`**.

## Method

* By Newton's identities, `A^{⊗k} = A^{(1)} ⋯ A^{(k)}`, the top elementary symmetric
  polynomial of the commuting family `A^{(j)}`, is a polynomial in the power sums
  `∑_j (A^{(j)})^m = Δ(A^m)`.
* By polarization, the symmetrization `∑_σ B_{σ 1} ⊗ ⋯ ⊗ B_{σ k}` equals
  `∑_{S} (-1)^{k - |S|} (∑_{i ∈ S} B_i)^{⊗k}`.
* An operator commuting with the copy permutations is the average of its conjugates, a
  combination of symmetrizations of elementary tensors of matrix units.

## Main declarations

* `TensorPower.partialTensor`, `TensorPower.siteOp`, `TensorPower.tensorPow`,
  `TensorPower.diagOp` — the operators `⊗_{j ∈ s} A_j`, `A^{(j)}`, `A^{⊗k}`, `Δ(A)`.
* `TensorPower.diagAlgebra` — the algebra generated by the operators `Δ(A)`.
* `TensorPower.tensorPow_mem_diagAlgebra` — `A^{⊗k}` lies in it.
* `TensorPower.commutant_le_diagAlgebra` — **Schur–Weyl**: the commutant of the copy
  permutations lies in it.
-/

open Finset Matrix PermutationRepresentation
open scoped IsMulCommutative

namespace TensorPower

variable {Ω : Type*} [Fintype Ω] [DecidableEq Ω] {k : ℕ}

/-- The operator `⊗_{j ∈ s} A_j`, acting by `A_j` on the copies `j ∈ s` and by the identity
on the others. -/
def partialTensor (s : Finset (Fin k)) (A : Fin k → Matrix Ω Ω ℂ) :
    Matrix (Fin k → Ω) (Fin k → Ω) ℂ :=
  fun x y => if ∀ i ∉ s, x i = y i then ∏ j ∈ s, A j (x j) (y j) else 0

omit [Fintype Ω] in
theorem partialTensor_apply (s : Finset (Fin k)) (A : Fin k → Matrix Ω Ω ℂ)
    (x y : Fin k → Ω) :
    partialTensor s A x y = if ∀ i ∉ s, x i = y i then ∏ j ∈ s, A j (x j) (y j) else 0 :=
  rfl

omit [Fintype Ω] in
@[simp]
theorem partialTensor_univ_apply (A : Fin k → Matrix Ω Ω ℂ) (x y : Fin k → Ω) :
    partialTensor univ A x y = ∏ j, A j (x j) (y j) := by
  simp [partialTensor_apply]

omit [Fintype Ω] in
@[simp]
theorem partialTensor_empty (A : Fin k → Matrix Ω Ω ℂ) : partialTensor ∅ A = 1 := by
  ext x y
  simp only [partialTensor_apply, notMem_empty, not_false_eq_true, forall_const,
    prod_empty, one_apply]
  by_cases h : x = y
  · simp [h]
  · have h' : ¬∀ i, x i = y i := fun h' => h (funext h')
    simp [h, h']

omit [Fintype Ω] in
theorem partialTensor_congr {s : Finset (Fin k)} {A B : Fin k → Matrix Ω Ω ℂ}
    (h : ∀ j ∈ s, A j = B j) : partialTensor s A = partialTensor s B := by
  ext x y
  simp only [partialTensor_apply]
  rw [prod_congr rfl fun j hj => by rw [h j hj]]

/-- Tensor products over disjoint sets of copies multiply. -/
theorem partialTensor_mul_partialTensor {s t : Finset (Fin k)} (hst : Disjoint s t)
    (A B : Fin k → Matrix Ω Ω ℂ) :
    partialTensor s A * partialTensor t B =
      partialTensor (s ∪ t) (fun j => if j ∈ s then A j else B j) := by
  ext x z
  rw [mul_apply]
  -- the only contributing intermediate configuration
  set y : Fin k → Ω := fun i => if i ∈ s then z i else x i with hy
  rw [Finset.sum_eq_single y]
  · simp only [partialTensor_apply]
    by_cases hxz : ∀ i ∉ s ∪ t, x i = z i
    · have h1 : ∀ i ∉ s, x i = y i := fun i hi => by simp [hy, hi]
      have h2 : ∀ i ∉ t, y i = z i := by
        intro i hi
        by_cases his : i ∈ s
        · simp [hy, his]
        · simp only [hy, his, ite_false]
          exact hxz i (by simp [his, hi])
      rw [ite_eq_left h1, ite_eq_left h2, ite_eq_left hxz, prod_union hst]
      congr 1
      · refine prod_congr rfl fun j hj => ?_
        simp [hj, hy]
      · refine prod_congr rfl fun j hj => ?_
        have hjs : j ∉ s := disjoint_right.mp hst hj
        simp [hjs, hy]
    · rw [ite_eq_right hxz]
      push Not at hxz
      obtain ⟨i, hi, hne⟩ := hxz
      simp only [mem_union, not_or] at hi
      by_cases h2 : ∀ i ∉ t, y i = z i
      · exact absurd (by simpa [hy, hi.1] using h2 i hi.2) hne
      · rw [ite_eq_right h2, mul_zero]
  · intro y' _ hy'
    simp only [partialTensor_apply]
    by_cases h1 : ∀ i ∉ s, x i = y' i
    · by_cases h2 : ∀ i ∉ t, y' i = z i
      · exfalso
        apply hy'
        funext i
        by_cases his : i ∈ s
        · simp only [hy, his, ite_true]
          exact h2 i (disjoint_left.mp hst his)
        · simp only [hy, his, ite_false]
          exact (h1 i his).symm
      · rw [ite_eq_right h2, mul_zero]
    · rw [ite_eq_right h1, zero_mul]
  · simp

/-- Tensor products over disjoint sets of copies commute. -/
theorem commute_partialTensor {s t : Finset (Fin k)} (hst : Disjoint s t)
    (A B : Fin k → Matrix Ω Ω ℂ) : Commute (partialTensor s A) (partialTensor t B) := by
  rw [Commute, SemiconjBy, partialTensor_mul_partialTensor hst,
    partialTensor_mul_partialTensor hst.symm, union_comm]
  refine partialTensor_congr fun j hj => ?_
  by_cases hjs : j ∈ s
  · simp [hjs, disjoint_left.mp hst hjs]
  · have hjt : j ∈ t := by simpa [hjs] using hj
    simp [hjs, hjt]

/-- The operator `A^{(j)}`: `A` acting on the `j`-th copy. -/
def siteOp (j : Fin k) (A : Matrix Ω Ω ℂ) : Matrix (Fin k → Ω) (Fin k → Ω) ℂ :=
  partialTensor {j} fun _ => A

/-- The operator `A^{⊗k}`. -/
def tensorPow (A : Matrix Ω Ω ℂ) : Matrix (Fin k → Ω) (Fin k → Ω) ℂ :=
  partialTensor univ fun _ => A

/-- The diagonal action `Δ(A) = ∑_j A^{(j)}`. -/
def diagOp (A : Matrix Ω Ω ℂ) : Matrix (Fin k → Ω) (Fin k → Ω) ℂ :=
  ∑ j, siteOp j A

variable (Ω k) in
/-- The algebra generated by the diagonal action. -/
noncomputable def diagAlgebra : Subalgebra ℂ (Matrix (Fin k → Ω) (Fin k → Ω) ℂ) :=
  Algebra.adjoin ℂ (Set.range (diagOp (Ω := Ω) (k := k)))

theorem diagOp_mem_diagAlgebra (A : Matrix Ω Ω ℂ) : diagOp (k := k) A ∈ diagAlgebra Ω k :=
  Algebra.subset_adjoin ⟨A, rfl⟩

omit [Fintype Ω] in
theorem siteOp_apply (j : Fin k) (A : Matrix Ω Ω ℂ) (x y : Fin k → Ω) :
    siteOp j A x y = if ∀ i, i ≠ j → x i = y i then A (x j) (y j) else 0 := by
  simp [siteOp, partialTensor_apply]

theorem siteOp_mul_siteOp (j : Fin k) (A B : Matrix Ω Ω ℂ) :
    siteOp j A * siteOp j B = siteOp j (A * B) := by
  ext x z
  rw [mul_apply, siteOp_apply, mul_apply]
  have hsupp : ∀ y ∈ (univ : Finset (Fin k → Ω)), y ∉ univ.image (Function.update x j) →
      siteOp j A x y * siteOp j B y z = 0 := by
    intro y _ hy
    rw [siteOp_apply, ite_eq_right, zero_mul]
    intro h
    apply hy
    refine mem_image.mpr ⟨y j, mem_univ _, ?_⟩
    funext i
    by_cases hij : i = j
    · subst hij; simp
    · simp [hij, h i hij]
  rw [← sum_subset (subset_univ _) hsupp,
    sum_image (fun a _ b _ h => by simpa using congrFun h j)]
  by_cases hxz : ∀ i, i ≠ j → x i = z i
  · rw [ite_eq_left hxz]
    refine sum_congr rfl fun a _ => ?_
    rw [siteOp_apply, siteOp_apply, ite_eq_left, ite_eq_left]
    · simp
    · intro i hij; simp [hij, hxz i hij]
    · intro i hij; simp [hij]
  · rw [ite_eq_right hxz]
    refine sum_eq_zero fun a _ => ?_
    push Not at hxz
    obtain ⟨i, hij, hne⟩ := hxz
    rw [siteOp_apply j B, ite_eq_right, mul_zero]
    intro h
    exact hne (by simpa [hij] using h i hij)

omit [Fintype Ω] in
@[simp]
theorem siteOp_one (j : Fin k) : siteOp j (1 : Matrix Ω Ω ℂ) = 1 := by
  ext x y
  rw [siteOp_apply, one_apply, one_apply]
  by_cases h : x = y
  · simp [h]
  · by_cases h' : ∀ i, i ≠ j → x i = y i
    · have hj : x j ≠ y j := fun hj => h (funext fun i => by
        by_cases hij : i = j
        · subst hij; exact hj
        · exact h' i hij)
      simp [h, hj]
    · simp [h, h']

theorem siteOp_pow (j : Fin k) (A : Matrix Ω Ω ℂ) (m : ℕ) :
    siteOp j A ^ m = siteOp j (A ^ m) := by
  induction m with
  | zero => simp
  | succ m ih => rw [pow_succ, ih, siteOp_mul_siteOp, ← pow_succ]

theorem commute_siteOp (i j : Fin k) (A : Matrix Ω Ω ℂ) :
    Commute (siteOp i A) (siteOp j A) := by
  by_cases hij : i = j
  · rw [hij]
  · exact commute_partialTensor (disjoint_singleton.mpr hij) _ _

/-! ### Newton's identities: tensor powers lie in the diagonal algebra -/

/-- By Newton's identities, every elementary symmetric polynomial lies in the subalgebra
generated by the power sums (over `ℂ`). -/
theorem _root_.MvPolynomial.esymm_mem_adjoin_psum (σ : Type*) [Fintype σ] (n : ℕ) :
    MvPolynomial.esymm σ ℂ n ∈ Algebra.adjoin ℂ (Set.range (MvPolynomial.psum σ ℂ)) := by
  induction n using Nat.strong_induction_on with
  | _ n ih =>
  rcases Nat.eq_zero_or_pos n with rfl | hn
  · rw [MvPolynomial.esymm_zero]
    exact one_mem _
  set S := Algebra.adjoin ℂ (Set.range (MvPolynomial.psum σ ℂ))
  have hmem : (n : MvPolynomial σ ℂ) * MvPolynomial.esymm σ ℂ n ∈ S := by
    rw [MvPolynomial.mul_esymm_eq_sum]
    refine mul_mem (pow_mem (neg_mem (one_mem _)) _) (sum_mem fun a ha => ?_)
    exact mul_mem (mul_mem (pow_mem (neg_mem (one_mem _)) _)
      (ih a.1 (mem_filter.mp ha).2)) (Algebra.subset_adjoin ⟨a.2, rfl⟩)
  have hn' : (n : ℂ) ≠ 0 := by exact_mod_cast hn.ne'
  have heq : MvPolynomial.esymm σ ℂ n =
      (n : ℂ)⁻¹ • ((n : MvPolynomial σ ℂ) * MvPolynomial.esymm σ ℂ n) := by
    rw [show (n : MvPolynomial σ ℂ) = algebraMap ℂ _ (n : ℂ) by simp, ← Algebra.smul_def,
      smul_smul, inv_mul_cancel₀ hn', one_smul]
  rw [heq]
  exact S.smul_mem hmem _

/-- `A^{⊗k}` lies in the algebra generated by the diagonal action. -/
theorem tensorPow_mem_diagAlgebra (A : Matrix Ω Ω ℂ) : tensorPow A ∈ diagAlgebra Ω k := by
  have hcomm : (Set.range fun j : Fin k => siteOp j A).Pairwise Commute := by
    rintro _ ⟨i, rfl⟩ _ ⟨j, rfl⟩ _
    exact commute_siteOp i j A
  have := Algebra.isMulCommutative_adjoin ℂ hcomm
  set C := Algebra.adjoin ℂ (Set.range fun j : Fin k => siteOp j A)
  let c : Fin k → C := fun j => ⟨siteOp j A, Algebra.subset_adjoin ⟨j, rfl⟩⟩
  let ψ : MvPolynomial (Fin k) ℂ →ₐ[ℂ] Matrix (Fin k → Ω) (Fin k → Ω) ℂ :=
    C.val.comp (MvPolynomial.aeval c)
  have hprod : ∀ s : Finset (Fin k),
      ((∏ j ∈ s, c j : C) : Matrix (Fin k → Ω) (Fin k → Ω) ℂ) =
        partialTensor s fun _ => A := by
    intro s
    induction s using Finset.induction_on with
    | empty => simp
    | insert j s hj ih =>
      rw [prod_insert hj, Subalgebra.coe_mul, ih]
      change partialTensor {j} (fun _ => A) * _ = _
      rw [partialTensor_mul_partialTensor (disjoint_singleton_left.mpr hj), singleton_union]
      exact partialTensor_congr fun i _ => by split_ifs <;> rfl
  have hψe : ψ (MvPolynomial.esymm (Fin k) ℂ k) = tensorPow A := by
    have h : powersetCard k (univ : Finset (Fin k)) = {univ} := by
      simpa using powersetCard_self (univ : Finset (Fin k))
    rw [MvPolynomial.esymm, h, sum_singleton]
    change ((MvPolynomial.aeval c (∏ j, MvPolynomial.X j) : C) :
      Matrix (Fin k → Ω) (Fin k → Ω) ℂ) = _
    rw [map_prod]
    simp only [MvPolynomial.aeval_X]
    exact hprod univ
  have hψp : ∀ m, ψ (MvPolynomial.psum (Fin k) ℂ m) = diagOp (A ^ m) := by
    intro m
    simp [ψ, c, MvPolynomial.psum, diagOp, siteOp_pow]
  rw [← hψe]
  have h1 := MvPolynomial.esymm_mem_adjoin_psum (Fin k) k
  have h2 : (Algebra.adjoin ℂ (Set.range (MvPolynomial.psum (Fin k) ℂ))).map ψ ≤
      diagAlgebra Ω k := by
    rw [AlgHom.map_adjoin]
    refine Algebra.adjoin_le ?_
    rintro _ ⟨_, ⟨m, rfl⟩, rfl⟩
    rw [hψp]
    exact diagOp_mem_diagAlgebra _
  exact h2 ⟨_, h1, rfl⟩

/-! ### Polarization -/

/-- The symmetrization `∑_σ B_{σ 1} ⊗ ⋯ ⊗ B_{σ k}`. -/
def symTensor (B : Fin k → Matrix Ω Ω ℂ) : Matrix (Fin k → Ω) (Fin k → Ω) ℂ :=
  ∑ σ : Equiv.Perm (Fin k), partialTensor univ (B ∘ σ)

/-- Inclusion–exclusion over the supersets of `T`. -/
theorem sum_superset_neg_one_pow (T : Finset (Fin k)) :
    ∑ S ∈ univ.filter (T ⊆ ·), (-1 : ℂ) ^ #Sᶜ = if T = univ then 1 else 0 := by
  have h : ∑ S ∈ univ.filter (T ⊆ ·), (-1 : ℂ) ^ #Sᶜ = ∑ U ∈ Tᶜ.powerset, (-1 : ℂ) ^ #U := by
    refine sum_nbij' (fun S => Sᶜ) (fun U => Uᶜ) ?_ ?_ ?_ ?_ ?_
    · intro S hS
      simpa [compl_subset_compl] using (mem_filter.mp hS).2
    · intro U hU
      simp only [mem_filter, mem_univ, true_and]
      intro x hx
      rw [mem_compl]
      intro hxU
      exact mem_compl.mp (mem_powerset.mp hU hxU) hx
    · intro S _; simp
    · intro U _; simp
    · intro S _; rfl
  rw [h]
  have := congrArg (fun z : ℤ => (z : ℂ)) (sum_powerset_neg_one_pow_card (x := Tᶜ))
  simp only [Int.cast_sum, Int.cast_pow, Int.cast_neg, Int.cast_one] at this
  rw [this]
  by_cases hT : T = univ
  · simp [hT]
  · simp [hT, compl_eq_empty_iff]

/-- Summing over the maps `Fin k → Fin k` with full image is summing over permutations. -/
theorem sum_image_eq_univ_eq_sum_perm (g : (Fin k → Fin k) → ℂ) :
    ∑ f, (if univ.image f = univ then g f else 0) = ∑ σ : Equiv.Perm (Fin k), g σ := by
  rw [← sum_filter]
  have h : univ.filter (fun f : Fin k → Fin k => univ.image f = univ) =
      univ.map ⟨fun σ : Equiv.Perm (Fin k) => ⇑σ, DFunLike.coe_injective⟩ := by
    ext f
    simp only [mem_filter, mem_univ, true_and, mem_map, Function.Embedding.coeFn_mk]
    constructor
    · intro hf
      have hs : Function.Surjective f := fun b => by
        have : b ∈ univ.image f := by rw [hf]; exact mem_univ b
        simpa using this
      exact ⟨Equiv.ofBijective f ⟨Finite.injective_iff_surjective.mpr hs, hs⟩, rfl⟩
    · rintro ⟨σ, rfl⟩
      exact eq_univ_of_forall fun b => mem_image.mpr ⟨σ.symm b, mem_univ _, by simp⟩
  rw [h, sum_map]
  rfl

omit [Fintype Ω] in
theorem tensorPow_sum (S : Finset (Fin k)) (B : Fin k → Matrix Ω Ω ℂ) :
    tensorPow (k := k) (∑ i ∈ S, B i) =
      ∑ f ∈ Fintype.piFinset fun _ => S, partialTensor univ (B ∘ f) := by
  ext x y
  simp only [tensorPow, partialTensor_univ_apply, Matrix.sum_apply, Function.comp_apply]
  exact prod_univ_sum (fun _ => S) fun j i => B i (x j) (y j)

omit [Fintype Ω] in
/-- **Polarization.** `∑_σ ⊗_j B_{σ j} = ∑_S (-1)^{k - |S|} (∑_{i ∈ S} B_i)^{⊗k}`. -/
theorem symTensor_eq_sum (B : Fin k → Matrix Ω Ω ℂ) :
    symTensor B = ∑ S : Finset (Fin k), ((-1 : ℂ) ^ #Sᶜ) • tensorPow (k := k) (∑ i ∈ S, B i) := by
  simp_rw [tensorPow_sum, smul_sum]
  ext x y
  simp only [symTensor, Matrix.sum_apply, Matrix.smul_apply, smul_eq_mul]
  set P : (Fin k → Fin k) → ℂ := fun f => partialTensor univ (B ∘ f) x y
  change ∑ σ : Equiv.Perm (Fin k), P σ = ∑ S, ∑ f ∈ Fintype.piFinset fun _ => S, (-1) ^ #Sᶜ * P f
  rw [← sum_image_eq_univ_eq_sum_perm]
  have : ∀ S : Finset (Fin k), ∑ f ∈ Fintype.piFinset (fun _ => S), (-1 : ℂ) ^ #Sᶜ * P f =
      ∑ f, if univ.image f ⊆ S then (-1) ^ #Sᶜ * P f else 0 := by
    intro S
    rw [← sum_filter]
    congr 1
    ext f
    simp [image_subset_iff]
  simp_rw [this]
  rw [sum_comm]
  refine sum_congr rfl fun f _ => ?_
  rw [← sum_filter, ← sum_mul, show univ.filter (fun S : Finset (Fin k) => univ.image f ⊆ S) =
    univ.filter (univ.image f ⊆ ·) from rfl, sum_superset_neg_one_pow]
  split_ifs <;> simp

theorem symTensor_mem_diagAlgebra (B : Fin k → Matrix Ω Ω ℂ) :
    symTensor B ∈ diagAlgebra Ω k := by
  rw [symTensor_eq_sum]
  exact sum_mem fun S _ => Subalgebra.smul_mem _ (tensorPow_mem_diagAlgebra _) _

/-! ### The commutant -/

/-- An operator commuting with the copy permutations is the average of its conjugates. -/
theorem eq_smul_sum_symTensor_of_mem_commutant {M : Matrix (Fin k → Ω) (Fin k → Ω) ℂ}
    (hM : M ∈ commutant (copyPerm Ω k)) :
    M = ((k.factorial : ℂ)⁻¹) •
      ∑ x, ∑ y, M x y • symTensor (fun j => Matrix.single (x j) (y j) (1 : ℂ)) := by
  ext z w
  simp only [Matrix.smul_apply, Matrix.sum_apply, symTensor, smul_eq_mul,
    partialTensor_univ_apply, Function.comp_apply, Matrix.single_apply, mul_sum]
  simp only [Fintype.prod_ite_zero, prod_const_one]
  have key : ∀ σ : Equiv.Perm (Fin k), (∑ x, ∑ y, (k.factorial : ℂ)⁻¹ *
      (M x y * if ∀ i, x (σ i) = z i ∧ y (σ i) = w i then 1 else 0)) =
        (k.factorial : ℂ)⁻¹ * M z w := by
    intro σ
    rw [sum_eq_single (fun j => z (σ.symm j)), sum_eq_single (fun j => w (σ.symm j))]
    · rw [ite_eq_left (by simp), mul_one]
      have := apply_eq_of_mem_commutant (copyPerm Ω k) hM σ z w
      exact congrArg _ this
    · intro y _ hy
      rw [ite_eq_right, mul_zero, mul_zero]
      intro h
      apply hy
      funext j
      simpa using (h (σ.symm j)).2
    · simp
    · intro x _ hx
      refine sum_eq_zero fun y _ => ?_
      rw [ite_eq_right, mul_zero, mul_zero]
      intro h
      apply hx
      funext j
      simpa using (h (σ.symm j)).1
    · simp
  have hk : (k.factorial : ℂ) ≠ 0 := by exact_mod_cast k.factorial_ne_zero
  calc M z w = ∑ σ : Equiv.Perm (Fin k), (k.factorial : ℂ)⁻¹ * M z w := by
        rw [sum_const, card_univ, Fintype.card_perm, Fintype.card_fin, nsmul_eq_mul,
          ← mul_assoc, mul_inv_cancel₀ hk, one_mul]
    _ = _ := sum_congr rfl fun σ _ => (key σ).symm
    _ = _ := sum_comm
    _ = _ := sum_congr rfl fun x _ => sum_comm

/-- **Schur–Weyl duality** (`05-replicas.tex`, lines 46–64; Etingof et al.,
Theorem 5.18.4): every operator on `(ℂ^Ω)^{⊗k}` commuting with the copy permutations lies in
the algebra generated by the diagonal action. -/
theorem commutant_le_diagAlgebra :
    commutant (copyPerm Ω k) ≤ Subalgebra.toSubmodule (diagAlgebra Ω k) := by
  intro M hM
  rw [eq_smul_sum_symTensor_of_mem_commutant hM]
  exact Submodule.smul_mem _ _ (Submodule.sum_mem _ fun x _ => Submodule.sum_mem _ fun y _ =>
    Submodule.smul_mem _ _ (symTensor_mem_diagAlgebra _))

end TensorPower
